### ISSUE TITLE
2.4.0 pr9.5 fails to install

### ISSUE THREAD

**Issue by ncrecc** [BenVlodgi/BEE2.4#102]
I went into bin and double-clicked BEE2.exe as usual, it didn't open the first time so I tried it again, I selected Portal 2's game directory and double clicked portal2.exe, then it gave me this error:

```
    --------------

    Monday 31 August 2015 01:30:25PM:
    =================================
    Traceback (most recent call last):
  File "BEE2.pyw", line 97, in <module>
  File "F:\Git\BEE2.4\src\packageLoader.py", line 143, in load_packages
  File "F:\Git\BEE2.4\src\packageLoader.py", line 90, in find_packages
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\nathan\\Downloads\\BEE2.4_pr9.5_win\\packages'
```

I ran StyleChanger.exe, hoping that would fix the problem, but I tried running BEE2.4.exe again and it just gave me the same error. I already had BEE2 installed, by the way.

**Comment by TeamSpen210** [comment]
Did you grab the packages download as well? The zips need to be copied to a packages/ directory in the BEE2.4.

Running the stylechanger exe isn't needed for the BEE2.4, it'll actually do the wrong thing anyway.

**Comment by ncrecc** [comment]
I can't find any download for packages anywhere.

**Comment by TeamSpen210** [comment]
Get the packages [here](https://github.com/TeamSpen210/BEE2-items/releases)
