### ISSUE TITLE
2.4.0pr9 BUG

### ISSUE THREAD

**Issue by k0rny13** [BenVlodgi/BEE2.4#105]
Hello there !

I'm testing your new pre-release. I have a few problems here. First, I created a package directory like you explained.
Then I put some items in the palette, including Death Fizzler to try it. The export works fine. But, here is what I have in the editor and ingame : 
![2015-09-04_00002](https://cloud.githubusercontent.com/assets/13617963/9685204/103147c0-531d-11e5-96b5-024e417fe1c7.jpg)
![2015-09-04_00001](https://cloud.githubusercontent.com/assets/13617963/9685207/153b7718-531d-11e5-9dc8-d44bfc6563e4.jpg)

Also, sometimes when I drag out an item from the palette into the editor to place it on the map, Portal 2 crashes and I cannot re open the map again. It crashes too when i try to re open it.

Could you help me with this issue ? Thx a lot.

Best regards.

**Comment by k0rny13** [comment]
Not any ideas ?

**Comment by TeamSpen210** [comment]
To fix the icons, delete `BEE2_EDIT_FLAG` in your Portal 2 folder. For the crashing issue, which item is it?

**Comment by k0rny13** [comment]
Mostly the different type of fizzlers. But with your fix icons solution, for now it seems to be stable. I iwll let you know if it crashes again. Thank you.
