### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by Latreso** [BenVlodgi/BEE2.4#106]
Why, when i install BEE2 (nevest version) i see this error:
(yes i have "packages" folder, and into this folder .zip's)
![untitled](https://cloud.githubusercontent.com/assets/14235441/9815789/f93d0e56-5898-11e5-8085-858c1160fb31.png)

Give the tutorial in YouTube: How to install this!!!

**Comment by jccreszMinecraft** [comment]
You have to create a folder with a particular name, look around the older bug reports and you'll find the solution to this issue.

**Comment by Latreso** [comment]
I was looking for, but all the proposals were not working.

**Comment by TeamSpen210** [comment]
The doubled-up slashes don't mean anything, it's just a part of how text is written in Python. Do you have that packages folder, with the zips from the BEE2-items repository?
