### ISSUE TITLE
Death Fizzler visual glitch when starting Enabled and Reversed

### ISSUE THREAD

**Issue by k0rny13** [BenVlodgi/BEE2.4#107]
Hello !

This time I have a question regarding the "Death Fizzler" item. I have read all the instructions about how to make it work, but i'm still stuck about something.

I want to implement this to my maps, working like that : 
- Basic state : red fizzler 
![2015-09-15_00004](https://cloud.githubusercontent.com/assets/13617963/9873846/b93fac48-5ba2-11e5-96ed-2987d6b1c8a3.jpg)

- Alternate state by pushing a button with a cube : normal fizzler
![2015-09-15_00001](https://cloud.githubusercontent.com/assets/13617963/9873855/c502dbea-5ba2-11e5-84c5-d5aa135f428a.jpg)

I tried multiple combinations with inputs, SR Latch A, B etc... Each time I push the button, it changes the state from : activated, nothing, desactivated, nothing, fizzler, nothing, red fizzler, nothing, desactivated etc....

I do not understand how to make it work properly like I would like to. And when i set it "start enabled" and "reverse enabled", it appears like that, and it is not really nice : 
![2015-09-15_00002](https://cloud.githubusercontent.com/assets/13617963/9873899/22633e6a-5ba3-11e5-9f69-067edd4597d4.jpg)

Could you help me on this please ?

Thanks a lot. Best regards !

**Comment by TeamSpen210** [comment]
The issue with both enabled is just a visual glitch which I'll fix, you just need to press and unpress a button to make it look right. To do what you want, set it to start enabled (fizzler) and start reversed (laser). Connect an Input B item to it, and connect the button to that. You never want to connect anything directly to the fizzler, inputs have to pass through an input A/B item first.

**Comment by k0rny13** [comment]
Thanks you for answering. I did try and it works like that with your solution : 
- Start enabled and start reversed checked.
- Input B to the death fizzler, then button to input B
Result : 
- Button pressed : desactivate any field
- Button unpressed : activate fizzler + laser together, like i want.

But, is it possible that instead of desactivating everything when the button is pressed, to get the normal fizzler instead ? Here is the result I expect : 
- Button pressed : turns death fizzler into normal fizzler
- Button unpressed : activate fizzler + laser together.

Thank you again.

**Comment by TeamSpen210** [comment]
This should now be fixed.
