### ISSUE TITLE
I'd like to contribute

### ISSUE THREAD

**Issue by jccreszMinecraft** [BenVlodgi/BEE2.4#110]
Currently I'm in the process of making environmental in-chamber decorations to either make things look nice or add a bit of functionality to the chamber. I plan on making a few block variants, black/white wall variants with empty "doorways", and more. I have no idea how to script for BEEmod, but I can provide the VMFs which are easy to make style variances of. I also am working on a special skybox that would be used with another item I'm making.

So, what say ye, BenVlodgi and TeamSpen?

**Comment by TeamSpen210** [comment]
I'd be happy to have any additions other people can make! You'd want to fork and modify the BEE2-items repro to add items, in this case probably to the 'brushes' package (which I'm going to rename to something like 'decorations'). For block variants, it'd be better to use the purely config method like the current partial blocks - that means they automatically use the correct materials for each style.

For the config format, your best bet is probably just to copy-paste an item similar to what you want, and then modify that.

**Comment by jccreszMinecraft** [comment]
Honestly I just want to make and hand over the VMFs :P
