### ISSUE TITLE
Maps don't compile

### ISSUE THREAD

**Issue by Slartibarty** [BenVlodgi/BEE2.4#112]
Whenever I try to compile a map I get a 'There was an error building the puzzle', I've installed everything correctly so I'm not sure what is wrong.

**Comment by TeamSpen210** [comment]
Open up the developer console, and paste the message that's in there.

**Comment by Slartibarty** [comment]
exec: couldn't exec skill1.cfg
==== calling mapspawn.nut
Unable to load sprite material materials/sprites/gunsmoke.vmt!
Unable to load sprite material materials/sprites/bubble.vmt!
Attempted to create unknown entity type playtest_manager!
Can't init playtest_manager
Couldn't find any entities named doorentry0-player_start_teleport, which point_template @player_start_template is specifying.
Commentary: Could not find commentary data file 'maps/puzzlemaker\newchamber_commentary.txt'. 
1.000:  Sending UDP connect to public IP "My IP address is here"
Server using '<none>' lobbies, requiring pw no, lobby id 0
RememberIPAddressForLobby: lobby 0 from address loopback
Connection to Steam servers successful.
Can't find factory for entity: wearable_item
NULL Ent in UTIL_PrecacheOther
[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_autoportal_orange.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_autoportal_orange.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_autoportal_blue.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_autoportal_blue.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_autoportal_frame.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_autoportal_frame.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_null.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_null.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_portalgun1.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_portalgun1.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_portalgun2.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_portalgun2.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_portalgun3.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_portalgun3.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_crusher.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_crusher.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_combine_ball_catcher.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_combine_ball_catcher.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_combine_ball_launcher.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_combine_ball_launcher.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_ant_mag.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_ant_mag.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_ant_router.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_ant_router.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_checkpoint.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_checkpoint.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_checkpoint_sep.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_checkpoint_sep.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_ditch.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_ditch.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_a.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_a.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_b.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_b.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_chamberlock.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_chamberlock.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_vactube.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_vactube.3ds
[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------

==== calling mapspawn.nut
   VAC secure mode is activated.
[PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/SteamLibrary/Steam/steamapps/common/Portal 2/portal2/puzzles\76561197987478995\autosave.p2c
Parent cvar in client.dll not allowed (r_shadowlod)
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
Redownloading all lightmaps
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF D:/SteamLibrary/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 45 (ms)

VBSP failed.

Adding metacondition ("remove_blank_inst") with priority 1000!
Adding metacondition ("fix_catapult_targets") with priority 0!
Adding metacondition ("add_voice") with priority 100!
Adding metacondition ("fix_fizz_models") with priority -200!
Adding metacondition ("static_pan") with priority -100!
Adding metacondition ("anti_fizz_bump") with priority 200!
Adding metacondition ("set_player_portalgun") with priority 500!
BEE2 VBSP hook initiallised.
Map path is "D:/SteamLibrary/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
New path: "D:/SteamLibrary/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
PeTI map detected!
Loading settings...
Failed parsing weight! ([])
Failed parsing weight! ([])
Invalid weight! ()
Failed parsing weight! ([])
Settings Loaded!
Parsing Map...
Parsing complete!
['instances/bee2/over/elevator_sp/exit_corridor_1.vmf', 'instances/bee2/over/elevator_sp/exit_corridor_2.vmf', 'instances/bee2/over/elevator_sp/exit_corridor_3.vmf', 'instances/bee2/over/elevator_sp/exit_corridor_4.vmf']
File: instances/bee2/arrival_departure_transition_ents.vmf
File: instances/bee2/over/items/observation_room_256.vmf
File: instances/bee2/clean/point_light.vmf
File: instances/bee2/clean/point_light.vmf
File: instances/bee2/over/elevator_sp/exit_corridor_2.vmf
Setting exit to 1
File: instances/bee2/over/elevator_sp/entrance_corridor_5.vmf
Setting entry to 1
File: instances/bee2/clean/point_light.vmf
File: instances/bee2/over/elevator_sp/door_frame_black.vmf
File: instances/bee2/clean/point_light.vmf
File: instances/bee2/over/elevator_sp/elevator_entrance.vmf
File: instances/bee2/over/elevator_sp/elevator_exit.vmf
File: instances/bee2/over/elevator_sp/door_frame_black.vmf
Game Mode: SP
Is Preview: True
Checking Conditions...
Exiting empty condition!
Starting catwalk generator...
Exiting empty condition!
Exiting empty condition!
Adding Voice Lines!
Error - No Voice Line Data!
Setting Portalgun:
Blue: Y, Orange: Y
Done!
Map has attributes:  ['spawn_dual']
Style Vars: {'fixportalbump': False, 'multiversecave': False, 'fixfizzlerbump': False, 'nomidvoices': False, 'bee_show_trigger': False, 'unlockdefault': True, 'allowgoomist': True}
Global instances:  {'instances/BEE2/over/elevator_sp/wp_holes/wp_hole_1.vmf', 'instances/BEE2/over/elevator_sp/wp_holes/wp_hole_2.vmf', 'instances/BEE2/over/global_ents.vmf'}
Adding Music...
Adding Global PTI Ents
Editing Other Entities...
Editing Brushes...
Bottomless Pit: False
Adding Goo Mist...
Done!
Editing Overlays...
Editing Triggers...
Collapsing goo triggers...
Done!
Editing Brush Entities...
Special tex: False False 0.15
Removing static indicator toggles...
Done!
Editing WorldSpawn
Saving New Map...
Complete!
Calling original VBSP...
"D:\SteamLibrary\Steam\steamapps\common\Portal 2\bin\vbsp_original" -game "D:/SteamLibrary/Steam/steamapps/common/Portal 2/portal2/" "D:/SteamLibrary/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
Valve Software - vbsp.exe (Aug 26 2014)
8 threads
materialPath: D:\SteamLibrary\Steam\steamapps\common\Portal 2\portal2\materials
Loading D:/SteamLibrary/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
ConVarRef gpu_level doesn't point to an existing ConVar
Could not open instance file instances/lights/bts_light_fluorescent _01_128a.vmf

VBSP failed! (1)
