### ISSUE TITLE
Goo in BTS style shows as remnants of the other textures on the screen

### ISSUE THREAD

**Issue by ncrecc** [BenVlodgi/BEE2.4#113]
I forgot the technical term for it and Google isn't really helping.

**Comment by BenVlodgi** [comment]
could you explain this a bit more?

**Comment by ncrecc** [comment]
It's what happens when there's a leak, I think. It's something like [this](https://upload.wikimedia.org/wikipedia/en/6/6b/Winxp_estk_artifact.png), where the goo's texture is invalid (like the
