### ISSUE TITLE
A "Work in progress" map can't be opened again

### ISSUE THREAD

**Issue by k0rny13** [BenVlodgi/BEE2.4#115]
Hello.

I was working on a new map using the last pre-release 10, and of course I do not edit the map in a day. Today I have the surprise that I cannot open my map in the editor. When I try to open it, Portal 2 closes instantly. I tried a lot of times, always the same result.
Do you know a way to fix that ? Or is it totally impossible to get back the map in the editor ?

Thx a lot.

**Comment by TeamSpen210** [comment]
What items did you have in the map?

**Comment by k0rny13** [comment]
Hi Teamspen.
I used in the map : 
- Pedestral button
- Cube dropper with weighted cube
- Gel dropper (speed gel)
- Fizzler
- Laserfield
- Catwalk
- Pneumatic Diversity Vent
- Death Fizzler
- SR LATCH A/B
- Turret
- Tractor Beam
- Grating
- Laser Emitter and Laser catcher
- Weihgted Button
- White Lightstrip
- Coop checkpoint (the normal one, not the separated one)

Style used : Clean
Music : Random PeTI
Voice : Glados clean
Skybox : Darkness
(all suggested)

Coop map.

**Comment by k0rny13** [comment]
Any ideas my friend ?

**Comment by LautaroL20** [comment]
@k0rny13, I see on that list youve used "SR LATCH A/B" and "coop checkpoint, those items does not work. They can be the cause of that bug.

**Comment by TeamSpen210** [comment]
This is likely due to the Death Fizzler. PR11 should fix it.

**Comment by k0rny13** [comment]
OK. So no way to recover the map i guess :/

**Comment by k0rny13** [comment]
I just reopened the map and it works now... I just don't understand why lol

**Comment by LautaroL20** [comment]
@k0rny13, Its not a good idea making maps with the current releases. Until others pre-releases comes out, use it for testing purpose only if you dont want to lose your maping process again.
