### ISSUE TITLE
so when is the next update coming out

### ISSUE THREAD

**Issue by ellingtonisland** [BenVlodgi/BEE2.4#120]
@TeamSpen210 - so when is prerelease 12 coming out?

**Comment by xDadiKx** [comment]
Need to be patience.

**Comment by LautaroL20** [comment]
I am also very anxious to know the improvements it can bring the PRL12, but anyway it would be better for the mod that TeamSpen210 takes all its time.

**Comment by TeamSpen210** [comment]
The next update will come soon. I'm working on Aperture Tag support, but that requires modifications to all of the SP exits (4 per style), plus modifications to Coop entrances. I've also got to make styled versions of the Paint Gun Activation Fields.

**Comment by Iandavid123** [comment]
How long will it take Teamspen?
I hope it fixes some things, the new stuff in PR11 does not work in the game.
The instance files are missing for the new items.

**Comment by Enterpise** [comment]
@Iandavid123 It will release with Half-Life 3.
