### ISSUE TITLE
BEE2.4 can not install

### ISSUE THREAD

**Issue by AXEKING** [BenVlodgi/BEE2.4#122]
I can not run any .exe files in BEE2.4, this happens all the time, making it impossible to install, not only that but I can not give out the file.

It says, 

"Windows cannot access the specified device, path or file. You may not have the appropriate permissions to access the item."

This happens to all .exe files that came in Prerelease 11, can you please find an answer to this, or at the very least, make a automatic installer? 

I also need help trying to install this, I can't figure it out, and this error is not helping. The only thing I think I know is that you got to make BEE2.4 a path to Portal 2. Unfortunately the programs are refusing to run.

P.S. has this ever happened anybody else? I can't see any answers or mentions so far.

**Comment by Enrerpice** [comment]
All the pre releases are buggy as hell, i recomend you to wait for the next one wich will arrive soon.

**Comment by AXEKING** [comment]
I am completely aware that all pre releases are buggy. But I think this also happened on Pre Release 10, but I haven't tried that version yet, doubt it was gone it that version. Because it's in this version, plus its been 2 months since the last pre release. So the next one could be in 2016, however this could be false.

**Comment by AXEKING** [comment]
@TeamSpen210 can you please read this.

**Comment by Enterpise** [comment]
A pre release coming in 2016? LOL, for that time we should have a final version...

**Comment by AXEKING** [comment]
I said this could be false. This is my point of view.

**Comment by TeamSpen210** [comment]
What do you mean by "make BEE2.4 a path to Portal 2"? Extract the folders anywhere really.

**Comment by AXEKING** [comment]
I can't access the program.
