### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by Rebunkee** [BenVlodgi/BEE2.4#125]
I couldn't download the installer from the site, and i downloaded this. But how to install?

**Comment by LautaroL20** [comment]
1. First make a new folder anywhere, and then extract both "BEE2.4_pr12.1_win.zip" and "BEE2.4_pr12_packages" files on it. 
2. Now go to the "bin" folder, and then search for "BEE2.exe", launch it and happy using!

**Comment by Rebunkee** [comment]
Thank you, it works now. But it seems that the rocket robot thing doesn't work. How do you fix this?

**Comment by LautaroL20** [comment]
This is a "Pre release" so, some items may not work (like the logic gates). TeamSpen210 is the main developer of Bee 2.4. If you got any questions, you can ask him through his steam profile.

**Comment by Rebunkee** [comment]
Thank you kindly sir. I'll just wait for the next more stable release.
