### ISSUE TITLE
How to Install new items?

### ISSUE THREAD

**Issue by BarbarianKabbage** [BenVlodgi/BEE2.4#128]
How do I install the BEE2Items-master to BEEMOD2?

**Comment by TeamSpen210** [comment]
The releases are here:
https://github.com/BenVlodgi/BEE2.4/releases
https://github.com/TeamSpen210/BEE2-items/releases
Download both, and extract the contents to a folder somewhere. Then run BEE2.exe in the `bin/` folder.
