### ISSUE TITLE
Better 'destroyed' antlines

### ISSUE THREAD

**Issue by TeamSpen210** [BenVlodgi/BEE2.4#131]
Old Aperture antlines currently produce very large sections of antline, which looks wrong. The compiler should generate extra overlay ents with a higher renderOrder, so only 3 or so are broken. Potentially spark ents could be produced as well. 

Options:
* [X] 'overlay.antlineBroken...', new texture name for the broken antline
* [X] 'broken_antline_distance': the maximum number to be broken at once
* [X] 'broken_antline_chance': The chance for a given antline to be broken
* [ ] 'broken_antline_spark': Spawn an env_spark entity at the center of broken segments.

* [X] For a section < destAntlineRun long (corners), the overlay will be replaced with the texture. 
* [X] Otherwise, extra overlays will be added on top. 
* [x] If special.antlineBroken is not defined, no textures will be replaced - this is used to just spawn spark entities.

**Comment by Konclan** [comment]
I honestly think they are fine without sparks. Perhaps you can make them spark when they reach a cutout tile or something
