### ISSUE TITLE
suggestion for "pitfall" logic for skybox for bottomless pit

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BenVlodgi/BEE2.4#132]
@TeamSpen210 and @BenVlodgi - i have two big other ideas for bottomless pit generation

first one is to use a large world portal to make it so if the player falls into the pit and looks up before they fall into the pit, a world portal placed in the sky box and a world portal placed in the goo pit linked together (surround the instances that the main test chamber is in with a large sealed box to prevent leaks and place the world portal at the bottom of the goopit, make it so goo pits can't overlap too) makes it so they would see the test chamber looking up, this also would allow paint to fall into the pit etc.

another idea is to redo the design of the bottomless pit all together and for maps with bottomless pits, generate a large box around the main test chamber instances and texture the outsides of the wall and ceiling and floor instances in the test chamber and place random panel arms etc on them, if a goo pit is placed destined to be a bottomless pit, all you would need to do is remove the floor instances and create timed delay fade and kill and cube destruction instances in the pit and fill the sides with broken panels etc, then find a way to place instances around the outside of the test chamber to create a nice looking pit for wheatly style, this would work well for removing ceiling and wall parts too etc. the challenge would be figuring out how to generate instances outside the map so they wouldn't collide inside the test chamber.

**Comment by BenVlodgi** [comment]
I don't think a world portal covering the bottom of the whole floor is feasible, to test this, export a PTI map and implement the idea you are proposing, make sure this works without a great performance hit, and on all levels of shader detail.

For the other idea, one problem is that floor is not made of instances. Could you detail how you propose we identify which brushes are floor brushes from reading the VMF?
