### ISSUE TITLE
Failure to compile

### ISSUE THREAD

**Issue by towergame** [BenVlodgi/BEE2.4#134]
I am using the BTS style and crushers.
Log:
    VBSP failed.

Adding metacondition ("remove_blank_inst") with priority 1000!
Adding metacondition ("fix_catapult_targets") with priority 0!
Adding metacondition ("res_find_potential_tag_fizzlers") with priority -110!
Adding metacondition ("find_indicator_panels") with priority -1000!
Adding metacondition ("add_voice") with priority 100!
Adding metacondition ("add_fizz_borders") with priority -250!
Adding metacondition ("fix_fizz_models") with priority -200!
Adding metacondition ("static_pan") with priority -100!
Adding metacondition ("find_panel_locs") with priority -1000!
Adding metacondition ("anti_fizz_bump") with priority 200!
Adding metacondition ("set_player_portalgun") with priority 500!
Adding metacondition ("add_screenshot_logic") with priority 750!
Adding metacondition ("set_elev_videos") with priority 50!
Adding metacondition ("ap_tag_modifications") with priority 200!
BEE2.4.0pr14 VBSP hook initiallised.
Map path is "D:/steamgames/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
New path: "D:/steamgames/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
PeTI map detected!
Loading settings...
Settings Loaded!
Parsing Map...
Parsing complete!
Forcing elevator spawn!
['instances/bee2/bts/elevator_sp/exit_corridor_1.vmf', 'instances/bee2/bts/elevator_sp/exit_corridor_2.vmf', 'instances/bee2/bts/elevator_sp/exit_corridor_3.vmf', 'instances/bee2/bts/elevator_sp/exit_corridor_4.vmf']
File: instances/bee2/logic/indicator_toggle.vmf
File: 
File: instances/bee2/logic/indicator_toggle.vmf
File: instances/bee2/bts/items/observation_room_256.vmf
File: instances/bee2/logic/indicator_toggle.vmf
File: instances/bee2/clean/items/bee/crusher.vmf
File: instances/bee2/logic/indicator_toggle.vmf
File: instances/bee2/clean/items/bee/crusher.vmf
File: instances/bee2/bts/items/panel_angled.vmf
File: instances/bee2/logic/indicator_toggle.vmf
File: instances/bee2/logic/bee/trigger_multiple.vmf
File: instances/bee2/logic/indicator_toggle.vmf
File: instances/bee2/clean/items/turret.vmf
File: instances/bee2/logic/indicator_toggle.vmf
File: instances/bee2/clean/items/turret.vmf
File: instances/bee2/bts/items/panel_angled.vmf
File: instances/bee2/bts/items/fizzler/model.vmf
File: instances/bee2/bts/items/button/pedestal_button.vmf
File: instances/bee2/bts/items/fizzler/model.vmf
File: instances/bee2/clean/items/panel_clear.vmf
File: instances/bee2/bts/items/panel_angled.vmf
File: instances/bee2/logic/bee/trigger_once.vmf
File: instances/bee2/clean/items/panel_clear.vmf
File: instances/bee2/clean/items/panel_clear.vmf
File: instances/bee2/logic/bee/trigger_multiple.vmf
File: instances/bee2/clean/items/panel_clear.vmf
File: instances/bee2/bts/items/panel_angled.vmf
File: instances/bee2/clean/items/panel_clear.vmf
File: instances/bee2/logic/bee/trigger_multiple.vmf
File: instances/bee2/logic/bee/trigger_once.vmf
File: instances/bee2/logic/bee/trigger_once.vmf
File: instances/bee2/bts/point_light.vmf
File: instances/bee2/clean/items/bee/door.vmf
File: instances/bee2/logic/bee/trigger_multiple.vmf
File: instances/bee2/bts/point_light.vmf
File: instances/bee2/bts/point_light.vmf
File: instances/bee2/bts/point_light.vmf
File: 
File: instances/bee2/bts/point_light.vmf
File: instances/bee2/bts/elevator_sp/entrance_corridor_6.vmf
Setting entry to 1
File: instances/bee2/bts/point_light.vmf
File: instances/bee2/bts/elevator_sp/elevator_entrance.vmf
File: instances/bee2/bts/items/fizzler/base.vmf
File: instances/bee2/bts/point_light.vmf
File: instances/bee2/bts/elevator_sp/elevator_exit.vmf
File: instances/bee2/bts/point_light.vmf
File: instances/bee2/arrival_departure_transition_ents.vmf
File: instances/bee2/bts/point_light.vmf
File: instances/bee2/logic/bee/trigger_multiple.vmf
File: instances/bee2/logic/indicator_toggle.vmf
File: instances/bee2/bts/elevator_sp/exit_corridor_1.vmf
Setting exit to 1
File: instances/bee2/logic/indicator_toggle.vmf
Game Mode: SP
Is Preview: False
World.a3JumpIntroRotatingPanelArrive World.a3JumpIntroRotatingPanelArrive
Checking Conditions...
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
    exec(code, m.__dict__)
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 2782, in main
  File "F:\Git\BEE2.4\src\conditions.py", line 433, in check_all
  File "F:\Git\BEE2.4\src\conditions.py", line 297, in test
  File "F:\Git\BEE2.4\src\conditions.py", line 286, in test_result
  File "F:\Git\BEE2.4\src\conditions.py", line 344, in <lambda>
  File "F:\Git\BEE2.4\src\vbsp.py", line 676, in find_panel_locs
TypeError: argument of type 'NoneType' is not iterable

**Comment by ellingtonvengaboysmuseum** [comment]
@towergame 

are you using the death fizzler or grating in your map?

**Comment by towergame** [comment]
@ellingtonvengaboysmuseum 
I placed a death fizzler but then i removed it and replaced it with laser beams.

**Comment by towergame** [comment]
Laser beams also cause this problem.

**Comment by towergame** [comment]
This happens when publishing:

VVIS failed.

Valve Software - vvis.exe (Aug 26 2015)
4 threads
reading d:\steamgames\steamapps\common\portal 2\sdk_content\maps\1450375900.bsp
reading d:\steamgames\steamapps\common\portal 2\sdk_content\maps\1450375900.prt
LoadPortals: couldn't read d:\steamgames\steamapps\common\portal 2\sdk_content\maps\1450375900.prt
