### ISSUE TITLE
Pre-release 14 issues.

### ISSUE THREAD

**Issue by k0rny13** [BenVlodgi/BEE2.4#135]
Hello !

- Switching glass to gratings causes error while compiling.
- Switching Fizzler to Laser field causes error while compiling.
- Overgrown style still not working in coop map edition. (Yes I'm waiting it !! )

Thx a lot for your work, as usual.

Cya soon !

**Comment by LautaroL20** [comment]
These issues were completely fixed with the pre-release 16 :)
