### ISSUE TITLE
There was a problem loading the puzzle with blank chamber

### ISSUE THREAD

**Issue by Eleazar98** [BenVlodgi/BEE2.4#136]
I don't know what I've done with prerelease 14 that has done this, but if I so much as try to create a new blank chamber, I can't load it. Any help would be appreciated.

**Comment by TeamSpen210** [comment]
What style are you using? After the error message occurs, open the developer console and paste the contents here.

**Comment by Eleazar98** [comment]
http://i.imgur.com/9ROhczv.png <-- my settings

I don't know where the error message starts or ends so I'll paste all the console's contents from opening the game to after it failed to build the puzzle:

NET_GetBindAddresses found 192.168.1.8: 'Intel(R) Ethernet Connection (2) I218-V'
Opened Steam Socket NS_SERVER ( socket 2012 )
Opened Steam Socket NS_CLIENT ( socket 2292 )
Network: IP 192.168.1.8, mode MP, dedicated No, ports 27015 SV / 27005 CL
Parent cvar in client.dll not allowed (movement_anim_playback_minrate)
Game supporting (2) split screen players
maxplayers set to 1
Steam config directory: D:\Steam\steamapps\common\Portal 2\portal2.exe\platform\config
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
Hud element 'CHUDVSScorePanel' doesn't have an entry 'VSScorePanel' in scripts/HudLayout.res
Hud element 'CHUDPaintAmmo' doesn't have an entry 'PaintAmmo' in scripts/HudLayout.res
Hud element 'CHudSubtitles' doesn't have an entry 'HudSubtitles' in scripts/HudLayout.res
Hud element 'CHudSaveStatus' doesn't have an entry 'HudSaveStatus' in scripts/HudLayout.res
--- Missing Vgui material vgui/hud/commands/change_this
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
Hud element 'CHUDVSScorePanel' doesn't have an entry 'VSScorePanel' in scripts/HudLayout.res
Hud element 'CHUDPaintAmmo' doesn't have an entry 'PaintAmmo' in scripts/HudLayout.res
Hud element 'CHudSubtitles' doesn't have an entry 'HudSubtitles' in scripts/HudLayout.res
Hud element 'CHudSaveStatus' doesn't have an entry 'HudSaveStatus' in scripts/HudLayout.res
--- Missing Vgui material vgui/hud/commands/gesture_smallwave
resource/closecaption_dfd_English.txt not found
resource/closecaption_english.txt will be used
Unknown command "cl_thirdperson"
Unknown command "joy_no_accel_scale"
Didn't find Active Steam Controller to Load Menu Controls
resource/closecaption_dfd_English.txt not found
resource/closecaption_english.txt will be used
Unknown command "cl_thirdperson"
C_GameInstructor::ReadSaveData failed to read GI.lesson.Swap_Split_Screen_Control
[PORTAL2 PUZZLEMAKER]  New chamber!
Unknown command "cl_puzzlemaker_activate"
An error occurred while attempting to download a file from the UGC server!
CGameUIConVarRef mp_gamemode doesn't point to an existing ConVar
maxplayers set to 1
---- Host_NewGame ----
Network: IP 192.168.1.8, mode SP, dedicated No, ports 0 SV / 0 CL
Opened Steam Socket NS_SERVER ( socket 2696 )
Opened Steam Socket NS_CLIENT ( socket 2740 )
Network: IP 192.168.1.8, mode MP, dedicated No, ports 27015 SV / 27005 CL
Couldn't get HDR 'maps\newchamber/c-1904_2096_-48.hdr' -- Trying non HDR 'maps\newchamber/c-1904_2096_-48'
Failed, using default cubemap 'engine/defaultcubemap'
Couldn't get HDR 'maps\newchamber/c-2032_-2032_-31.hdr' -- Trying non HDR 'maps\newchamber/c-2032_-2032_-31'
Failed, using default cubemap 'engine/defaultcubemap'
Host_NewGame on map puzzlemaker\newchamber
exec: couldn't exec skill1.cfg
==== calling mapspawn.nut
Unable to load sprite material materials/sprites/gunsmoke.vmt!
Unable to load sprite material materials/sprites/bubble.vmt!
Attempted to create unknown entity type playtest_manager!
Can't init playtest_manager
Couldn't find any entities named doorentry0-player_start_teleport, which point_template @player_start_template is specifying.
Commentary: Could not find commentary data file 'maps/puzzlemaker\newchamber_commentary.txt'. 
1.000:  Sending UDP connect to public IP 127.0.0.1:27015
Server using '<none>' lobbies, requiring pw no, lobby id 0
RememberIPAddressForLobby: lobby 0 from address loopback
Can't find factory for entity: wearable_item
NULL Ent in UTIL_PrecacheOther
[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file materials/models/props_map_editor/door_frame.vmt
patch, (*insert*), 
KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file materials/models/props_map_editor/crusher_back.vmt
patch, (*insert*), 
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_autoportal_blue.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_autoportal_blue.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_autoportal_frame.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_autoportal_frame.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_portalgun1.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_portalgun1.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_portalgun2.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_portalgun2.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_portalgun3.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_portalgun3.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_ant_mag.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_ant_mag.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_ant_router.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_ant_router.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_checkpoint.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_checkpoint.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_checkpoint_sep.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_checkpoint_sep.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_ditch.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_ditch.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_a.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_a.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_b.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_b.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_chamberlock.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_chamberlock.3ds
KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file materials/models/props_map_editor/floor_panels.vmt
patch, (*insert*), 
[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------

==== calling mapspawn.nut
Connection to Steam servers successful.
   VAC secure mode is activated.
[PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198059474671\autosave.p2c
Parent cvar in client.dll not allowed (r_shadowlod)
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
Redownloading all lightmaps
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF D:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 27 (ms)

VBSP failed.

Adding metacondition ("remove_blank_inst") with priority 1000!
Adding metacondition ("fix_catapult_targets") with priority 0!
Adding metacondition ("res_find_potential_tag_fizzlers") with priority -110!
Adding metacondition ("find_indicator_panels") with priority -1000!
Adding metacondition ("add_voice") with priority 100!
Adding metacondition ("add_fizz_borders") with priority -250!
Adding metacondition ("fix_fizz_models") with priority -200!
Adding metacondition ("static_pan") with priority -100!
Adding metacondition ("find_panel_locs") with priority -1000!
Adding metacondition ("anti_fizz_bump") with priority 200!
Adding metacondition ("set_player_portalgun") with priority 500!
Adding metacondition ("add_screenshot_logic") with priority 750!
Adding metacondition ("set_elev_videos") with priority 50!
Adding metacondition ("ap_tag_modifications") with priority 200!
BEE2.4.0pr14 VBSP hook initiallised.
Map path is "D:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
New path: "D:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
PeTI map detected!
Loading settings...
Settings Loaded!
Parsing Map...
Parsing complete!
Forcing elevator spawn!
['instances/bee2/clean/elevator_sp/door_exit_1.vmf', 'instances/bee2/clean/elevator_sp/door_exit_2.vmf', 'instances/bee2/clean/elevator_sp/door_exit_3.vmf', 'instances/bee2/clean/elevator_sp/door_exit_4.vmf']
File: instances/bee2/clean/elevator_sp/elevator_exit.vmf
File: instances/bee2/arrival_departure_transition_ents.vmf
File: instances/bee2/clean/point_light.vmf
File: instances/bee2/clean/point_light.vmf
File: instances/bee2/clean/elevator_sp/door_exit_2.vmf
Setting exit to 1
File: instances/bee2/clean/point_light.vmf
File: instances/bee2/clean/elevator_sp/door_entrance_3.vmf
Setting entry to 1
File: instances/bee2/clean/elevator_sp/door_frame_black.vmf
File: instances/bee2/clean/elevator_sp/door_frame_black.vmf
File: instances/bee2/clean/elevator_sp/elevator_entrance.vmf
File: instances/bee2/clean/items/observation_room_256.vmf
File: instances/bee2/clean/point_light.vmf
Game Mode: SP
Is Preview: False
World.a3JumpIntroRotatingPanelArrive World.a3JumpIntroRotatingPanelArrive
Checking Conditions...
Exiting empty condition!
Exiting empty condition!
Starting catwalk generator...
Exiting empty condition!
Running Scaffold Generator (BEE2_SCAFFOLD)...
Finished Scaffold generation!
Exiting empty condition!
Exiting empty condition!
Exiting empty condition!
Elevator type:  RAND
Adding Voice Lines!
Config "bee2\voice.cfg" not found! Using defaults...
Config "bee2\mid_voice.cfg" not found! Using defaults...
Adding Base instance!
Generic True
Emancipation Grill False
Deadly False
Sentry Turret False
Discouragement Beam False
Conversion Gel False
Aerial Faith Plate False
Hard Light Bridge False
Propulsion Gel False
Mashy Spike Plate False
High Energy Pellets False
Reflection Gel False
Pneumatic Diversty Vent False
Paint Fizzler False
Sendificator False
Chosen: Property('line', [Property('name', 'Federal Regulations'), Property('id', 'GENERIC_1'), Property('trans', 'Federal regulations require me to warn you that this next test chamber... is looking pretty good.'), Property('choreo', 'scenes/npc/glados/a2_triple_laser01.vcd')])
Adding quote:  "Line"
	{
	"Name" "Federal Regulations"
	"ID" "GENERIC_1"
	"Trans" "Federal regulations require me to warn you that this next test chamber... is looking pretty good."
	"choreo" "scenes/npc/glados/a2_triple_laser01.vcd"
	}

Generic True
Deadly False
Aerial Faith Plate False
Repulsion Gel False
Propulsion Gel False
Chosen: Property('line_sp', [Property('name', 'Waddle Over To The Elevator'), Property('id', 'GENERIC_1'), Property('trans', "Waddle over to the elevator and we'll continue the testing."), Property('choreo', 'scenes/npc/glados/testchambermisc12.vcd')])
Property('line_sp', [Property('name', 'Mildly Impressive'), Property('id', 'GENERIC_2'), Property('trans', 'That was genuinely mildly impressive.'), Property('choreo', 'scenes/npc/glados/dlc1_leaderboard01.vcd')])
Property('line_sp', [Property('name', 'Statistically Speaking...'), Property('id', 'GENERIC_3'), Property('trans', 'You are playing above the global average. Statistically speaking, there are actually people playing worse than you.'), Property('choreo', 'scenes/npc/glados/dlc1_leaderboard20.vcd')])
Property('line_sp', [Property('name', 'Very Not Completely Bad'), Property('id', 'GENERIC_4'), Property('trans', 'Very not completely bad.'), Property('choreo', 'scenes/npc/glados/dlc1_leaderboard23.vcd')])
Property('line_sp', [Property('name', 'Maybe I Was Wrong'), Property('id', 'GENERIC_5'), Property('trans', '[impressed] Maybe I was wrong about you.'), Property('choreo', 'scenes/npc/glados/dlc1_leaderboard07.vcd')])
Property('line_sp', [Property('name', 'Impressive'), Property('trans', 'Impressive.'), Property('id', 'GENERIC_6'), Property('choreo', 'scenes/npc/glados/dlc1_leaderboard06.vcd')])
Property('line_sp', [Property('name', 'Congratulations'), Property('trans', 'Congratulations.'), Property('id', 'GENERIC_7'), Property('choreo', 'scenes/npc/glados/dlc1_leaderboard03.vcd')])
Adding quote:  "Line_SP"
	{
	"Name" "Mildly Impressive"
	"ID" "GENERIC_2"
	"Trans" "That was genuinely mildly impressive."
	"Choreo" "scenes/npc/glados/dlc1_leaderboard01.vcd"
	}

Mid quotes:  []
Done!
Setting Portalgun:
Blue: Y, Orange: Y
Done!
Added Screenshot Logic
Map has attributes:  ['spawn_dual']
Style Vars: {'bee_show_trigger': False, 'nomidvoices': False, 'fixportalbump': False, 'fixfizzlerbump': False, 'allowgoomist': True, 'multiversecave': True, 'unlockdefault': False, 'doorcameras': True}
Global instances:  {'instances/BEE2/clean/global_ents.vmf'}
Adding Music...
Adding Global PTI Ents
Editing Other Entities...
Editing Brushes...
Bottomless Pit: False
Editing Overlays...
Editing Triggers...
Collapsing goo triggers...
Done!
Editing Brush Entities...
Special tex: False False 0.15
Removing static indicator toggles...
Done!
Editing WorldSpawn
defaultdict(<class 'list'>, {'bee2/p1/metalwall048b_lrg_fade': ['PACK_P1_BLACK_WALL_LARGE_FADE'], 'bee2/bullseye/concrete_bts_floor002c_bts': ['PACK_BEE2_BULLSEYE_BTS_WHITE_FLOOR'], 'bee2/bts_grate': ['PACK_BTS_GRATING'], 'bee2/squarebeams_shiny': ['PACK_SQUAREBEAMS_SHINY'], 'bee2/70s/signage_shape_wavy': ['PACK_BEE2_70S_SHAPE_3'], 'bee2/70s/signage_shape_star': ['PACK_BEE2_70S_SHAPE_3'], 'bee2/bullseye/plasticwall003a_bts': ['PACK_BEE2_BULLSEYE_BTS_PLASTICWALL'], 'bee2/70s/signage_shape_sine': ['PACK_BEE2_70S_SHAPE_3'], 'bee2/bullseye/black_floor_metal': ['PACK_BEE2_BULLSEYE_CLEAN_BLACK_FLOORCEIL'], 'bee2/80s/signage_paint_jump': ['PACK_BEE2_80S_SIGN_PAINT_JUMP'], 'bee2/bullseye/factory_metal_floor001a': ['PACK_BEE2_BULLSEYE_BTS_FACTORYFLOOR'], 'bee2/ind_p1/corner_floor': ['PACK_P1_ANTLINES'], 'bee2/bullseye/under_metal_wall': ['PACK_BEE2_BULLSEYE_RETRO_50S_BLACK'], 'bee2/70s/signage_pellet': ['PACK_BEE2_70S_SIGN_PELLET'], 'bee2/bullseye/concrete_modular_wall': ['PACK_BEE2_BULLSEYE_P1_CONC_WALL'], 'bee2/p1/metalwall048b_med': ['PACK_P1_BLACK_WALL_MED'], 'bee2/p1/metalwall_bts_006a': ['PACK_P1_BTS_WALLS'], 'bee2/bullseye/factory_metal_floor001b': ['PACK_BEE2_BULLSEYE_BTS_FACTORYFLOOR'], 'bee2/bullseye/under_plywood': ['PACK_BEE2_BULLSEYE_RETRO_50S_BLACK'], 'bee2/bullseye/backpanels_yellow_bts': ['PACK_BEE2_BULLSEYE_BTS_BACKPANELS'], 'bee2/70s/signage_shape_slash': ['PACK_BEE2_70S_SHAPE_2'], 'bee2/70s/signage_overlay_energyball': ['PACK_BEE2_WORLD_SIGN_PELLET'], 'bee2/bullseye/under_plywood_bottom': ['PACK_BEE2_BULLSEYE_RETRO_70S_BLACK'], 'bee2/ind_p1/straight_wall': ['PACK_P1_ANTLINES'], 'bee2/bullseye/under_metal_ceil_80s': ['PACK_BEE2_BULLSEYE_RETRO_80S_BLACK'], 'bee2/bullseye/black_ceiling_metal': ['PACK_BEE2_BULLSEYE_CLEAN_BLACK_FLOORCEIL'], 'bee2/bullseye/under_conc_tile_80s': ['PACK_BEE2_BULLSEYE_RETRO_80S_BLACK'], 'bee2/p1/metalwall048b_lrg': ['PACK_P1_BLACK_WALL_LARGE'], 'bee2/p1/goo/p1_goo': ['PACK_P1_GOO'], 'bee2/70s/signage_shape_moon': ['PACK_BEE2_70S_SHAPE_2'], 'bee2/bullseye/under_wood_003d': ['PACKMaking Pack list...
scripts/vscripts/BEE2/video_splitter_rand.nut
Packlist written!
Generating VRAD config...
Saving New Map...
Complete!
Calling original VBSP...
"D:\Steam\steamapps\common\Portal 2\bin\vbsp_original" -game "D:/Steam/steamapps/common/Portal 2/portal2/" "D:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
VBSP failed! (1)

**Comment by AXEKING** [comment]
I have the same error, but when I restarted the whole editor, same error, I think its affecting the whole editor as a whole, because when I tried to use hammer for once in my life, it wouldn't let me play it. I used BTS, clean, 1950, and 1980. They all didn't work, I even used what the Portal 2 editor usually uses but still get the same error, I even switched back to BEE Alpha 2.2.5 and get the same error. I've sent the error to Valve, but haven't gotten a fix, and it usually doesn't take that long for the error to be fixed. 

I think the VBSP and VRAD are being very buggy because if I open VBSP with the files that are needed, then VRAD fails. But if I do the same thing to VRAD, VBSP fails. If I don't do it, both fail, and I can't do both, because the reaction time is at least less than 1 second.

I would prefer an auto-installer so that some of the big file errors that happen due to confusion and curiosity don't occur as much. Because I had to install it 15 times to figure out how to get into the BEE program, and screwed up anyways because I don't use things like pythons and that stuff. I only used an ico I believe twice. Possibly the most I can do is install a skin in TF2 (That is if its in a VPK). So I would prefer an auto-installer for the people who want things like death fizzlers and that stuff and don't know how to setup things like hammer and pythons, and just want into action. 


Is there a fix or is it gonna be fixed in pr15. Because auto-installers would help out with installation and wouldn't be as stressful and when things get too stressful, you get stressed. When you get stressed, it makes the task harder. When the task gets harder, you get stressed even more. 

Please fix this bug and add an auto-installer.

**Comment by Venima** [comment]
@AXEKING Right click Portal 2 in your steam library and go to properties. Go to Local Files and click Verify Integrity of Game Cache, and wait for it to finish. This won't help you use pr14 or 15, but Alpha 2.2.5 should start working again. Naturally you'll have to run the StyleChanger and export the palette in BEE's interface as you did before. I'm still waiting on an answer for the PRs. 

Also FYI, you shouldn't have made your own issue report when this one already exists. Yeah you know what I'm talking about: https://github.com/BenVlodgi/BEE2.4/issues/140. It just creates confusion.
