### ISSUE TITLE
Multiprocessing tries to flush stdout

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BenVlodgi/BEE2.4#137]
this comes up when i run bee2.4

![bee2 bug 1](https://cloud.githubusercontent.com/assets/11165643/11980997/d3b355f8-a96c-11e5-9c4c-664cbc0efd4a.jpg)

**Comment by jccreszMinecraft** [comment]
​I've already reported this.​

On Wed, Dec 23, 2015 at 12:01 PM, the great bee2 bug finder <
notifications@github.com> wrote:

> this comes up when i run bee2.4
>
> [image: bee2 bug 1]
> <https://cloud.githubusercontent.com/assets/11165643/11980997/d3b355f8-a96c-11e5-9c4c-664cbc0efd4a.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BenVlodgi/BEE2.4/issues/137>.
>



-- 
*-~=~-*
*Ice Network Entertainment Studios*
*-~=~-*

Chores in videogames are ridiculous!
