### ISSUE TITLE
Bee 2.4 Prl 15: Bugs

### ISSUE THREAD

**Issue by LautaroL20** [BenVlodgi/BEE2.4#138]
In-game editor bugs:

Impossible to build any chambers even without adding items, in both SP - Co-op modes. Ive tried this on all available Styles even on " use suggested" and using "BEEMod" default pallete:

![builderror](https://cloud.githubusercontent.com/assets/15699236/11982841/88f1b476-a98d-11e5-8c69-b301e4876889.jpg)

I really wished to test all the new added and old items but it was not possible.

---------------------------------------------------------------------------------------------

Bee2.4 tool bugs:

The "extracting resources" procces becomes stagnant forever due to a pyton manin script error, clicking on "accept" ennables the "export button" but It may be the cause of compilation failures of the chambers.

![the extracting resources procces becomes stagnant](https://cloud.githubusercontent.com/assets/15699236/11982821/602ac154-a98d-11e5-9d1d-8f2d7752409b.jpg)

------------------------------------------------------------------------------

Windows bugs on the tool:

![tool bug](https://cloud.githubusercontent.com/assets/15699236/11982868/d248b188-a98d-11e5-9013-fcefa9d77fd7.png)

--------------------------------------------------------------------------------------

Even clicking on these little icons to make them return to the view, it does not work:

![gif](https://cloud.githubusercontent.com/assets/15699236/11982895/0272317c-a98e-11e5-8c6a-2d7335d7cd67.gif)

-----------------------------------------------------------------------------------------------

Suggestion:

![suggestion for bee2 4](https://cloud.githubusercontent.com/assets/12244376/11983104/a3e3ec84-a98f-11e5-9e6e-01f1d899ed67.png)

**Comment by Enterpise** [comment]
Same bugs here.  

@TeamSpen210 was this Pre Release tested on a 100% Clean Portal 2 install before being uploaded to the page?

**Comment by Venima** [comment]
I also tried PR14 and that couldn't build maps either.

I saw Pillow under dependencies, do I have to install that myself? I'm a compile-ophobe and the Pillow's install method looks ghastly, so I avoided the notion.
