### ISSUE TITLE
Portal 2 can't make anything with BEE2.4 

### ISSUE THREAD

**Issue by AXEKING** [BenVlodgi/BEE2.4#140]
Portal 2 seems to have this error when I installed BEE2.4, this happened to me in Windows 8 and 10. No matter what style, option, pallete I use, it doesn't work. And in Windows 10, I got BEE 2 right when I installed portal 2, then the same error happened. I export the pallete, it successfully exports, it asks me if I want to launch portal 2, I said yes. Then I built the map, then error. I don't really know what is going on. It says the VBSP failed, like in a previous problem. In the windows 8, I used VBSP and VRAD didn't work, I did VRAD and then VBSP failed, and I can't do both.

Does anybody got a fix?

**Comment by Enterpise** [comment]
The first uploaded of the Prl 15 was the APOCALYPSE came true. But i think that the dev updated it.

**Comment by TeamSpen210** [comment]
What do you mean by 'used' VBSP and VRAD?

**Comment by AXEKING** [comment]
like, ran them. Like ran their pythons.

Even without doing that, it doesn't work.

**Comment by TeamSpen210** [comment]
Are you running from source? You need the executable versions of the compilers - they're run by Portal 2 during export. If you don't have those copied over, most items would end up broken (since a lot of instances get renamed to other ones by the compiler).

**Comment by AXEKING** [comment]
where would I paste that?

**Comment by TeamSpen210** [comment]
You want to download one of the [releases](https://github.com/BenVlodgi/BEE2.4/releases), extract that and use it. Alternately you could run the`src/compile_vrad_vbsp.py` script with an argument of 'build', which will generate the `compiler/` folder for you.

**Comment by AXEKING** [comment]
I believe I have pr15. I can't see where you are going with this, where is src/compile_vrad_vbsp.py

**Comment by AXEKING** [comment]
I see, but when I ran src/compile_vrad_vbsp.py, it didn't do anything really.

**Comment by TeamSpen210** [comment]
You should just use the release copy. Unzip that and run the BEE2.exe file in bin/, (once you've also copied the packages/ folder over).
For `compile_vrad_vbsp.py`, you must run it via the command line - `python compile_vrad_vbsp.py build`. It won't do anything without the extra argument. You then want to type in the version - `'2.4.0pr15'` that will be copied into it. (It doesn't affect anything, it's just printed in the console messages.)

**Comment by Venima** [comment]
I've been having the same problem, I'm not running from source, I'm using the downloads provided, and running BEE2.exe. I was using an old version, Bee2 alpha 2. That still works fine. I have it in the portal2_dlc2 folder. I'd like to know what my Portal 2 folder should look like after exporting the pallete using Bee2 PR15.1. 

To describe the problem better, when building an empty map in portal 2, it comes up with a build fail error at the end of building geometry.

**Comment by TeamSpen210** [comment]
For backing up puzzles, there's an option in File > backup/restore puzzles to perform backups (additionally via `bin/backup_tool.exe`). If you delete your local content you will lose your puzzles.

**Comment by seamuskills** [comment]
i have a vrad.error file in the bee2 files saying:
[ERROR] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "vrad.py", line 1002, in <module>
  File "vrad.py", line 920, in main
IndexError: list assignment index out of range

**Comment by Nikitasoskov** [comment]
how to fix Bee2 4.37.0 launch error?
