### ISSUE TITLE
More music and a online thing

### ISSUE THREAD

**Issue by AXEKING** [BenVlodgi/BEE2.4#142]
Music is music, plain and simple, but we need more options, like Portal stories: Mel and Portal 1.

<h1> I would like to show the developers of BEE, THE HONEYCOMB</h1>
A online place where
* You can hang out with other BEE users
* Announce upcoming maps (both admins and users)
*  Share mods, music, and other things for both portal games and BEE, and rate others.
* Give out tips and ideas
* Start a discussion the forums, do a fun little forum game, or something a little more serious
* Chat in the chatroom
* and A LOT MORE

I know, what about portal2backstock, but I feel like creating an entire new website while making the original still useful, would actually be very cool and interesting (and creating a new website with these features, might be less dangerous and less stressful than updating portal2backstock). I also seen that portal2backstock hasn't been updated in a long time (thinkingwithportals is now replaced by a virus website for some strange reason).

The icon is right here, you may improve or create a new one.  
![untitled](https://cloud.githubusercontent.com/assets/15697834/12008709/d6dfe922-ac1d-11e5-8880-ace75abd16ee.png)

**Comment by ellingtonvengaboysmuseum** [comment]
maybe, but a better name for it would be "The BeeHive - the Ben's Extended Editor and portal modding community"

things it would need to pull off would be 

- sharing of mods and their files and code
- announcement of portal 2 mods or a short map series (single maps only through the steam community)
- giving help and tips etc (for coding etc)
- and many more

and what ever it does or is, it should only be created on and run through and on GITHUB...

**Comment by Enterpise** [comment]
Yeah it could be a good idea but I think this must be maded under a Steam community group.

Respect to the maps it must be Bee2 maded only, but for this i think there is the "Portal 2 workshop" in where you can credit with #BEE2 on your map description.

**Comment by Venima** [comment]
Maintaining a website is a big hassle. Github makes maintenance easy. This is just speculation, but I think they've got enough on their plates. Unless there's an enthusiastic user willing to set this up?

**Comment by Enterpise** [comment]
LOL, It seems that the developers of the buggy Bee 2.4 are not interesting on "the honeycomb".

**Comment by BenVlodgi** [comment]
The intention is to instead release on steam and use the community tools there.

**Comment by Luke18033** [comment]
There's a [Steam group](https://steamcommunity.com/groups/beemod) and [Discord server](https://discord.me/beemod) for BEEmod now, which could be used for this sort of thing.
TWP was down for a while, but it's back up now on a new domain, [thinking.withportals.com](https://forums.thinking.withportals.com).

**Comment by Luke18033** [comment]
Note though that we could use GitHub pages if we really wanted to make this.
