### ISSUE TITLE
Better old style elements.

### ISSUE THREAD

**Issue by CrashingScience** [BenVlodgi/BEE2.4#144]
I really like the BEE2.4 and can't wait for it to be finished. One thing that bugs me is the old style test elements. I don't like the fact they are just brown, it doesn't look right. I was thinking of some alternatives:

Laser node: A large, old style, cylindrical light bulb protruding from the ground, maybe it could light up red when the laser passes through.

Excursion funnel: Four rotating copper coils to replace the rotating arms, and perhaps a large fan set in the middle to look like it pushes/pulls the player.

Light bridge: Perhaps just a grey metal box with a slot in the middle, with some black and yellow hazard stripes around the edge.

Turrets: Rather than just using defective, how about the ones seen in Aperture Tag and Portal Stories: Mel

Companion cube: An old style cube with a pink heart painted on the side.

Old sphere: Make it look similar to the cube, or possibly you could use a football.

I can see you have already done the laser and receiver in the editor,but I couldn't compile.
Please let me know what you think of my ideas, whether you agree or disagree with my suggestions.

**Comment by TeamSpen210** [comment]
Have you tried the BEE2.4? I've implemented various replacement versions of the Old Aperture items. For the laser catcher, it's exactly what you said.

**Comment by CrashingScience** [comment]
I have tried it but i couldnt compile any chambers at all. This was my second time installing the newest pre release and it had worked before but I hadnt tried old styles. Another thing I found was after deleting beemod the thumbnail gets stuck and Is the last compiled beemod chamber for all new chambers.

**Comment by CrashingScience** [comment]
I think i know why I couldnt compile, the prevoius bee files would have still been in my portal 2 folder and maybe conflicted with the current files bee was creating

**Comment by TeamSpen210** [comment]
That won't be the problem (at least for a compile error. The resources are actually saved in a different location entirely compared to the BEE1. Can you pastebin the contents of the developer console?

**Comment by CrashingScience** [comment]
Ill have to re intstall the mod and it might work again because i have just reinstalled portal 2 to get rid of the test chamber thumbnail bug i mentioned earlier. Maybe setting it to use the standard peti thumbnail, not custom will avoid this, ill have to test it out

**Comment by Venima** [comment]
@CrashingScience let me know if that works, cause then I'll do the same.

**Comment by CrashingScience** [comment]
Didn't work, heres my console report:

CrashingScience unpaused the game
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 53 (ms)

VBSP failed.

[I] vbsp: BEE2.4.0pr15 VBSP hook initiallised.
[I] vbsp: Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp: New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp: PeTI map detected!
[I] vbsp: Loading settings...
[I] vbsp: Settings Loaded!
[I] vbsp: Parsing Map...
[I] vbsp: Reading Map...
[I] vbsp: Loading complete!
[I] vbsp: Forcing elevator spawn!
[I] vbsp: Setting exit to 1
[I] vbsp: Setting entry to 1
[I] vbsp: Game Mode: SP
[I] vbsp: Is Preview: False
[I] conditions: Checking Conditions...
[I] conditions: Exiting empty condition!
[I] conditions: Exiting empty condition!
[I] conditions: Starting catwalk generator...
[I] conditions: Exiting empty condition!
[I] conditions: Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] conditions: Finished Scaffold generation!
[I] conditions: Exiting empty condition!
[I] conditions: Exiting empty condition!
[I] conditions: Exiting empty condition!
[I] conditions: Exiting empty condition!
[I] vbsp: Elevator type: NONE
[I] voiceLine: Adding Voice Lines!
[W] BEE2_config: Config "bee2\voice.cfg" not found! Using defaults...
[W] BEE2_config: Config "bee2\mid_voice.cfg" not found! Using defaults...
[I] voiceLine: Adding Base instance!
[I] voiceLine: Quote events: []
[I] voiceLine: Chosen: Property('Line_SP', [Property('Name', 'Welcome to Aperture Science'), Property('Trans', "Welcome, gentlemen, to Aperture Science. Astronauts, war heroes, Olympians--you're here because we want the best, and you are it. So: Who is ready to make some science?"), Property('Bullseye', 'cave_a3_03_lift_shaft'), Property('AmbientChoreo', [Property('Choreo', 'npc/cavejohnson/fifties_intro01.vcd'), Property('File', 'vo/cavejohnson/fifties_intro01.wav')])])
Property('Line_SP', [Property('Name', 'Shoulders of Giants'), Property('Trans', 'They say great science is built on the shoulders of giants. Not here. At Aperture, we do all our science from scratch. No hand holding.'), Property('Bullseye', 'cave_a3_03_exit'), Property('AmbientChoreo', [Property('Choreo', 'npc/cavejohnson/fifties_elevator_out_a01.vcd'), Property('File', 'vo/cavejohnson/fifties_elevator_out_a01.wav')])])
Property('Line_SP', [Property('Name', 'These Prerecorded Messages'), Property('Trans', "There's a thousand tests performed every day here in our enrichment spheres. I can't personally oversee every one of them, so these pre-recorded messages will cover any questions you might have, and respond to any incidents that may occur in the course of your science adventure."), Property('Bullseye', 'cave_a3_03_waiting_room'), Property('AmbientChoreo', [Property('Choreo', 'npc/cavejohnson/fifties_waiting01.vcd'), Property('File', 'vo/cavejohnson/fifties_waiting01.wav')])])
[I] voiceLine: Adding quote: "Line_SP"
	{
	"Name" "Welcome to Aperture Science"
	"Trans" "Welcome, gentlemen, to Aperture Science. Astronauts, war heroes, Olympians--you're here because we want the best, and you are it. So: Who is ready to make some science?"
	"Bullseye" "cave_a3_03_lift_shaft"
	"AmbientChoreo"
		{
		"Choreo" "npc/cavejohnson/fifties_intro01.vcd"
		"File" "vo/cavejohnson/fifties_intro01.wav"
		}
	}

[I] voiceLine: Chosen: Property('Line', [Property('Name', 'You Make Up Your Own Rules'), Property('Trans', 'Ha! I like your style. You make up your own rules, just like me.'), Property('Bullseye', 'cave_bomb_flings_chamber'), Property('AmbientChoreo', [Property('Choreo', 'npc/cavejohnson/fifties_into_middle_of_test01.vcd'), Property('File', 'vo/cavejohnson/fifties_into_middle_of_test01.wav')])])
Property('Line', [Property('Name', 'Glorious Contribution to Science'), Property('Trans', "Congratulations! The simple fact that you're standing here listening to me means you've made a glorious contribution to science."), Property('Trans', 'As founder and CEO of Aperture Science, I thank you for your participation and hope we can count on you for another round of tests.'), Property('Bullseye', 'cave_transition01_dummy_exit'), Property('File', '50s/exit_contrib.vmf')])
Property('Line', [Property('Name', 'Great Job, Astronaut!'), Property('Trans', "Great job, astronaut, war hero, and/or Olympian! With your help, we're gonna (tape sped up) change the world!"), Property('Bullseye', '@cave_exit_lift'), Property('AmbientChoreo', [Property('Choreo', 'npc/cavejohnson/seventies_test_a_complete06.vcd'), Property('File', 'vo/cavejohnson/seventies_test_a_complete06.wav')])])
Property('Line', [Property('Name', 'This Next Test Might Involve Time Travel'), Property('Trans', "Alright, this next test may involve trace amounts of time travel. So, word of advice: If you meet yourself on the testing track, don't make eye contact. Lab boys tell me that'll wipe out time. Entirely. Forward and backward! So do both of yourselves a favor and just let that handsome devil go about his business."), Property('Bullseye', 'cave_crazy_box_dummy_chamber'), Property('AmbientChoreo', [Property('Choreo', 'npc/cavejohnson/fifties_fourth_test_complete02.vcd'), Property('File', 'vo/cavejohnson/fifties_fourth_test_complete02.wav')])])
[I] voiceLine: Adding quote: "Line"
	{
	"Name" "Great Job, Astronaut!"
	"Trans" "Great job, astronaut, war hero, and/or Olympian! With your help, we're gonna (tape sped up) change the world!"
	"Bullseye" "@cave_exit_lift"
	"AmbientChoreo"
		{
		"Choreo" "npc/cavejohnson/seventies_test_a_complete06.vcd"
		"File" "vo/cavejohnson/seventies_test_a_complete06.wav"
		}
	}

[I] voiceLine: Mid quotes: []
[I] voiceLine: Done!
[I] vbsp: Setting Portalgun:
[I] vbsp: Blue: Y, Orange: Y
[I] vbsp: Done!
[I] conditions: Map has attributes: 
[I] conditions: Style Vars:
[I] conditions: Global instances: 
[I] vbsp: Adding Music...
[I] vbsp: Adding Global PTI Ents
[I] vbsp: Editing Other Entities...
[I] vbsp: Changing goo sides...
[I] vbsp: Done!
[I] vbsp: Editing Brushes...
[I] vbsp: Make Bottomless Pit: False
[I] vbsp: Clumping: 160 clumps
[I] vbsp: Editing Overlays...
[I] vbsp: Editing Triggers...
[I] vbsp: Collapsing goo triggers...
[I] vbsp: Done!
[I] vbsp: Editing Brush Entities...
[I] vbsp: Removing static indicator toggles...
[I] vbsp: Done!
[I] vbsp: Editing WorldSpawn
[I] vbsp: Making Pack list...
[I] vbsp: materials/BEE2/underground_woodwall003c.vmt
[I] vbsp: materials/BEE2/world/underground_hotsurface.vmt
[I] vbsp: Packlist written!
[I] vbsp: Generating VRAD config...
[I] vbsp: Saving New Map...
[I] vbsp: Complete!
Calling original VBSP...
"C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
Valve Software - vbsp.exe (Aug 26 2015)
4 threads
materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
Error! Variable "$envmap" is multiply defined in material "metal/underground_wall_metal004a_bottom"!
ConVarRef gpu_level doesn't point to an existing ConVar
fixing up env_cubemap materials on brush sides...
ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (0)
ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (0)
Processing areas...done (0)
Building Faces...done (0)
Chop Details...done (0)
Find Visible Detail Sides...
Merged 8 detail faces...SubdivideFace: didn't split the polygon
VBSP failed! (1)

**Comment by jccreszMinecraft** [comment]
All themes more or less fail to compile unless it's the "clean" theme.
Doesn't matter whether or not there's items.

On Thu, Dec 31, 2015 at 7:12 AM, CrashingScience <notifications@github.com>
wrote:

> Didn't work, heres my console report:
>
> CrashingScience unpaused the game
> [PORTAL2 PUZZLEMAKER] CVoxelTestChamber::Export VMF C:/Program Files
> (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
> [PORTAL2 PUZZLEMAKER] CVoxelTestChamber::Export VMF success, chamber size:
> (8,6,4)
> [PORTAL2 PUZZLEMAKER] Compilation time (after export): 53 (ms)
>
> VBSP failed.
>
> [I] vbsp: BEE2.4.0pr15 VBSP hook initiallised.
> [I] vbsp: Map path is "C:/Program Files
> (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
> [I] vbsp: New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal
> 2/sdk_content\maps\styled\preview.vmf"
> [I] vbsp: PeTI map detected!
> [I] vbsp: Loading settings...
> [I] vbsp: Settings Loaded!
> [I] vbsp: Parsing Map...
> [I] vbsp: Reading Map...
> [I] vbsp: Loading complete!
> [I] vbsp: Forcing elevator spawn!
> [I] vbsp: Setting exit to 1
> [I] vbsp: Setting entry to 1
> [I] vbsp: Game Mode: SP
> [I] vbsp: Is Preview: False
> [I] conditions: Checking Conditions...
> [I] conditions: Exiting empty condition!
> [I] conditions: Exiting empty condition!
> [I] conditions: Starting catwalk generator...
> [I] conditions: Exiting empty condition!
> [I] conditions: Running Scaffold Generator (BEE2_SCAFFOLD)...
> [I] conditions: Finished Scaffold generation!
> [I] conditions: Exiting empty condition!
> [I] conditions: Exiting empty condition!
> [I] conditions: Exiting empty condition!
> [I] conditions: Exiting empty condition!
> [I] vbsp: Elevator type: NONE
> [I] voiceLine: Adding Voice Lines!
> [W] BEE2_config: Config "bee2\voice.cfg" not found! Using defaults...
> [W] BEE2_config: Config "bee2\mid_voice.cfg" not found! Using defaults...
> [I] voiceLine: Adding Base instance!
> [I] voiceLine: Quote events: []
> [I] voiceLine: Chosen: Property('Line_SP', [Property('Name', 'Welcome to
> Aperture Science'), Property('Trans', "Welcome, gentlemen, to Aperture
> Science. Astronauts, war heroes, Olympians--you're here because we want the
> best, and you are it. So: Who is ready to make some science?"),
> Property('Bullseye', 'cave_a3_03_lift_shaft'), Property('AmbientChoreo',
> [Property('Choreo', 'npc/cavejohnson/fifties_intro01.vcd'),
> Property('File', 'vo/cavejohnson/fifties_intro01.wav')])])
> Property('Line_SP', [Property('Name', 'Shoulders of Giants'),
> Property('Trans', 'They say great science is built on the shoulders of
> giants. Not here. At Aperture, we do all our science from scratch. No hand
> holding.'), Property('Bullseye', 'cave_a3_03_exit'),
> Property('AmbientChoreo', [Property('Choreo',
> 'npc/cavejohnson/fifties_elevator_out_a01.vcd'), Property('File',
> 'vo/cavejohnson/fifties_elevator_out_a01.wav')])])
> Property('Line_SP', [Property('Name', 'These Prerecorded Messages'),
> Property('Trans', "There's a thousand tests performed every day here in our
> enrichment spheres. I can't personally oversee every one of them, so these
> pre-recorded messages will cover any questions you might have, and respond
> to any incidents that may occur in the course of your science adventure."),
> Property('Bullseye', 'cave_a3_03_waiting_room'), Property('AmbientChoreo',
> [Property('Choreo', 'npc/cavejohnson/fifties_waiting01.vcd'),
> Property('File', 'vo/cavejohnson/fifties_waiting01.wav')])])
> [I] voiceLine: Adding quote: "Line_SP"
> {
> "Name" "Welcome to Aperture Science"
> "Trans" "Welcome, gentlemen, to Aperture Science. Astronauts, war heroes,
> Olympians--you're here because we want the best, and you are it. So: Who is
> ready to make some science?"
> "Bullseye" "cave_a3_03_lift_shaft"
> "AmbientChoreo"
> {
> "Choreo" "npc/cavejohnson/fifties_intro01.vcd"
> "File" "vo/cavejohnson/fifties_intro01.wav"
> }
> }
>
> [I] voiceLine: Chosen: Property('Line', [Property('Name', 'You Make Up
> Your Own Rules'), Property('Trans', 'Ha! I like your style. You make up
> your own rules, just like me.'), Property('Bullseye',
> 'cave_bomb_flings_chamber'), Property('AmbientChoreo', [Property('Choreo',
> 'npc/cavejohnson/fifties_into_middle_of_test01.vcd'), Property('File',
> 'vo/cavejohnson/fifties_into_middle_of_test01.wav')])])
> Property('Line', [Property('Name', 'Glorious Contribution to Science'),
> Property('Trans', "Congratulations! The simple fact that you're standing
> here listening to me means you've made a glorious contribution to
> science."), Property('Trans', 'As founder and CEO of Aperture Science, I
> thank you for your participation and hope we can count on you for another
> round of tests.'), Property('Bullseye', 'cave_transition01_dummy_exit'),
> Property('File', '50s/exit_contrib.vmf')])
> Property('Line', [Property('Name', 'Great Job, Astronaut!'),
> Property('Trans', "Great job, astronaut, war hero, and/or Olympian! With
> your help, we're gonna (tape sped up) change the world!"),
> Property('Bullseye', '@cave_exit_lift'), Property('AmbientChoreo',
> [Property('Choreo', 'npc/cavejohnson/seventies_test_a_complete06.vcd'),
> Property('File', 'vo/cavejohnson/seventies_test_a_complete06.wav')])])
> Property('Line', [Property('Name', 'This Next Test Might Involve Time
> Travel'), Property('Trans', "Alright, this next test may involve trace
> amounts of time travel. So, word of advice: If you meet yourself on the
> testing track, don't make eye contact. Lab boys tell me that'll wipe out
> time. Entirely. Forward and backward! So do both of yourselves a favor and
> just let that handsome devil go about his business."), Property('Bullseye',
> 'cave_crazy_box_dummy_chamber'), Property('AmbientChoreo',
> [Property('Choreo', 'npc/cavejohnson/fifties_fourth_test_complete02.vcd'),
> Property('File', 'vo/cavejohnson/fifties_fourth_test_complete02.wav')])])
> [I] voiceLine: Adding quote: "Line"
> {
> "Name" "Great Job, Astronaut!"
> "Trans" "Great job, astronaut, war hero, and/or Olympian! With your help,
> we're gonna (tape sped up) change the world!"
> "Bullseye" "@cave_exit_lift"
> "AmbientChoreo"
> {
> "Choreo" "npc/cavejohnson/seventies_test_a_complete06.vcd"
> "File" "vo/cavejohnson/seventies_test_a_complete06.wav"
> }
> }
>
> [I] voiceLine: Mid quotes: []
> [I] voiceLine: Done!
> [I] vbsp: Setting Portalgun:
> [I] vbsp: Blue: Y, Orange: Y
> [I] vbsp: Done!
> [I] conditions: Map has attributes:
> [I] conditions: Style Vars:
> [I] conditions: Global instances:
> [I] vbsp: Adding Music...
> [I] vbsp: Adding Global PTI Ents
> [I] vbsp: Editing Other Entities...
> [I] vbsp: Changing goo sides...
> [I] vbsp: Done!
> [I] vbsp: Editing Brushes...
> [I] vbsp: Make Bottomless Pit: False
> [I] vbsp: Clumping: 160 clumps
> [I] vbsp: Editing Overlays...
> [I] vbsp: Editing Triggers...
> [I] vbsp: Collapsing goo triggers...
> [I] vbsp: Done!
> [I] vbsp: Editing Brush Entities...
> [I] vbsp: Removing static indicator toggles...
> [I] vbsp: Done!
> [I] vbsp: Editing WorldSpawn
> [I] vbsp: Making Pack list...
> [I] vbsp: materials/BEE2/underground_woodwall003c.vmt
> [I] vbsp: materials/BEE2/world/underground_hotsurface.vmt
> [I] vbsp: Packlist written!
> [I] vbsp: Generating VRAD config...
> [I] vbsp: Saving New Map...
> [I] vbsp: Complete!
> Calling original VBSP...
> "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original"
> -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/"
> "C:/Program Files (x86)/Steam/steamapps/common/Portal
> 2/sdk_content\maps\styled\preview.vmf"
> Valve Software - vbsp.exe (Aug 26 2015)
> 4 threads
> materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal
> 2\portal2\materials
> Loading C:/Program Files (x86)/Steam/steamapps/common/Portal
> 2/sdk_content\maps\styled\preview.vmf
> Error! Variable "$envmap" is multiply defined in material
> "metal/underground_wall_metal004a_bottom"!
> ConVarRef gpu_level doesn't point to an existing ConVar
> fixing up env_cubemap materials on brush sides...
> ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (0)
> ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (0)
> Processing areas...done (0)
> Building Faces...done (0)
> Chop Details...done (0)
> Find Visible Detail Sides...
> Merged 8 detail faces...SubdivideFace: didn't split the polygon
> VBSP failed! (1)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BenVlodgi/BEE2.4/issues/144#issuecomment-168184103>.
>



-- 
*-~=~-*
*Ice Network Entertainment Studios*
*-~=~-*

Chores in videogames are ridiculous!
