### ISSUE TITLE
I open BEE2.4 and this is what I got while it was trying to load packages:

### ISSUE THREAD

**Issue by BarbarianKabbage** [BenVlodgi/BEE2.4#146]
![2015-12-31 13_43_59-cx_freeze_ python error in main script](https://cloud.githubusercontent.com/assets/10360446/12069128/54602af0-afd5-11e5-9c6f-203dfb5e1840.png)

**Comment by TeamSpen210** [comment]
Check the palettes/ folder for non-zip files and remove them. It's tripping up when trying to read them as palettes.

**Comment by BarbarianKabbage** [comment]
The same thing happened I have another error box here:
![2015-12-31 15_58_20-tk_ bee2 exe - application error](https://cloud.githubusercontent.com/assets/10360446/12069176/5a87429a-afd7-11e5-9ecd-99a47f717cbe.png)

**Comment by LautaroL20** [comment]
This issue was fixed with the current pre-release 16.
