### ISSUE TITLE
Issue when compiling

### ISSUE THREAD

**Issue by Konclan** [BenVlodgi/BEE2.4#148]
When using version BEE2.4_pr15_win I get an error message when trying to compile my map in the puzzlemaker. I've tried a combination of pallets and settings but nothing seems to change it.

Here is my log when compiling
PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,5)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 69 (ms)

VBSP failed.

[I] vbsp: BEE2.4.0pr15 VBSP hook initiallised.
[I] vbsp: Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp: New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp: PeTI map detected!
[I] vbsp: Loading settings...
[I] vbsp: Settings Loaded!
[I] vbsp: Parsing Map...
[I] vbsp: Reading Map...
[I] vbsp: Loading complete!
[I] vbsp: Forcing elevator spawn!
[I] vbsp: Setting exit to 1
[I] vbsp: Setting entry to 1
[I] vbsp: Game Mode: SP
[I] vbsp: Is Preview: False
[I] conditions: Checking Conditions...
[I] conditions: Exiting empty condition!
[I] conditions: Exiting empty condition!
[I] conditions: Starting catwalk generator...
[I] conditions: Exiting empty condition!
[I] conditions: Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] conditions: Finished Scaffold generation!
[I] conditions: Exiting empty condition!
[I] conditions: Exiting empty condition!
[I] conditions: Exiting empty condition!
[I] vbsp: Elevator type: FORCE
[I] voiceLine: Adding Voice Lines!
[I] voiceLine: Adding Base instance!
[I] voiceLine: Quote events: []
[I] voiceLine: Chosen: Property('Line', [Property('Name', 'Federal Regulations'), Property('ID', 'GENERIC_1'), Property('Trans', 'Federal regulations require me to warn you that this next test chamber... is looking pretty good.'), Property('choreo', 'scenes/npc/glados/a2_triple_laser01.vcd')])
[I] voiceLine: Adding quote: "Line"
	{
	"Name" "Federal Regulations"
	"ID" "GENERIC_1"
	"Trans" "Federal regulations require me to warn you that this next test chamber... is looking pretty good."
	"choreo" "scenes/npc/glados/a2_triple_laser01.vcd"
	}

[I] voiceLine: Chosen: Property('Line_SP', [Property('Name', 'Waddle Over To The Elevator'), Property('ID', 'GENERIC_1'), Property('Trans', "Waddle over to the elevator and we'll continue the testing."), Property('Choreo', 'scenes/npc/glados/testchambermisc12.vcd')])
Property('Line_SP', [Property('Name', 'Mildly Impressive'), Property('ID', 'GENERIC_2'), Property('Trans', 'That was genuinely mildly impressive.'), Property('Choreo', 'scenes/npc/glados/dlc1_leaderboard01.vcd')])
Property('Line_SP', [Property('Name', 'Statistically Speaking...'), Property('ID', 'GENERIC_3'), Property('Trans', 'You are playing above the global average. Statistically speaking, there are actually people playing worse than you.'), Property('Choreo', 'scenes/npc/glados/dlc1_leaderboard20.vcd')])
Property('Line_SP', [Property('Name', 'Very Not Completely Bad'), Property('ID', 'GENERIC_4'), Property('Trans', 'Very not completely bad.'), Property('Choreo', 'scenes/npc/glados/dlc1_leaderboard23.vcd')])
Property('Line_SP', [Property('Name', 'Maybe I Was Wrong'), Property('ID', 'GENERIC_5'), Property('Trans', '[impressed] Maybe I was wrong about you.'), Property('Choreo', 'scenes/npc/glados/dlc1_leaderboard07.vcd')])
Property('Line_SP', [Property('Name', 'Impressive'), Property('Trans', 'Impressive.'), Property('ID', 'GENERIC_6'), Property('Choreo', 'scenes/npc/glados/dlc1_leaderboard06.vcd')])
Property('Line_SP', [Property('Name', 'Congratulations'), Property('Trans', 'Congratulations.'), Property('ID', 'GENERIC_7'), Property('Choreo', 'scenes/npc/glados/dlc1_leaderboard03.vcd')])
[I] voiceLine: Adding quote: "Line_SP"
	{
	"Name" "Mildly Impressive"
	"ID" "GENERIC_2"
	"Trans" "That was genuinely mildly impressive."
	"Choreo" "scenes/npc/glados/dlc1_leaderboard01.vcd"
	}

[I] voiceLine: Mid quotes: []
[I] voiceLine: Done!
[I] vbsp: Setting Portalgun:
[I] vbsp: Blue: Y, Orange: Y
[I] vbsp: Done!
[I] vbsp: Added Screenshot Logic
[I] conditions: Map has attributes: 
[I] conditions: Style Vars:
[I] conditions: Global instances: 
[I] vbsp: Adding Music...
[I] vbsp: Adding Global PTI Ents
[I] vbsp: Editing Other Entities...
[I] vbsp: Editing Brushes...
[I] vbsp: Make Bottomless Pit: False
[I] vbsp: Editing Overlays...
[I] vbsp: Editing Triggers...
[I] vbsp: Collapsing goo triggers...
[I] vbsp: Done!
[I] vbsp: Editing Brush Entities...
[I] vbsp: Removing static indicator toggles...
[I] vbsp: Done!
[I] vbsp: Editing WorldSpawn
[I] vbsp: Making Pack list...
[I] vbsp: scripts/vscripts/BEE2/video_splitter_specific.nut
[I] vbsp: Packlist written!
[I] vbsp: Generating VRAD config...
[I] vbsp: Saving New Map...
[I] vbsp: Complete!
Calling original VBSP...
"C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
Valve Software - vbsp.exe (Aug 26 2015)
2 threads
materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
ConVarRef gpu_level doesn't point to an existing ConVar
fixing up env_cubemap materials on brush sides...
ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (0)
ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (0)
Processing areas...done (0)
Building Faces...done (0)
Chop Details...done (0)
Find Visible Detail Sides...
Merged 474 detail faces...SubdivideFace: didn't split the polygon
VBSP failed! (1)

**Comment by Konclan** [comment]
it also seems like others have had this issue, but I can't find a solution

**Comment by Konclan** [comment]
Is it possible I need other mods for this in order for it to work properly?
Also does it matter that I installed bee1 mod?

**Comment by TeamSpen210** [comment]
I should have fixed this issue, I'm putting the release together right now.

**Comment by Konclan** [comment]
Awesome thank you
