### ISSUE TITLE
Bee2.4 PRL16: Bug List (Includes Screenshots).

### ISSUE THREAD

**Issue by LautaroL20** [BenVlodgi/BEE2.4#151]
Using the Shpere Button in Overgrown style causes error when trying to compile:

![2016-01-06_00012](https://cloud.githubusercontent.com/assets/12244376/12155381/8827087c-b4a3-11e5-9c03-6452d7759b46.jpg)

-------------------------------------------------------------------------------------------------------------------------

Cameras are literally "Dead" in the Entry and Exit SP Doors in Overgrown Style: 

![2016-01-06_00014](https://cloud.githubusercontent.com/assets/12244376/12155558/9027ad46-b4a4-11e5-8f04-caf22e9ac677.jpg)
![2016-01-06_00013](https://cloud.githubusercontent.com/assets/12244376/12155566/978caab4-b4a4-11e5-93dd-b664d59af9bf.jpg)

------------------------------------------------------------------------------------------------------
 
The Half Wall and its variations are completely vulnerable to portals shots:

![2016-01-06_00007](https://cloud.githubusercontent.com/assets/12244376/12155674/4ebf7586-b4a5-11e5-9844-ac371e9985cc.jpg)
![2016-01-06_00001](https://cloud.githubusercontent.com/assets/12244376/12156136/ee2a5b02-b4a7-11e5-8167-5b4a03abb0ce.jpg)
![2016-01-06_00015](https://cloud.githubusercontent.com/assets/12244376/12155697/6351b00e-b4a5-11e5-8a10-f16e3c1a5a05.jpg)

-----------------------------------------------------------------------------------------------------------------

Failure when trying to compile in Co-op mode only in: 50 & 60 Aperture Styles:

![builderror](https://cloud.githubusercontent.com/assets/12244376/12155848/3fdba340-b4a6-11e5-9ae6-c98cbf2e9323.jpg)

-------------------------------------------------------------------------------------------------

Wrong effect placement on the custom fizzlers on all the Old Aperture Styles:

![2016-01-06_00009](https://cloud.githubusercontent.com/assets/12244376/12156052/5a3eca22-b4a7-11e5-9943-933fb843470a.jpg)
![2016-01-06_00011](https://cloud.githubusercontent.com/assets/12244376/12156060/69e744d6-b4a7-11e5-8333-107cd56aa12a.jpg)

--------------------------------------------------------------------------------------------------------

Missing Skybox in the final of the exit door in Old aperture style:

![2016-01-06_00016](https://cloud.githubusercontent.com/assets/12244376/12156312/045cdb2e-b4a9-11e5-8c8f-d1b9217b08e4.jpg)

----------------------------------------------------------------------------------------------------------

Wrong placement of the stripes in the little windows:

![2016-01-06_00005](https://cloud.githubusercontent.com/assets/12244376/12156346/47809670-b4a9-11e5-84fa-4e3d0cbe1f12.jpg)

------------------------------------------------------------------------------------------------------------

Im not sure if this bug is fixeable but Doors and Lasers Relays got "Dark Orange" when shots with Reflection gel:

![2016-01-06_00002](https://cloud.githubusercontent.com/assets/12244376/12156434/bb720fa0-b4a9-11e5-8c15-c9228ab7e9ac.jpg)

---------------------------------------------------------------------------------------------------------

Two suggestions:

1. Reduce the Warm Light Brightness or add options to choose the bridghtness level through "Button Type"

![2016-01-06_00003](https://cloud.githubusercontent.com/assets/12244376/12156619/bdd88ac0-b4aa-11e5-9ce7-ec2166ea91fa.jpg)

2

![a3e3ec84-a98f-11e5-9e6e-01f1d899ed67](https://cloud.githubusercontent.com/assets/12244376/12156674/3196b59a-b4ab-11e5-8327-01b5a48e7fe8.png)

------------------------------------------------------------------------------------------------------------------

Small bug on the Bee interface tool: "compile options" and "pallete list" does not return to the view when clicking its icons:

![gif](https://cloud.githubusercontent.com/assets/12244376/12156720/7bd25b1e-b4ab-11e5-863d-66e092cb0f59.gif)

**Comment by TeamSpen210** [comment]
The overgrown cameras are supposed to be 'dead', they're off since GLaDOS is shutdown. The warm lightstrips actually have the same brightness as cool ones, it just looks brighter because of the contrast (Observation rooms produce cool lighting).

The reflection gel <> door interaction is a bug with reflection gel - it uses Propulsion Gel colouring, instead of its own. If you put propulsion or repulsion gel on relays and doors, they get correctly coloured and get their properties.

**Comment by LautaroL20** [comment]
I am migrating each bugs from this post into individual posts, in order to help developers to focus in each bug separately, and then it will be easier to close each issue.
