### ISSUE TITLE
Object Fizzler and Portal Fizzler

### ISSUE THREAD

**Issue by Konclan** [BenVlodgi/BEE2.4#152]
Could you add two fizzlers with unique colors. One fizzler would only destroy objects but your portals would remain, the other one would do the opposite. I feel like the normal fizzler is very limited in that way in the puzzle maker so a new fizzler with these interchangeable properties would be awesome!

**Comment by TeamSpen210** [comment]
'Matter Inquisition Fields' destroy objects but keep portals. 'Compressed Smoke Fields' block players but allow objects through. The one slight problem is that I can't control whether fizzlers block portal shots, but I can control what objects they fizzle and if they reset portals when you pass through.

**Comment by Konclan** [comment]
Oh ok, I didn't know. Thanks!
