### ISSUE TITLE
Bee2.exe not starting

### ISSUE THREAD

**Issue by spygineer** [BenVlodgi/BEE2.4#153]
When i try to start bee2.exe the windows explorer freezes and the program is not starting up.
I installed the packages to the right folder.

**Comment by LautaroL20** [comment]
Bee 2.5.5 Alpha and Bee 2.4 Does not work in older versions than Windows 7. Wich S.O are you using?

**Comment by spygineer** [comment]
I have Bee 2.4 pre-release 16 and i have win 7 proffesional x64

**Comment by spygineer** [comment]
Well it seems now working.Maybe i just needed to reboot.

**Comment by BenVlodgi** [comment]
Glad to hear its working now
