### ISSUE TITLE
Error with extracting archive with packages pr.16

### ISSUE THREAD

**Issue by MicroElf** [BenVlodgi/BEE2.4#154]
I've downloaded the new pr.16 version and can not unzip archive with packages
Screenshot: http://clip2net.com/s/3sF8HYF
Translation is something like 'an unknown method in' and all paths.

The application unzips with no problems. Also, have no problems on any previous versions with unzipping.

**Comment by LautaroL20** [comment]
WinRar does not work with packages of Pre-release 16. You should use 7-zip and youll have no problem with extracting.

**Comment by MicroElf** [comment]
Thanks. 7zip works fine
