### ISSUE TITLE
Game freeze down

### ISSUE THREAD

**Issue by spygineer** [BenVlodgi/BEE2.4#155]
When i hit "build" the whole game just freeze down,not doing anything.I chencked task manager vbsp is started,but not doing anything.

**Comment by TeamSpen210** [comment]
In your Portal 2 folder, navigate to `Portal 2/bin/bee2` and upload `vbsp.log` to pastebin. Alternatively, type `developer 2; clear` into the Portal 2 developer console, then compile, abort after a few seconds, and open the console again to get the log.

**Comment by spygineer** [comment]
Well problem is there is no vbsp.log and as i start build everything freeze down and i can't see any massenge in the console.

**Comment by TeamSpen210** [comment]
Quit the vbsp program via task manager, and see if that helps.

**Comment by spygineer** [comment]
Well i tried but it didn't helped and there is 3 vbsp.exe i can't close 2 of them,even with task maneger,

**Comment by BenVlodgi** [comment]
Restart your computer, those shouldn't be running

**Comment by spygineer** [comment]
Well now it seems to be working.I changed entrence and exit type and now working.
