### ISSUE TITLE
50s crushers inside out

### ISSUE THREAD

**Issue by CrashingScience** [BenVlodgi/BEE2.4#160]
Setting a 50s crusher to start enabled causes it to become inside out.

**Comment by TeamSpen210** [comment]
What do you mean by 'inside out'?

**Comment by CrashingScience** [comment]
![2016-01-11_00001](https://cloud.githubusercontent.com/assets/16468734/12241567/da4f0280-b88b-11e5-9b84-fca53c09bf7e.jpg)

**Comment by CrashingScience** [comment]
retracted

**Comment by CrashingScience** [comment]
![2016-01-11_00002](https://cloud.githubusercontent.com/assets/16468734/12241577/eb4446a4-b88b-11e5-9737-a1154af3a08e.jpg)

extended

**Comment by CrashingScience** [comment]
they can still kill, but you need to squeeze yourself up against the wall

**Comment by CrashingScience** [comment]
Also 60s flamethrowers dont work, and have no exitor texture

**Comment by CrashingScience** [comment]
Maybe the fist movement is set to retract instead of extend?

**Comment by TeamSpen210** [comment]
This appears fixed now.
