### ISSUE TITLE
Add Overgrown Paint Dropper

### ISSUE THREAD

**Issue by CrashingScience** [BenVlodgi/BEE2.4#162]
Some items with missing variants I have found

* [x] Old laser relay.
* [x] Old moving glass panels.
* [x] Old drawbridge.
* [x] Overgrown paint dropper.
* [x] Portal 1 Crusher.

Please keep the style of the overgrown paint dropper as a gel tube sticking out the wall when they are place sideways, I thought that was quite cool.

**Comment by TeamSpen210** [comment]
I will be keeping the appearance of the overgrown dropper, but I now have the ability to add more variation (different plants, stains, and using static props for better lighting).

**Comment by CrashingScience** [comment]
Cool idea.

Also no portal 1 crusher

**Comment by Konclan** [comment]
Didn't you add a P1 crusher? Perhaps this suggestion is done then
