### ISSUE TITLE
add option to have bee2 copy the bsp files for published test chambers

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BenVlodgi/BEE2.4#164]
i will be creating my own portal mod soon called "portal stories 2: past, present, and future" and i want to have the maps i use converted to bsp and have all the custom resources that are not in the original game packed into too...

add option to have bee2 copy the ready and packed bsp files for published test chambers to a folder when a map is published.

**Comment by BenVlodgi** [comment]
Mods should not have their resources packed into the BSPs, that causes inflation of the resources by the duplication of them.
Mods should also not be developed in the PTI, the PTI is for puzzle design, not mapping.

**Comment by PrestonAshton** [comment]
Yup, if you're doing a mod don't do it like this! I thought you would have experience with this considering you must have made Portal Stories 1. :laughing:
