### ISSUE TITLE
could Bee2 trigger Valve Anti Cheat

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BenVlodgi/BEE2.4#165]
@BenVlodgi @TeamSpen210 and @CarlKenner - 

just asking this just in case because if it should ever happen, it would be bad news for your mod

could Bee2 trigger Valve Anti Cheat and cause someone to get banned by a false flag

**Comment by xDadiKx** [comment]
Nope. It never happens.

**Comment by ellingtonvengaboysmuseum** [comment]
@xDadiKx it hasn't happened yet that is

**Comment by xDadiKx** [comment]
No. There was no reports about that.

**Comment by ellingtonvengaboysmuseum** [comment]
just found there is no VAC in portal 2 - case closed
