### ISSUE TITLE
How do I use the original style?

### ISSUE THREAD

**Issue by goodDOS** [BenVlodgi/BEE2.4#167]
How do I use the original style? Not clear style. Thank you :smile: -- Online translation

**Comment by jccreszMinecraft** [comment]
Just click style/theme, and click Clean. That will set it to compile with
clean textures.

On Tue, Jan 19, 2016 at 6:53 AM, 阿叶叶 <notifications@github.com> wrote:

> How do I use the original style? Not clear style Thank you [image:
> :smile:] -- Online translation
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BenVlodgi/BEE2.4/issues/167>.
>



-- 
*-~=~-*
*Ice Network Entertainment Studios*
*-~=~-*

Chores in videogames are ridiculous!

**Comment by goodDOS** [comment]
@jccreszMinecraft But clean style have BUG :sob: https://github.com/BenVlodgi/BEE2.4/issues/168
