### ISSUE TITLE
Missing player clip in Clean Coop Exit

### ISSUE THREAD

**Issue by goodDOS** [BenVlodgi/BEE2.4#169]
![Image of Yaktocat](http://i4.tietuku.com/f9c154f67db1bdfc.png)

**Comment by BenVlodgi** [comment]
could you clarify the problem?

**Comment by goodDOS** [comment]
@BenVlodgi The player can jump from the stairs

**Comment by goodDOS** [comment]
@BenVlodgi 
![img](http://i8.tietuku.com/7a4074c555cad158.png)

**Comment by BenVlodgi** [comment]
@goodDOS oh, gotcha, thanks
