### ISSUE TITLE
After repeat , the exit room can repeat  trigger glados voice .

### ISSUE THREAD

**Issue by goodDOS** [BenVlodgi/BEE2.4#171]
After repeat , the exit room can repeat  trigger glados voice .
![img](http://i8.tietuku.com/11a3f5342a323b16.png)

**Comment by LautaroL20** [comment]
Nice bug find.

**Comment by goodDOS** [comment]
Should be replaced with a once trigger :smile:

**Comment by jccreszMinecraft** [comment]
This bug is known by TeamSpen.
