### ISSUE TITLE
(wish) Can add coop glados voice?

### ISSUE THREAD

**Issue by goodDOS** [BenVlodgi/BEE2.4#172]
I have a little wish, can add coop glados voice?

**Comment by TeamSpen210** [comment]
What do you mean exactly? There are voice lines in Coop in addition to Singleplayer. In the next release I made GLaDOS and Wheatley respond when you die in coop now.

**Comment by goodDOS** [comment]
@TeamSpen210 Add the player's death, glados said: Ha ha ha ....

**Comment by TeamSpen210** [comment]
I've added this in PR 17, for Coop. (It wouldn't really work in singleplayer, since you'd only hear a few seconds before a map reload.)
