### ISSUE TITLE
Missing models: Coop Checkpoint And Separated Coop Checkpoint

### ISSUE THREAD

**Issue by goodDOS** [BenVlodgi/BEE2.4#176]
![img](http://m1.yea.im/5gB.png)

**Comment by TeamSpen210** [comment]
This isn't an error (the missing model is though). You need to have empty space on the other side of the doorway, to allow players to actually exit.

**Comment by goodDOS** [comment]
@TeamSpen210 thank you :)

**Comment by Enterpise** [comment]
Well, there are several "Missing models". Not only from co-op checkpoints.

**Comment by Konclan** [comment]
Should this issue be closed yet?
