### ISSUE TITLE
Bee2.4 PRL 17 BUG: Can't build any chambers

### ISSUE THREAD

**Issue by LautaroL20** [BenVlodgi/BEE2.4#178]
"There was an error building the puzzle"

No matters if i use any item or not in the map, i will always getting the same error:

![2016-02-02_00001](https://cloud.githubusercontent.com/assets/12244376/12750310/170a3e14-c995-11e5-9782-3faa9e7eaca0.jpg)

--------------------------------------------------------------------------------------------

HERE IS THE FULL BUG LOG:

] developer 2
Lautaro unpaused the game
[PORTAL2 PUZZLEMAKER]  Saved puzzle: E:/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198046602127\autosave.p2c
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF E:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 80 (ms)

VBSP succeeded.

[I] vbsp: BEE2.4.0pr16 VBSP hook initiallised.
[I] cond.core: Imported all conditions modules!
[I] vbsp: Map path is "E:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp: New path: "E:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp: PeTI map detected!
[I] vbsp: Loading settings...
[I] vbsp: Settings Loaded!
[I] vbsp: Parsing Map...
[I] vbsp: Reading Map...
[I] vbsp: Loading complete!
[I] vbsp: Forcing elevator spawn!
[I] vbsp: Setting exit to 1
[I] vbsp: Setting entry to 1
[I] vbsp: Game Mode: SP
[I] vbsp: Is Preview: False
[I] cond.core: Checking Conditions...
[I] cond.core: Exiting empty condition!
[I] cond.core: Exiting empty condition!
[I] cond.catwalks: Starting catwalk generator...
[I] cond.core: Exiting empty condition!
[I] cond.scaffold: Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold: Finished Scaffold generation!
[I] cond.core: Exiting empty condition!
[I] cond.core: Exiting empty condition!
[I] cond.core: Exiting empty condition!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[W] cond.core: "ResizeableTrigger" is not a valid condition result!
[I] vbsp: Elevator type: RAND
[I] voiceLine: Adding Voice Lines!
[W] BEE2_config: Config "bee2\voice.cfg" not found! Using defaults...
[W] BEE2_config: Config "bee2\mid_voice.cfg" not found! Using defaults...
[I] voiceLine: Adding Base instance!
[I] voiceLine: Quote events: []
[I] voiceLine: Chosen: Property('Line', [Property('Name', 'Federal Regulations'), Property('ID', 'GENERIC_1'), Property('Trans', 'Federal regulations require me to warn you that this next test chamber... is looking pretty good.'), Property('choreo', 'scenes/npc/glados/a2_triple_laser01.vcd')])
[I] voiceLine: Adding quote: "Line"
 | 	{
 | 	"Name" "Federal Regulations"
 | 	"ID" "GENERIC_1"
 | 	"Trans" "Federal regulations require me to warn you that this next test chamber... is looking pretty good."
 | 	"choreo" "scenes/npc/glados/a2_triple_laser01.vcd"
 | 	}
 |_

[I] voiceLine: Chosen: Property('Line_SP', [Property('Name', 'Waddle Over To The Elevator'), Property('ID', 'GENERIC_1'), Property('Trans', "Waddle over to the elevator and we'll continue the testing."), Property('Choreo', 'scenes/npc/glados/testchambermisc12.vcd')])
 | Property('Line_SP', [Property('Name', 'Mildly Impressive'), Property('ID', 'GENERIC_2'), Property('Trans', 'That was genuinely mildly impressive.'), Property('Choreo', 'scenes/npc/glados/dlc1_leaderboard01.vcd')])
 | Property('Line_SP', [Property('Name', 'Statistically Speaking...'), Property('ID', 'GENERIC_3'), Property('Trans', 'You are playing above the global average. Statistically speaking, there are actually people playing worse than you.'), Property('Choreo', 'scenes/npc/glados/dlc1_leaderboard20.vcd')])
 | Property('Line_SP', [Property('Name', 'Very Not Completely Bad'), Property('ID', 'GENERIC_4'), Property('Trans', 'Very not completely bad.'), Property('Choreo', 'scenes/npc/glados/dlc1_leaderboard23.vcd')])
 | Property('Line_SP', [Property('Name', 'Maybe I Was Wrong'), Property('ID', 'GENERIC_5'), Property('Trans', '[impressed] Maybe I was wrong about you.'), Property('Choreo', 'scenes/npc/glados/dlc1_leaderboard07.vcd')])
 | Property('Line_SP', [Property('Name', 'Impressive'), Property('Trans', 'Impressive.'), Property('ID', 'GENERIC_6'), Property('Choreo', 'scenes/npc/glados/dlc1_leaderboard06.vcd')])
 |_Property('Line_SP', [Property('Name', 'Congratulations'), Property('Trans', 'Congratulations.'), Property('ID', 'GENERIC_7'), Property('Choreo', 'scenes/npc/glados/dlc1_leaderboard03.vcd')])

[I] voiceLine: Adding quote: "Line_SP"
 | 	{
 | 	"Name" "Mildly Impressive"
 | 	"ID" "GENERIC_2"
 | 	"Trans" "That was genuinely mildly impressive."
 | 	"Choreo" "scenes/npc/glados/dlc1_leaderboard01.vcd"
 | 	}
 |_

[I] voiceLine: Mid quotes: []
[I] voiceLine: Done!
[I] vbsp: Setting Portalgun:
[I] vbsp: Blue: Y, Orange: Y
[I] vbsp: Done!
[I] vbsp: Added Screenshot Logic
[I] cond.core: Map has attributes: 
[I] cond.core: Style Vars:
[I] cond.core: Global instances: 
[I] vbsp: Adding Music...
[I] vbsp: Adding Global PTI Ents
[I] vbsp: Editing Other Entities...
[I] vbsp: Editing Brushes...
[I] vbsp: Make Bottomless Pit: False
[I] vbsp: Editing Overlays...
[I] vbsp: Editing Triggers...
[I] vbsp: Collapsing goo triggers...
[I] vbsp: Done!
[I] vbsp: Editing Brush Entities...
[I] vbsp: Removing static indicator toggles...
[I] vbsp: Done!
[I] vbsp: Editing WorldSpawn
[I] vbsp: Making Pack list...
[I] vbsp: "scripts/vscripts/BEE2/video_splitter_rand.nut"
[I] vbsp: Packlist written!
[I] vbsp: Generating VRAD config...
[I] vbsp: Saving New Map...
[I] vbsp: Complete!
Calling original VBSP...
"E:\Steam\steamapps\common\Portal 2\bin\vbsp_original" -game "E:/Steam/steamapps/common/Portal 2/portal2/" "E:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
Valve Software - vbsp.exe (Aug 26 2015)
4 threads
materialPath: E:\Steam\steamapps\common\Portal 2\portal2\materials
Loading E:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
ConVarRef gpu_level doesn't point to an existing ConVar
fixing up env_cubemap materials on brush sides...
ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (0)
**** leaked ****
Entity logic_relay (-2968.00 32.00 -32.00) leaked!

FindPortalSide: Couldn't find a good match for which brush to assign to a portal near (2048.0 2560.0 344.0)
Leaf 0 contents: 
Leaf 1 contents: CONTENTS_SOLID 
viscontents (node 0 contents ^ node 1 contents): CONTENTS_SOLID 
This means that none of the brushes in leaf 0 or 1 that touches the portal has CONTENTS_SOLID 
Check for a huge brush enclosing the coordinates above that has contents CONTENTS_SOLID 
Candidate brush IDs: 

FindPortalSide: Couldn't find a good match for which brush to assign to a portal near (1536.0 3072.0 344.0)
Leaf 0 contents: 
Leaf 1 contents: CONTENTS_SOLID 
viscontents (node 0 contents ^ node 1 contents): CONTENTS_SOLID 
This means that none of the brushes in leaf 0 or 1 that touches the portal has CONTENTS_SOLID 
Check for a huge brush enclosing the coordinates above that has contents CONTENTS_SOLID 
Candidate brush IDs: 

FindPortalSide: Couldn't find a good match for which brush to assign to a portal near (704.0 2048.0 -64.0)
Leaf 0 contents: CONTENTS_SOLID 
Leaf 1 contents: 
viscontents (node 0 contents ^ node 1 contents): CONTENTS_SOLID 
This means that none of the brushes in leaf 0 or 1 that touches the portal has CONTENTS_SOLID 
Check for a huge brush enclosing the coordinates above that has contents CONTENTS_SOLID 
Candidate brush IDs: 

FindPortalSide: Couldn't find a good match for which brush to assign to a portal near (320.0 2048.0 -64.0)
Leaf 0 contents: CONTENTS_SOLID 
Leaf 1 contents: 
viscontents (node 0 contents ^ node 1 contents): CONTENTS_SOLID 
This means that none of the brushes in leaf 0 or 1 that touches the portal has CONTENTS_SOLID 
Check for a huge brush enclosing the coordinates above that has contents CONTENTS_SOLID 
Candidate brush IDs: 

FindPortalSide: Couldn't find a good match for which brush to assign to a portal near (832.0 2048.0 -64.0)
Leaf 0 contents: CONTENTS_SOLID 
Leaf 1 contents: 
viscontents (node 0 contents ^ node 1 contents): CONTENTS_SOLID 
This means that none of the brushes in leaf 0 or 1 that touches the portal has CONTENTS_SOLID 
Check for a huge brush enclosing the coordinates above that has contents CONTENTS_SOLID 
Candidate brush IDs: 

FindPortalSide: Couldn't find a good match for which brush to assign to a portal near (960.0 2048.0 -64.0)
Leaf 0 contents: CONTENTS_SOLID 
Leaf 1 contents: 
viscontents (node 0 contents ^ node 1 contents): CONTENTS_SOLID 
This means that none of the brushes in leaf 0 or 1 that touches the portal has CONTENTS_SOLID 
Check for a huge brush enclosing the coordinates above that has contents CONTENTS_SOLID 
Candidate brush IDs: 

FindPortalSide: Couldn't find a good match for which brush to assign to a portal near (512.0 2048.0 -536.0)
Leaf 0 contents: CONTENTS_SOLID 
Leaf 1 contents: 
viscontents (node 0 contents ^ node 1 contents): CONTENTS_SOLID 
This means that none of the brushes in leaf 0 or 1 that touches the portal has CONTENTS_SOLID 
Check for a huge brush enclosing the coordinates above that has contents CONTENTS_SOLID 
Candidate brush IDs: 

FindPortalSide: Couldn't find a good match for which brush to assign to a portal near (704.0 2048.0 64.0)
Leaf 0 contents: CONTENTS_SOLID 
Leaf 1 contents: 
viscontents (node 0 contents ^ node 1 contents): CONTENTS_SOLID 
This means that none of the brushes in leaf 0 or 1 that touches the portal has CONTENTS_SOLID 
Check for a huge brush enclosing the coordinates above that has contents CONTENTS_SOLID 
Candidate brush IDs: 

*** Suppressing further FindPortalSide errors.... ***
Processing areas...done (0)
Building Faces...done (0)
Chop Details...done (0)
Find Visible Detail Sides...
Merged 474 detail faces...done (1)
Merging details...done (0)
FixTjuncs...
PruneNodes...
WriteBSP...
done (0)
Finding displacement neighbors...
Finding lightmap sample positions...
Displacement Alpha : 0...1...2...3...4...5...6...7...8...9...10
Building Physics collision data...
done (0) (455734 bytes)
Placing detail props : 0...1...2...3...4...5...6...7...8...9...10
Compacting texture/material tables...
Reduced 2427 texinfos to 556
Reduced 48 texdatas to 44 (1358 bytes to 1251)
Writing E:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.bsp

nummapplanes:     (  7644 / 65536 )
nummapbrushes:    (  1231 /  8192 )
nummapbrushsides: ( 10692 / 65536 )
num_map_overlays: (     2 /   512 )
nummodels:        (    40 /  1024 )
num_entities:     (   281 / 16384 )

4 seconds elapsed
CDynamicFunction: Loading library 'Kernel32.dll' (75BF0000)
CDynamicFunction: Lookup of 'TryEnterCriticalSection' in 'Kernel32.dll': 76FC2530
CDynamicFunction: Closing library 'Kernel32.dll' (75BF0000)
Done!
[I] vbsp: BEE2 VBSP hook finished!

[PORTAL2 PUZZLEMAKER]  Compilation time (after VBSP): 8281 (ms)

VVIS failed.

Valve Software - vvis.exe (Aug 26 2015)
4 threads
reading e:\steam\steamapps\common\portal 2\sdk_content\maps\preview.bsp
reading e:\steam\steamapps\common\portal 2\sdk_content\maps\preview.prt
LoadPortals: couldn't read e:\steam\steamapps\common\portal 2\sdk_content\maps\preview.prt

**Comment by harritron2k2** [comment]
loadportals error usually means that there is a leak in the map. Based on the stuff above, ask @TeamSpen210 if this means that one of the items/blocks is causing leaks

**Comment by LautaroL20** [comment]
Interesting, let me check if the problem are these blocks.

**Comment by LautaroL20** [comment]
No, I can confirm i get "failure to compile" by using any other item, or, even compiling without any item in the map. And Here is the Proof:
![2016-02-05_00001](https://cloud.githubusercontent.com/assets/12244376/12862158/8f509f4e-cc47-11e5-8fba-1c1740a99a16.jpg)

So, i congratulate everyone who was able to get this pre-release working, but in my case i must to say i will keep using Bee2 Alpha 2.2.5 for some time until @TeamSpen210 fix those leaks.

**Comment by LautaroL20** [comment]
Fixed with the Prl18.
