### ISSUE TITLE
Bee2 Pr17 Mac: Error when exporting

### ISSUE THREAD

**Issue by yinhanzhi** [BenVlodgi/BEE2.4#179]
![default](https://cloud.githubusercontent.com/assets/3956293/12804027/2f069ae4-cb2a-11e5-91b0-e82bc84d19f8.jpg)

[E] tk_tools: TKinter callback exception occurred:
 | Traceback (most recent call last):
 |   File "/Users/spencer/Documents/Git/BEE2.4/src/UI.py", line 764, in export_editoritems
 |   File "/Users/spencer/Documents/Git/BEE2.4/src/gameMan.py", line 433, in export
 |   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/shutil.py", line 229, in copy
 |     copyfile(src, dst, follow_symlinks=follow_symlinks)
 |   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/shutil.py", line 108, in copyfile
 |     with open(src, 'rb') as fsrc:
 | IsADirectoryError: [Errno 21] Is a directory: '../compiler/logs'
 |_

Any suggestions?

**Comment by TeamSpen210** [comment]
Check the `BEE2_mac/compiler/` folder for a `logs` subfolder, and delete it if it's there.

**Comment by goodDOS** [comment]
@yinhanzhi 朋友你好 :)

**Comment by yinhanzhi** [comment]
@TeamSpen210 Thanks! It work!
@goodDOS 您吃了吗？
