### ISSUE TITLE
Bee 2.4 Won't open anymore since Pre-release 18

### ISSUE THREAD

**Issue by MrKrunk** [BenVlodgi/BEE2.4#185]
The mod was recently patched, and now I can't even open the program. When loading objects, the program just closes entirely. I can't do anything with it.

**Comment by MrKrunk** [comment]
[INFO] packageLoader.load_packages(): Reading objects from "APERTURE_TAG_VOICE"...
[INFO] packageLoader.load_packages(): Reading objects from "VALVE_LASERS"...
[INFO] packageLoader.load_packages(): Reading objects from "BEE2_PORTAL_1"...
[INFO] packageLoader.load_packages(): Reading objects from "BEE_PELLETS"...
[INFO] packageLoader.load_packages(): Reading objects from "HMW_SENDIFICATOR"...
[INFO] packageLoader.load_packages(): Reading objects from "PACK_WOM_CONDUCTOR"...
[INFO] packageLoader.load_packages(): Reading objects from "BEE2_MUSIC"...
[INFO] packageLoader.load_packages(): Reading objects from "BEE2_ELEV_VIDEO"...
[INFO] packageLoader.load_packages(): Reading objects from "TAG_MUSIC"...
[INFO] packageLoader.load_packages(): Reading objects from "TSPEN_LOGIC"...
[INFO] packageLoader.load_packages(): Reading objects from "HMW_MOD"...
[INFO] packageLoader.load_packages(): Reading objects from "FR_FIZZ"...
[INFO] packageLoader.load_packages(): Reading objects from "BEE2_VOICE_LINE"...
[INFO] packageLoader.load_packages(): Reading objects from "VALVE_HAZARDS"...
[INFO] packageLoader.load_packages(): Reading objects from "BEE2_OLD_AP"...
[INFO] packageLoader.load_packages(): Reading objects from "VALVE_TEST_ELEM"...
[INFO] packageLoader.load_packages(): Reading objects from "VALVE_GEOMETRY"...
[INFO] packageLoader.load_packages(): Reading objects from "BEE2_UNST_SCAFFOLD"...
[INFO] packageLoader.load_packages(): Reading objects from "BEE2_DECRORATION"...
[INFO] packageLoader.load_packages(): Reading objects from "BEE2_BTS"...
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_HMW_SENDIFICATOR"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_TSPEN_SP_CHECKPOINT"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_LIGHT_PANEL_WARM"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_CATAPULT"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_BEE_LOGIC"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_PAINT_SPLAT_REFLECTION"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_BEE2_SCAFFOLD_WALL"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_TSPEN_LOGIC_DELAYER"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_TSPEN_FLIP_FLOP"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_CRUSHER"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_PORTAL_MAGNET"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_TSPEN_ANT_MAGNET"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_BARRIER"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_HIGH_ENERGY_PELLET_CATCHER"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_PAINT_SPLAT"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_LASER_RELAY_CENTER"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_BEE2_ANGLED_BLOCK"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_DRAW_BRIDGE"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_BEE2_PARTIAL_FLAT_BLOCK"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_PANEL_CLEAR"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_BEE2_CATWALK"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_BEE2_SCAFFOLD_PIST"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_LP_DEATH_FIZZLER"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_TRIGGERS"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_OBSERVATION_ROOM"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_SQUARE_LIGHT"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_TURRET"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_BEE2_ROCKET_TURRET"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_TSPEN_COOP_CHECKPOINT"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_FR_COMP_SMOKE_FIELD"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_TAG_GUN_ACTIVATOR"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_EXIT_DOOR"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_WOM_CONDUCTOR"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_COOP_EXIT_DOOR"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_PANEL_STAIRS"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_FR_FORCE_DEFLECTION_FIELD"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_SAVEPOINT"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_BEE2_QUART_WALL"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_AUTOPORTAL"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_BEE2_CUTOUT_TILE"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_BEE2_SMALL_WINDOW"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_VENT"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_TSPEN_LOGIC_INPUTS_SR"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_TSPEN_DITCH"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_FR_MATTER_INQUISITION_FIELD"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_LOGIC_GATE"!
[DEBUG] packageLoader.load_packages(): Loading Item "DOOR"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_TBEAM"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_SECONDARY_OBSERVATION_ROOM"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_COOP_ENTRY_DOOR"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_RAIL_PLATFORM"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_BUTTON_PEDESTAL"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_BEE2_PAINT_FIZZLER"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_GOO"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_BEE2_HALF_WALL"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_PANEL_ANGLED"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_HIGH_ENERGY_PELLET_EMITTER"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_BUTTON_FLOOR"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_LIGHT_BRIDGE"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_PISTON_PLATFORM"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_LASER_EMITTER_CENTER"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_BEE2_PORTALGUN"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_ENTRY_DOOR"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_LIGHT_PANEL"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_TSPEN_ANT_ROUTER"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_BEE2_SPECIAL_MARKER"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_128X64X64"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_BEE2_SCAFFOLD_SLOT"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_TSPEN_ANT_ROUTER_STRIP"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_TSPEN_COOP_CHECKPOINT_SEP"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_HIGH_ENERGY_PELLET_INF"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_BARRIER_HAZARD"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_CUBE"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_PANEL_FLIP"!
[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_LASER_CATCHER_CENTER"!
[DEBUG] packageLoader.load_packages(): Loading EditorSound "Under_Door_Close"!
[DEBUG] packageLoader.load_packages(): Loading EditorSound "Under_Ped_Button_Press"!
[DEBUG] packageLoader.load_packages(): Loading EditorSound "Collapse_Suction"!
[DEBUG] packageLoader.load_packages(): Loading EditorSound "Under_Floor_Button_Press"!
[DEBUG] packageLoader.load_packages(): Loading EditorSound "Under_Door_Open"!
[DEBUG] packageLoader.load_packages(): Loading EditorSound "Expand_Crusher"!
[DEBUG] packageLoader.load_packages(): Loading EditorSound "Collapse_Crusher"!
[DEBUG] packageLoader.load_packages(): Loading EditorSound "Under_Ped_Button_Release"!
[DEBUG] packageLoader.load_packages(): Loading EditorSound "Expand_Suction"!
[DEBUG] packageLoader.load_packages(): Loading EditorSound "Under_Floor_Button_Release"!
[DEBUG] packageLoader.load_packages(): Loading Music "VALVE_MUSIC_SPHERES_1"!
[DEBUG] packageLoader.load_packages(): Loading Music "VALVE_SPACE_PHASE"!
[DEBUG] packageLoader.load_packages(): Loading Music "TAG_ARRIVAL"!
[DEBUG] packageLoader.load_packages(): Loading Music "TAG_COMPLETE_THE_CIRCUIT"!
[DEBUG] packageLoader.load_packages(): Loading Music "TAG_MOVING_PARTS"!
[DEBUG] packageLoader.load_packages(): Loading Music "TAG_LIFE_TEST_CONDITIONS"!
[DEBUG] packageLoader.load_packages(): Loading Music "VALVE_ROBO_ROOM_5"!
[DEBUG] packageLoader.load_packages(): Loading Music "TAG_PRECIOUS_TEST"!
[DEBUG] packageLoader.load_packages(): Loading Music "TAG_SYSTEM_LEAK"!
[DEBUG] packageLoader.load_packages(): Loading Music "TAG_GLITCH"!
[DEBUG] packageLoader.load_packages(): Loading Music "VALVE_ROBO_GHOST"!
[DEBUG] packageLoader.load_packages(): Loading Music "TAG_CONFRONTATION"!
[DEBUG] packageLoader.load_packages(): Loading Music "VALVE_CONTROL_GROUP"!
[DEBUG] packageLoader.load_packages(): Loading Music "TAG_CERTIFIABLY_INSANE"!
[DEBUG] packageLoader.load_packages(): Loading Music "VALVE_REDEMPTION"!
[DEBUG] packageLoader.load_packages(): Loading Music "TAG_GET_TO_IT"!
[DEBUG] packageLoader.load_packages(): Loading Music "TAG_RECONSTRUCTING_AMBIENCE"!
[DEBUG] packageLoader.load_packages(): Loading Music "VALVE_TECHNICAL_DIFFICULTIES"!
[DEBUG] packageLoader.load_packages(): Loading Music "VALVE_REUNION"!
[DEBUG] packageLoader.load_packages(): Loading Music "VALVE_MUSIC_SPHERES_2"!
[DEBUG] packageLoader.load_packages(): Loading Music "VALVE_ROBO_ROOM_1"!
[DEBUG] packageLoader.load_packages(): Loading Music "TAG_CONCERNED"!
[DEBUG] packageLoader.load_packages(): Loading Music "TAG_DEAD_SUBJECT"!
[DEBUG] packageLoader.load_packages(): Loading Music "TAG_STERILISED_ENVIRONS"!
[DEBUG] packageLoader.load_packages(): Loading Music "TAG_LIFE_TOO_SHORT"!
[DEBUG] packageLoader.load_packages(): Loading Music "VALVE_TBEAM_INTRO"!
[DEBUG] packageLoader.load_packages(): Loading Music "VALVE_ROBO_ROOM_3"!
[DEBUG] packageLoader.load_packages(): Loading Music "VALVE_ROBO_ROOM_2"!
[DEBUG] packageLoader.load_packages(): Loading Music "TAG_RESONANCE"!
[DEBUG] packageLoader.load_packages(): Loading Music "VALVE_LASER_DANCE"!
[DEBUG] packageLoader.load_packages(): Loading Music "TAG_BOOTS"!
[DEBUG] packageLoader.load_packages(): Loading Music "TAG_TAKE_IT_SLOW"!
[DEBUG] packageLoader.load_packages(): Loading Music "VALVE_DAUGHTER_WORK"!
[DEBUG] packageLoader.load_packages(): Loading Music "VALVE_LOVE_CONSTRUCT"!
[DEBUG] packageLoader.load_packages(): Loading Music "VALVE_PETI"!
[DEBUG] packageLoader.load_packages(): Loading Music "TAG_TIME_ESSENCE"!
[DEBUG] packageLoader.load_packages(): Loading Music "VALVE_NINES_1"!
[DEBUG] packageLoader.load_packages(): Loading Music "TAG_TRIALS"!
[DEBUG] packageLoader.load_packages(): Loading Music "TAG_RIDE_IT_OUT"!
[DEBUG] packageLoader.load_packages(): Loading Music "VALVE_50_PERC"!
[DEBUG] packageLoader.load_packages(): Loading Music "VALVE_NINES_2"!
[DEBUG] packageLoader.load_packages(): Loading Music "TAG_SLOW_2"!
[DEBUG] packageLoader.load_packages(): Loading Music "VALVE_SAW_DEER"!
[DEBUG] packageLoader.load_packages(): Loading Music "VALVE_ACCENT_BEYOND"!
[DEBUG] packageLoader.load_packages(): Loading Music "VALVE_VIT_ORDER_1"!
[DEBUG] packageLoader.load_packages(): Loading Music "VALVE_IM_DIFFERENT"!
[DEBUG] packageLoader.load_packages(): Loading Music "VALVE_ROBO_ROOM_PTI"!
[DEBUG] packageLoader.load_packages(): Loading Music "VALVE_FRANKENTURRETS"!
[DEBUG] packageLoader.load_packages(): Loading Music "VALVE_COMEDY=TRAGEDY"!
[DEBUG] packageLoader.load_packages(): Loading Music "VALVE_ROBO_ROOM_6"!
[DEBUG] packageLoader.load_packages(): Loading Music "VALVE_FUTURE_STARTER"!
[DEBUG] packageLoader.load_packages(): Loading Music "VALVE_RATTMAN"!
[DEBUG] packageLoader.load_packages(): Loading Music "TAG_PULL_YOURSELF_TOGETHER"!
[DEBUG] packageLoader.load_packages(): Loading Music "TAG_ART_THERAPY"!
[DEBUG] packageLoader.load_packages(): Loading Music "TAG_BUILD_UP_TO_NOWHERE"!
[DEBUG] packageLoader.load_packages(): Loading Music "VALVE_CAUSE_SCIENCE"!
[DEBUG] packageLoader.load_packages(): Loading Music "VALVE_ROBO_ROOM_4"!
[DEBUG] packageLoader.load_packages(): Loading Music "VALVE_WHAT_HAS_HE_DONE"!
[DEBUG] packageLoader.load_packages(): Loading Music "VALVE_50_PERC_FAST"!
[DEBUG] packageLoader.load_packages(): Loading Music "VALVE_VIT_ORDER_2"!
[DEBUG] packageLoader.load_packages(): Loading Music "VALVE_CLASSICAL"!
[DEBUG] packageLoader.load_packages(): Loading Music "TAG_SURE"!
[DEBUG] packageLoader.load_packages(): Loading Music "TAG_LIFE_SUPPORT"!
[DEBUG] packageLoader.load_packages(): Loading Elevator "VALVE_RADAR_UNUSED"!
[DEBUG] packageLoader.load_packages(): Loading Elevator "VALVE_FAITH_PLATE"!
[DEBUG] packageLoader.load_packages(): Loading Elevator "VALVE_ATLAS_LOAD"!
[DEBUG] packageLoader.load_packages(): Loading Elevator "VALVE_RADAR_FOUND"!
[DEBUG] packageLoader.load_packages(): Loading Elevator "VALVE_MENU_ACT_3"!
[DEBUG] packageLoader.load_packages(): Loading Elevator "VALVE_APERTURE_LOGO"!
[DEBUG] packageLoader.load_packages(): Loading Elevator "VALVE_MENU_ACT_5"!
[DEBUG] packageLoader.load_packages(): Loading Elevator "VALVE_LOAD_PBODY"!
[DEBUG] packageLoader.load_packages(): Loading Elevator "VALVE_MENU_ACT_2"!
[DEBUG] packageLoader.load_packages(): Loading Elevator "VALVE_SECURITY_SEARCHING"!
[DEBUG] packageLoader.load_packages(): Loading Elevator "VALVE_MENU_ACT_1"!
[DEBUG] packageLoader.load_packages(): Loading Elevator "VALVE_SPACE"!
[DEBUG] packageLoader.load_packages(): Loading Elevator "VALVE_ANIMAL_KING"!
[DEBUG] packageLoader.load_packages(): Loading Elevator "VALVE_BOTS_WAVE"!
[DEBUG] packageLoader.load_packages(): Loading Elevator "VALVE_BLUEPRINTS"!
[DEBUG] packageLoader.load_packages(): Loading Elevator "VALVE_INSERT_DISC"!
[DEBUG] packageLoader.load_packages(): Loading Elevator "VALVE_TURRET_DROPIN"!
[DEBUG] packageLoader.load_packages(): Loading Elevator "VALVE_LASER_PORTAL"!
[DEBUG] packageLoader.load_packages(): Loading Elevator "VALVE_BOTS_LOAD"!
[DEBUG] packageLoader.load_packages(): Loading Elevator "VALVE_FIZZLER"!
[DEBUG] packageLoader.load_packages(): Loading Elevator "VALVE_TURRET_CASE_OPTIONS"!
[DEBUG] packageLoader.load_packages(): Loading Elevator "VALVE_TURRET_EXPLODED"!
[DEBUG] packageLoader.load_packages(): Loading Elevator "VALVE_MENU_ACT_4"!
[DEBUG] packageLoader.load_packages(): Loading Elevator "VALVE_BLUESCREEN"!
[DEBUG] packageLoader.load_packages(): Loading Elevator "VALVE_APERTURE_APPEAR"!
[DEBUG] packageLoader.load_packages(): Loading Elevator "VALVE_POWER_CONNECTED"!
[DEBUG] packageLoader.load_packages(): Loading Elevator "VALVE_EVAC_TRAINING"!
[DEBUG] packageLoader.load_packages(): Loading Elevator "VALVE_LASER_DANGER"!
[DEBUG] packageLoader.load_packages(): Loading Elevator "VALVE_LIGHTBRIDGE"!
[DEBUG] packageLoader.load_packages(): Loading Elevator "VALVE_POWER_CONNECTING"!
[DEBUG] packageLoader.load_packages(): Loading Elevator "VALVE_SECURITY_DOWNLOADING"!
[DEBUG] packageLoader.load_packages(): Loading Elevator "VALVE_REMAIN_CALM"!
[DEBUG] packageLoader.load_packages(): Loading Elevator "VALVE_RADAR_CALIBRATING"!
[DEBUG] packageLoader.load_packages(): Loading Elevator "VALVE_BLACK"!
[DEBUG] packageLoader.load_packages(): Loading Elevator "VALVE_CREDITS_BG"!
[DEBUG] packageLoader.load_packages(): Loading StyleVar "P1_WPORTAL_STRIPS"!
[DEBUG] packageLoader.load_packages(): Loading StyleVar "BEE_SHOW_TRIGGER"!
[DEBUG] packageLoader.load_packages(): Loading StyleVar "P1_PORTED_PGUN"!
[DEBUG] packageLoader.load_packages(): Loading StyleVar "DoorCameras"!
[DEBUG] packageLoader.load_packages(): Loading StyleVar "OpenSphere"!
[DEBUG] packageLoader.load_packages(): Loading StyleVPK "VPK_BEE2_1950S"!

**Comment by MrKrunk** [comment]
At the very bottom of the log, it clearly does not say "done extracting" or anything.

**Comment by LautaroL20** [comment]
Im having the same problem.

**Comment by Enterpise** [comment]
I can't open Bee 2.4 too. I think this program should be called "Bug Simulator 2016".

**Comment by TeamSpen210** [comment]
Redownload, it should be fixed now.
