### ISSUE TITLE
Bee 2.4 Pre-release 18 Portal Style Entrance Leak

### ISSUE THREAD

**Issue by MrKrunk** [BenVlodgi/BEE2.4#186]
![preview0001](https://cloud.githubusercontent.com/assets/17092818/12907180/4948041c-ce9d-11e5-9c95-9d01b1cde322.jpg)
Look under the test chamber entrance. You guys know what to do.

**Comment by BenVlodgi** [comment]
Technically its not a leak, its visible nodraw

**Comment by TeamSpen210** [comment]
Fixed by 5ef4796a186b7f0a055020433d5d3359d87a1bc0.
