### ISSUE TITLE
Bee 2.4 Pre-release 18 Portal Button Error 

### ISSUE THREAD

**Issue by MrKrunk** [BenVlodgi/BEE2.4#187]
![preview0004](https://cloud.githubusercontent.com/assets/17092818/12907573/c9cca6c0-cea1-11e5-98a2-7061b822952c.jpg)
The plate on the Portal 1 Style button is an error.

**Comment by LautaroL20** [comment]
I think you should post everything related to items on this page:

https://github.com/TeamSpen210/BEE2-items/issues

And everything related to BEE2.exe Interface, should be in this page, where you are posting right now.

**Comment by TeamSpen210** [comment]
This is fixed by TeamSpen210/BEE2-items@4a2b0557f162d656862550eefb774e1036c508f5.
