### ISSUE TITLE
Generated instances

### ISSUE THREAD

**Issue by BenVlodgi** [BenVlodgi/BEE2.4#188]
In relation to the generated instances:
Are all of these generated instances in the  _BEE2/logic_ folder?
Are these instances persistent? Do they stick around?
How does this affect exported maps?
Do exported maps get temporary instance markers which are then replaced during compilation?

**Comment by TeamSpen210** [comment]
The stuff that's generated isn't instance files - it's saved directly into the main map. Basically a lot of items have instances defined in editoritems that don't exist. It's different for each item, but they'll either remame the instance to one that exists or delete it after insterting other things. 

There's a 'templating' system that copies a set of brushes into the map, retexturing them based on the orientation and style. There's a template for button bases, for example, to make them use floor/wall/ceiling textures, as well as match black/white with 1 file to reduce duplication.

**Comment by BenVlodgi** [comment]
So the filename of the instance is actually just a flag that the compiler recognizes and replaces?

**Comment by TeamSpen210** [comment]
Pretty much. Here's the [config](https://github.com/TeamSpen210/BEE2-items/blob/master/packages/valve/buttons/items/floor/vbsp_config.cfg) for floor buttons. The angle brackets lookup filenames from editoritems.

**Comment by BenVlodgi** [comment]
Okay, so with these conditions, anything matching the **instance** gets replaced with the **ChangeInstance** and brush? so in the item definition you just put that flag like `<ITEM_BUTTON_FLOOR>` in place of a file name?

**Comment by TeamSpen210** [comment]
Yes. This is used pretty heavily everywhere. There's lots of flags for detecting various things (instance $replace variables, orientation, SP/Coop, etc) and lots of tranformations that can be applied. That's in the `conditions` Python package. The `instancelocs` module parses the <> values.
