### ISSUE TITLE
Suggestion: Ennable ability folder´s url paste for the "Find Game Exe" Window.

### ISSUE THREAD

**Issue by LautaroL20** [BenVlodgi/BEE2.4#189]
This could save a bit of time if it had the ability to directly paste the Url "Portal 2" folder instead of having to search "Folder per folder"

-----------------------------------------------------------------------------------

![3196b59a-b4ab-11e5-8327-01b5a48e7fe8](https://cloud.githubusercontent.com/assets/12244376/12933408/a875d7b0-cf66-11e5-8195-357b7906bbce.png)

**Comment by Enterpise** [comment]
Hey, this would be practical if they implement it.

**Comment by BenVlodgi** [comment]
You can paste the path in the lower texbox and click **Open** and it will go to that folder

**Comment by LautaroL20** [comment]
It may result a bit confusing for some users though.

**Comment by TeamSpen210** [comment]
This is the standard Windows file opening box, I don't really have any control over how it functions. You can paste directory paths into it, so you might need to remove the '/portal2.exe' from the end.
