### ISSUE TITLE
Pr18 bugs

### ISSUE THREAD

**Issue by goodDOS** [BenVlodgi/BEE2.4#190]
## 1.1950 style
![img](http://i12.tietuku.com/051a278f35a8ebfd.png)
Exit Door error.

## 2.1960 style
![img](http://i12.tietuku.com/82a20dcdfe182033.png)
As long as there is a player out of the exit room, the door will close.

## 3.1970 style
![img](http://i12.tietuku.com/7d7df9abbabcbff1.png)
?!?!

![img](http://i12.tietuku.com/3351943a4e9bcadb.png)
Light reflection have bug.

![img](http://i12.tietuku.com/924d0de7ea49bd9f.png)
Exit Door missing textures.

## 4.1980 style
![img](http://i12.tietuku.com/b9fd8f6f8a437eb4.png)
?!?!

![img](http://i12.tietuku.com/503170e3310f76b1.png)
Sky box can't show.

![img](http://i12.tietuku.com/6b4130af808d0f4a.png)
Exit Door missing textures.

## 5.BTS style
![img](http://i12.tietuku.com/b61811557c8f4fb0.png)
Exit room missing clip.

## 6.Overgrown style
Using a overgrown model of cooperation result in a compile error.

## 7.:laughing:

**Comment by LautaroL20** [comment]
Ive reported some of these bugs, but i see there are few others i didnt notice, nice find!

**Comment by goodDOS** [comment]
@LautaroL20 Thanks! :laughing:

**Comment by BenVlodgi** [comment]
Some of those look like too many portals are open in the game at once
