### ISSUE TITLE
Logical XOR Gate invalid

### ISSUE THREAD

**Issue by goodDOS** [BenVlodgi/BEE2.4#191]
![img](http://i11.tietuku.com/0d457ae1a5f7ae46.png)
Logical XOR Gate invalid.

Will you be able to quickly fix this bug? I am anxious to use.
Thanks :smiley:

**Comment by goodDOS** [comment]
![img](http://i13.tietuku.com/667c7161498a1951.png)

**Comment by BenVlodgi** [comment]
What is invalid? XOR gates only activate when only one of the inputs are active.
![image](https://cloud.githubusercontent.com/assets/1462374/12951545/d4201298-cfe0-11e5-843e-aea5bda5980e.png)


https://en.wikipedia.org/wiki/Exclusive_or
http://www.ee.surrey.ac.uk/Projects/CAL/digital-logic/gatesfunc/

**Comment by goodDOS** [comment]
@BenVlodgi Can be used before update

**Comment by goodDOS** [comment]
@BenVlodgi You have a try

**Comment by BenVlodgi** [comment]
If you activate just one input, does the output activate?

**Comment by goodDOS** [comment]
@BenVlodgi It is not active.

**Comment by goodDOS** [comment]
@BenVlodgi I found that trigger once could not activate XOR.Others seem to be able to activate XOR.

**Comment by Konclan** [comment]
I've had the trouble where trigger once will not activate logic gates in general, it could just be a bug with them.

**Comment by TeamSpen210** [comment]
This should be resolved by the same fix as #400.
