### ISSUE TITLE
Pre-Release 18

### ISSUE THREAD

**Issue by SpyyZ158** [BenVlodgi/BEE2.4#197]
I am having problem at starting up Pre-Release 18, I don't know what to do ...I have downloaded everything I needed like I always do but it just doesn't want to startup so I am using Pre-Release 17 I hope I am not the only one who has this problem ;) I hope it will be quick and great answer  .

**Comment by LautaroL20** [comment]
It would be helpful if you copy-paste the txt notes contained in the "logs" folder from bee 2.4 Prl18, in this text must show whats going on.

**Comment by Tomidlo158** [comment]
The point is Bee2 crashes with logs so I kinda don't know.

**Comment by TeamSpen210** [comment]
There should be a logs/ folder containing `BEE2-error.log`. What does that say?

**Comment by Tomidlo158** [comment]
It just shows my old Pre-Release 17's logs but it doesn't save for Pre-Release 18

**Comment by Tomidlo158** [comment]
So kinda doesn't say anything in logs of things from Pre-Release 18

**Comment by BenVlodgi** [comment]
Is your pr18 in a different folder than pr17?
I don't think its a good idea to merge releases. If you did do this, try clearing out your bee2 folder completely, then add pr18

**Comment by Tomidlo158** [comment]
I had kinda these problems when something was missing for me so I have no idea.It never happend before when I was replacing them.Already tried by the way removing whole folder and making new one but didn't worked.

**Comment by Tomidlo158** [comment]
I hope it get's fixed in next release ...for now well I'll be using 17th version.

**Comment by Tomidlo158** [comment]
By the way I would like to know if is bad when I download BEE2.4_pr18_win.zip and Source code (zip)
same with packages.

**Comment by LautaroL20** [comment]
The "Source code.zip" is not necesary to use this mod. You only need "Bee2.4" and "Pakages" zip files, only.
