### ISSUE TITLE
Bee 2.4 Prl18 - User Interface gets freeze forever after click on "Change Defaults..."

### ISSUE THREAD

**Issue by LautaroL20** [BenVlodgi/BEE2.4#199]
If you click on "Change Defaults..." over any item from the Bee 2.4 UI, it will become freeze forever, and then, the "Task Manager" will become your best friend in case you want to close Beemod.

-----------------------------------------------------------------------------------------------------------

![task manager](https://cloud.githubusercontent.com/assets/12244376/13032366/520c3700-d2ce-11e5-9d5e-078503b77b9e.png)

**Comment by LautaroL20** [comment]
I can confirm that this bug is not present in the UI from the "PRL17".

**Comment by TeamSpen210** [comment]
This is the same issue as #195, and it's fixed for the next version.

**Comment by LautaroL20** [comment]
lol, sorry, i promise to check better between the reported issues in the future.
