### ISSUE TITLE
Add bottomless pits to initial release

### ISSUE THREAD

**Issue by ellingtonisland** [BenVlodgi/BEE2.4#20]
bottomless pits should be included with the initial release, a glados clean style with bottomless pits instead of goo would work well for the first release of this new version of bee2.

**Comment by ncrecc** [comment]
There's already an option somewhere to turn the goo pits into Wheatley's bottomless pits, meaning that making entirely separate styles just for bottomless pits or different monitors or other things like that is now pointless.

**Comment by TeamSpen210** [comment]
I'm not sure if clean style will include a bottomless pit option, but some styles will probably allow both versions. (I'm planning on using the pit functionality to allow you to see the enrichment sphere and supports around goo in Old Aperture maps. From now on, different style variants like that will just be a Style Property, or chosen via the main picker menu (for voice lines, music, elevator videos).

Bottomless pits anyway will only appear if the goo surface is occupying the lowest 2 or so blocks in the map. (Lots of visual oddities ensure if any part of the real map is below the goo area).
