### ISSUE TITLE
Pre-release 18 - Vbsp Failed

### ISSUE THREAD

**Issue by harritron2k2** [BenVlodgi/BEE2.4#202]
I can't build a clean chamber with no items in it. I recently got a new computer and transferred my files over from the new, and ever since then, I get a error building a test. Could this be because I need to reinstall the game? Here is the screenshot. 
![2016-02-15_00001](https://cloud.githubusercontent.com/assets/13120164/13057872/29161d70-d3dc-11e5-8eab-5989a5ec70c2.jpg)

**Comment by BenVlodgi** [comment]
Did you re-open the BEE2.4?

**Comment by harritron2k2** [comment]
Never mind. I reinstalled Portal 2 and that fixed the problem.
