### ISSUE TITLE
Sort items on palette

### ISSUE THREAD

**Issue by LautaroL20** [BenVlodgi/BEE2.4#209]
I was not able to find any user reporting this issue, so here is it. It would be cool to have a static menu as the one from Bee 2.2.5 alpha, in order to prevent the random messy items every time Bee 2.4 is Re-open, as we can see on this gif:

![gif](https://cloud.githubusercontent.com/assets/12244376/13376943/fa0ac164-dda6-11e5-9fd0-aae2e94ef4e2.gif)

**Comment by TeamSpen210** [comment]
Any particular preference to the order? I can sort it by basically anything, it's currently unsorted so items will effectively appear in random order.

**Comment by jccreszMinecraft** [comment]
I suggest functional>decorational.

Droppers, Fizzlers variants, etc in a row before the more decorational items.

**Comment by LautaroL20** [comment]
@TeamSpen210 Im going to propose some suggestions to have items order, tomorrow, i still need to finish the concept art of them. I promise those concept will be as clear and sence as possible.

**Comment by LautaroL20** [comment]
#212

**Comment by Konclan** [comment]
Why is this issue still open if this has been fixed?
