### ISSUE TITLE
IDEA: rename Bee2.4 to Bee 3??

### ISSUE THREAD

**Issue by ellingtonisland** [BenVlodgi/BEE2.4#21]
i have an idea, since bee2 is the last version of the bee editor, this new one will have MANY new things which will make it COMPLETELY different from bee2. it might be a good idea to just rename this one to bee 3 on initial release.

**Comment by TeamSpen210** [comment]
It's not as big a leap between BEE1-2. It still does the same thing, just with a bunch of improvements to the item format and other tweaks.

**Comment by Luke18033** [comment]
BEE3 would probably be a PMP sort of thing.
