### ISSUE TITLE
HEP missing texture.

### ISSUE THREAD

**Issue by CrashingScience** [BenVlodgi/BEE2.4#210]
This error only applies if you DO NOT have bee2.4 installed. The glowing effect around a pellet has a missing untextured box. The box is translucent and the pellet is still visible inside. This isn't just beemod because on the map gelocity 3 there is a high energy pellet which has the same error, Any way to fix this?

**Comment by BenVlodgi** [comment]
Resources not getting packed it sounds like. Though I'm not sure why that problem would happen for Gelocity 3

**Comment by CrashingScience** [comment]
Im going to test this out more, getting a freing to test it to.

**Comment by CrashingScience** [comment]
this is not a bug, works fine
