### ISSUE TITLE
Old style coop checkpoint error.

### ISSUE THREAD

**Issue by CrashingScience** [BenVlodgi/BEE2.4#211]
I couldn't compile a map with an old style checkpoint but the reason I was trying to do so is because in the old beemod one robot could press both buttons inside if they were quick.

**Comment by TeamSpen210** [comment]
In the next version I'll have properly ported over the checkpoint variations. The buttons aren't actually a problem - you can press both buttons, but nothing will happen until both players are inside the checkpoint as well. (All 4 conditions must be true to trigger the doors.)
