### ISSUE TITLE
[Suggestion] Improvements to the Old Aperture companion cube (make it a little more authentic-looking)

### ISSUE THREAD

**Issue by ncrecc** [BenVlodgi/BEE2.4#217]
I understand this might be a ridiculous thing to make an issue about, but it doesn't fit in that much compared to the rest of the Old Aperture style.

1. **Make the marker less strong:** The marker used to draw the hearts with completely draws over the checkered square on two of the sides, as if it wasn't even there in the first place. Markers aren't that strong.
2. **Make the hearts slightly different on each side:** As if they were hand-drawn by Cave and not just copy-pasted with an image editor.
3. (optional) **Have the Aperture logos scribbled out, with a heart drawn next to it:** This would replicate some of the silly quirkiness that Cave Johnson, and Aperture in general, was known for. What better way to motivate test subjects than to try and make them forget that they're working in some of the most dangerous conditions possible?

Again, I really hope nobody sees this as a tall order, or just bossy in general. I just think it would make the style seem slightly more realistic compared to the rest of the game.

**Comment by TeamSpen210** [comment]
This isn't ridiculous at all, I'd really appreciate feedbsck on these custom models and things. FYI, the original materials are located in the (tspenAddons-src)[https://github.com/TeamSpen210/tSpenAddons-src/blob/master/materials/underground_cmpanion_cube.pdn] repro, which I should probably rename.

**Comment by Enterpise** [comment]
Everything related to "items" in specific, must be posted here:

https://github.com/TeamSpen210/BEE2-items/issues

**Comment by TeamSpen210** [comment]
Moved to TeamSpen210/BEE2-items#309.

**Comment by TeamSpen210** [comment]
This isn't ridiculous at all, I'd really appreciate feedbsck on these custom models and things. G
