### ISSUE TITLE
Suggestion: Customizable Signage

### ISSUE THREAD

**Issue by ellingtonisland** [BenVlodgi/BEE2.4#22]
i think you should implement this into this new version of bee2 if you havn't

Customizable test chamber Signage

here's what you should be able to change or add (for small description)

- name of test chamber
- a small description below the name (such as "difficulty level = challanging")
- the test elements used in the test chamber that are lit in black on the sign
- show custom test elements on the sign lit up in black (such as a sendificator)

**Comment by TeamSpen210** [comment]
Valve already made this basically - The test chamber sign in DLC2 displays the items in the map, current progress through your subscribed maps, the map name, and other stuff. Implementing a custom one automatically would be horribly complicated - the BEE2 would have to generate the texture, fill in all the details, save it into the game and then generate an instance with the new sign, and then pack it into the map. This also doesn't work well with Old Aperture / BTS styles, which don't have these test chamber signs.

I will probably make a secondary sign panel that displays indicators for some of the custom elements, but there won't be a custom sign - it doesn't really add anything.
