### ISSUE TITLE
Block Portals in Old Aperture exit corridors to prevent getting trapped

### ISSUE THREAD

**Issue by CrashingScience** [BenVlodgi/BEE2.4#222]
I assume this is still an issue, but i can't check because of the fact that the chamber unloads after going towards the lift, and is replaced by an empty corridor. Sent white gel through the exit door, shoot a portal on this after exiting and then place another portal inside the chamber, through the observation grating. You should now be back inside the chamber, stuck if you move your portals.

**Comment by TeamSpen210** [comment]
I'll add a `func_noportal_volume` to the exit corridors, to stop you from placing portals at all.
