### ISSUE TITLE
[Suggestion] Open door

### ISSUE THREAD

**Issue by MrKrunk** [BenVlodgi/BEE2.4#223]
As I am writing this, I am using my tablet. So at the moment I cannot attach images to the post. As soon as I can, I will do so on my computer. Onto the suggestion.
There are sometimes open doors between windows in the first Portal game. Originally, portal wasn't going to have chamber lock doors. Each test chamber exit would be an open area with a white border along the chamber walls. The border seen around observation areas in the first portal game is what I am referring to.

**Comment by TeamSpen210** [comment]
You mean like the hallway on the right-hand side of [this image](http://theportalwiki.com/wiki/File:Portal_Test_Chamber_15.png)? I might go implement this in exit corridors instead of the door, if the door has no connections and is set to start unlocked.

**Comment by TeamSpen210** [comment]
Implemented in 70s style via TeamSpen210/BEE2-items@b9fb7e847de7aebf7f41b5982e662bc1514a6363
