### ISSUE TITLE
[BUG] Portal on Observation Room

### ISSUE THREAD

**Issue by xDadiKx** [BenVlodgi/BEE2.4#224]
![2016-03-05_00001](https://cloud.githubusercontent.com/assets/13087761/13550031/bc4aaaf0-e30b-11e5-88c0-4e6d3b2e121b.jpg)

Just put a portal right next to it and place a orange portal onto the blue portal.

**Comment by Enterpise** [comment]
LOOOOOOOOL WHAT A BUG!!!

**Comment by Tomidlo158** [comment]
Why I feel in the air sv_portal_placement 1?Maybe not :P

**Comment by xDadiKx** [comment]
Closing Issue
