### ISSUE TITLE
Release Date??

### ISSUE THREAD

**Issue by ellingtonisland** [BenVlodgi/BEE2.4#23]
So when's this thing coming out?
hopefully by summer.
consider creating a deadline so it gets done.

**Comment by TeamSpen210** [comment]
I'd like to release the UI in the next couple of weeks. It's basically done. The compiler still needs one or two features, though. The real issue is items - most of the items and styles haven't been converted yet.

**Comment by ellingtonisland** [comment]
convert the items and styles first, no need to rush it and have it FOREVER bad as myamoto says.
