### ISSUE TITLE
There is no windows version "BEE2.4_pr19_win.zip" available in the download page.

### ISSUE THREAD

**Issue by LautaroL20** [BenVlodgi/BEE2.4#230]
Today i wanted to download the latest pre-release, but unfortunately i was not able to find the windows version in the page download: https://github.com/BenVlodgi/BEE2.4/releases

-------------------------------------------------------------------------------------------------------

Only version abailable ive found was mac os x, but it is not compatible on Windows 7.

**Comment by xDadiKx** [comment]
There was a crash for PR19. That means we have to wait for a bit.

**Comment by LautaroL20** [comment]
I have seen that bug report you re talking about, but i thought the user was testing the Mac version from Bee 2.4, since that "user" does have a Mac.

**Comment by TeamSpen210** [comment]
Fixed. (The crash bug occurs in both platforms.)
