### ISSUE TITLE
[PRL19 Bug] Aperture Tag music not building in the map.

### ISSUE THREAD

**Issue by LautaroL20** [BenVlodgi/BEE2.4#231]
![aperture tag music not working](https://cloud.githubusercontent.com/assets/12244376/13729819/cfacc94a-e91c-11e5-8614-9f2df91fdbfc.png)

**Comment by TeamSpen210** [comment]
Those only work if you're using Aperture Tag itself. (Including a copy of the music will balloon the file size substantially.)

**Comment by Gimzie** [comment]
I made a tutorial on how to get it to work in Portal 2. (Only if you have brought Aperture Tag)
It's in the README.txt.
https://drive.google.com/file/d/0B6SvahCOfVqMZnNpbml0YTE4eDQ/view?usp=sharing
You only have to do it once.

**Comment by Konclan** [comment]
This should be closed then because its not an actual bug?
