### ISSUE TITLE
[PRL19 Bug] Clicking "Hide / Show the "Compile" and "Pallete" windows options not works.

### ISSUE THREAD

**Issue by LautaroL20** [BenVlodgi/BEE2.4#232]
VIDEO SHOWING THIS BUG: https://www.youtube.com/watch?v=_O6ffTqS_x4

**Comment by TeamSpen210** [comment]
Does this still occur? I can't replicate it.

**Comment by LautaroL20** [comment]
I will record the bug with Camtasia Studio on 1080p Res, and going to upload it on YT. Using GIF Cam would not be useful for this case.

**Comment by LautaroL20** [comment]
Ah, finally i got Camtasia working as i wanted on 1080p, it was a pain to set it up, but here is the bug recording. Some important details about this rec:

I recorded this by installing Bee2.4 from stchatc, until reaching the part in where i replicate this issue.
Be sure to watch this in the highest resolution possible.

REC LINK: https://www.youtube.com/watch?v=_O6ffTqS_x4

**Comment by Konclan** [comment]
I'm pretty sure its because when you fullscreen the windows are either pushed out of the way or they are behind the inventory window

**Comment by LautaroL20** [comment]
Not to forger that the "Export Options" and "Style Properties" clickboxes works pretty normal as shown on the video recording, so i dont know what is causing this strange bug on the "Compile" and "Pallete" to not return them to the view.

**Comment by LautaroL20** [comment]
This was fixed with the Prl21.5
