### ISSUE TITLE
[PRL19 Bug] Item Icons from the Bee 2.4 pallete on the "Text Box" are non-selecable with "Left Click"

### ISSUE THREAD

**Issue by LautaroL20** [BenVlodgi/BEE2.4#233]
This only works clicking them with "Right Click" only.

-------------------------------------------------------------------------------------------

![bee 2 4 ui submenu icons are non-selectable if using left click](https://cloud.githubusercontent.com/assets/12244376/13729872/fff64422-e91d-11e5-9ad1-e53e1333e953.png)

**Comment by TeamSpen210** [comment]
You can only right-click them there since they aren't draggable (which is what left-click does).
