### ISSUE TITLE
[PRL19 Bugs] Wrong information in all the gels items on the little icons from the text box.

### ISSUE THREAD

**Issue by LautaroL20** [BenVlodgi/BEE2.4#234]
For example, all the gel droppers accepts imputs. In the Bee 2.4, the small icons from the "text box info" says they does not accepts them:

_____________________________________________

![gels items wrong info pallete](https://cloud.githubusercontent.com/assets/12244376/13729894/77f1d784-e91e-11e5-9ddb-e314d4210fbb.png)

**Comment by TeamSpen210** [comment]
It's not technically wrong. That data is grabbed from the item configuration. In the PeTI, the 'gel dropper' and 'gel splat' are two seperate items, which get moved around together. That data is taken from the splat object, which can be placed on all surfaces and doesn't accept inputs. I might add a special case for this though as well as for cube droppers.
