### ISSUE TITLE
[PRL19 Bug] Death fizzler and Paint fizzler still uses the same icon in the pallete and are unordered.

### ISSUE THREAD

**Issue by LautaroL20** [BenVlodgi/BEE2.4#235]
And they re unordered:

---------------------------------------------------------------------

![pallete bug](https://cloud.githubusercontent.com/assets/12244376/13729916/0a58cfb0-e91f-11e5-9ad0-d37b262dfe80.png)

**Comment by TeamSpen210** [comment]
This issue was moved to TeamSpen210/BEE2-items#359
