### ISSUE TITLE
[Wrong Link] Link of Packages 19 Pre-Release

### ISSUE THREAD

**Issue by SpyyZ158** [BenVlodgi/BEE2.4#239]
https://gyazo.com/a0d13c34729d58122137ef4891026ce3

https://gyazo.com/339704efb59b476a5ea609130b21f173

**Comment by SpyyZ158** [comment]
ahh I think I should have made it to packages issue ,if it's wrong, my bad

**Comment by xDadiKx** [comment]
Wait, you mean you can't find it?

If so, here's the link
https://github.com/TeamSpen210/BEE2-items/releases/tag/pr19_

**Comment by TeamSpen210** [comment]
Fixed.
