### ISSUE TITLE
Giant Ceiling Light / Light Set

### ISSUE THREAD

**Issue by Konclan** [BenVlodgi/BEE2.4#245]
I have an idea for a large light or set of lights for the roof of test chambers. The reason I want this is because I feel like the overgrown large light could be a hole in the roof that reveals sunlight. Even if it is not possible for a hole in overgrown I feel like this item would still be useful.

**Comment by TeamSpen210** [comment]
My original BEE2 addons had a ceiling light item just like this. I'm going to eventually add in a ceiling cutout tile instance for overgrown-style ceiling holes.

**Comment by Konclan** [comment]
Awesome good to know

**Comment by Konclan** [comment]
Since you already have this item in the list at TeamSpen210/BEE2.4-items#95
