### ISSUE TITLE
Music Error

### ISSUE THREAD

**Issue by Konclan** [BenVlodgi/BEE2.4#246]
Some normal portal 2 music like Comedy = T + T seems to give me an error sound. I do not know if this is just me. Also I do not know how compatible portal 1 and other music is with the game yet. Is it possible that you can make it so that custom models, textures, and sounds used in the map are published with the map or would that be too hard?

**Comment by Konclan** [comment]
I think I found the cause, the bts announcer sound was the missing one and because of that the music file didn't start

**Comment by TeamSpen210** [comment]
All the needed files are packed automatically. Actually, sound files only work if they're being packed.

**Comment by Konclan** [comment]
But when publishing the map the needed files are not published with the map file

**Comment by Konclan** [comment]
I'm still having trouble with music not playing in the overgrown style. I get an error sound ("Oh fiddlesticks, what now") when I go through the entrance and each time I respawn.

**Comment by LautaroL20** [comment]
@Konclan - Thats a bug of the Portal 1 style wich i already reported: "A "Mysterious" Wheatly voice line starts playin in Portal 1 Style in the SP mode" https://github.com/TeamSpen210/BEE2-items/issues/354

**Comment by Konclan** [comment]
Its not wheatlys voice, its a sound that played when a sound file is missing.

**Comment by Konclan** [comment]
https://developer.valvesoftware.com/wiki/Missing_content

**Comment by Konclan** [comment]
Also I was using the Overgrown Style with normal portal 2 music

**Comment by LautaroL20** [comment]
Well, the quote voice line "Oh fiddlesticks, what now" it is from a character called "Wheatly".

**Comment by Konclan** [comment]
I know who Wheatley is and on the wiki it tell you its Dr Kliener from the half-life 2 series

**Comment by xDadiKx** [comment]
If you ever played half life 2, you would know the fiddlesticks thing.

**Comment by LautaroL20** [comment]
That sounds like a younger voice to be from Dr kleiner who is an "Old". Then i must be confused due to using a spanish translation.

**Comment by Konclan** [comment]
That makes more sense then

**Comment by xDadiKx** [comment]
https://youtu.be/V6cV_DuryBc?t=13m18s 
Here is a link where he says that.

**Comment by xDadiKx** [comment]
I mean https://youtu.be/V6cV_DuryBc?t=13m47s

**Comment by LautaroL20** [comment]
Ah, i see. Sorry i was wrong then, i think i should change the language on all valve games to prevent getting confused. Valve did an amazing voice translation for "Spanish", but terrible voice casting valve did on the english version.

**Comment by xDadiKx** [comment]
It's alright.

**Comment by LautaroL20** [comment]
Also, i must to say "Wheatly spanish voice" sounds identically to the "Dr. Kleiner english voice", thats the reason of my confusion.
