### ISSUE TITLE
Turrets can be put on angled panels but not drawbridges

### ISSUE THREAD

**Issue by ncrecc** [BenVlodgi/BEE2.4#249]
![I assume this is the same for a few other items.](http://i.imgur.com/Of2bYYp.png)

**Comment by TeamSpen210** [comment]
I don't think i can fix this - the ability to place cubes/turrets on other items is basically hard-coded into the editor.

**Comment by xDadiKx** [comment]
But would it be possible to do that?

**Comment by TeamSpen210** [comment]
It's possible, but I might need to add an extra 'panel angle' property.
