### ISSUE TITLE
Old Aperture crusher set to "Start Enabled" will actually pull in instead of going out

### ISSUE THREAD

**Issue by ncrecc** [BenVlodgi/BEE2.4#251]
http://i.imgur.com/FDurHaD.webm
This does not happen to it when it is given a regular input.

**Comment by LautaroL20** [comment]
I highly recommend to check already reported bugs before posting, and their respective sections, this is focus in the Bee2 interface rather than "Items". This was already reported by me "Old Aperture "Spike Crusher" is Buggy as Hell" https://github.com/TeamSpen210/BEE2-items/issues/355

**Comment by ncrecc** [comment]
You never mentioned it only happened when set to "start enabled".
