### ISSUE TITLE
Portal 1 Style Compile Error

### ISSUE THREAD

**Issue by Konclan** [BenVlodgi/BEE2.4#256]
Angled Panels in the portal 1 style create a compile error
Console reports that the instance is missing

**Comment by LautaroL20** [comment]
To report bugs related to items, like you did, must be posted here: https://github.com/TeamSpen210/BEE2-items/issues

And it was already reported in the "Items section" by another user: https://github.com/TeamSpen210/BEE2-items/issues/414
