### ISSUE TITLE
Make Aperture Tag and PS:Mel music available in vanilla Portal 2

### ISSUE THREAD

**Issue by TeamSpen210** [BenVlodgi/BEE2.4#257]
When loading, check adjacent folders for selected games to find PS:Mel and Aperture Tag. If found the music files will be copied to all other games when exporting.

**Comment by Gimzie** [comment]
Would the music be packed into the bsp, so others who don't have aperture tag would get it?

**Comment by TeamSpen210** [comment]
Yes. The issue isn't distributing the files, it's mainly to prevent massively ballooning the download size.

**Comment by Gimzie** [comment]
Ah, so whoever has Aperture Tag can include the music, but anyone can get the sound to play when playing the published map. (Also, I don't know how distributing would work, because Aperture Tag is a paid mod.)

**Comment by TeamSpen210** [comment]
Additionally these music paskages should not be shown if we can't find the matching resources.

**Comment by TeamSpen210** [comment]
Now done! Portal Stories: Mel's music is available too.

**Comment by Gimzie** [comment]
When will it be released?
