### ISSUE TITLE
Styled Items In Other Styles ( RIP Grammar )

### ISSUE THREAD

**Issue by TheReviewers** [BenVlodgi/BEE2.4#259]
Like Having a portal 1 panel in 1950's style and overgrown wall in portal 1 etc.

**Comment by TeamSpen210** [comment]
This wouldn't make any sense, and look really wrong. Additionally, many items depend on parts of the style - Old Aperture Large Observation Grates need to link to a portal in the sphere, for example.

**Comment by TheReviewers** [comment]
Some Stuff would Be Gud Tho, Dont You Think?

**Comment by TeamSpen210** [comment]
Aside from perhaps Clean <> Overgrown, it wouldn't make much sense. I can fairly easily define specific conversions for a particular item, like the mechanical Faith Plate option if it's desired.

**Comment by BenVlodgi** [comment]
I don't think this is a feature that should be put in the hands of BEE users, if someone wants to defy a style, they should have to do it in hammer

**Comment by TheReviewers** [comment]
OMG Ben Commented. I LOVE YOUR WORK!!

**Comment by TheReviewers** [comment]
HAI BEN

**Comment by BenVlodgi** [comment]
Hi @TheReviewers glad you've liked it :)
Though @TeamSpen210 has pretty much single handedly managed this version of the BEE2. Make sure to give him some <3

**Comment by TheReviewers** [comment]
@TeamSpen210 And @BenVlodgi  How Can You Guys Take The Issues And Complains EveryDay?

**Comment by BenVlodgi** [comment]
If you love something, then you want it to be the best.
BEE2 and I are in the friendzone now though :smile:
