### ISSUE TITLE
Tubes

### ISSUE THREAD

**Issue by TheReviewers** [BenVlodgi/BEE2.4#260]
Well, Ive Been Thinking Of A New Item. 
A TUBE ( No Dirty Reference Intended)
Basically You Connect 2 Tube Items Together, And It Sticks Together, You Can Add Cubes In It, Or Gel, Or Any Other Item, You Can Also Add Destroyable Version Using Bombs Or ( Broken ) Rocket Turret,
And You Use An Item Similar To Portal Magnet, To Choose Where The Destroyed Tube Of Gel Will Go ( To Paint Walls)

**Comment by towergame** [comment]
If you mean the destroyable pipes from the Wheatley boss fight. Then yeah that would be cool

**Comment by TheReviewers** [comment]
I Also Mean Destroyable Tubes From Portal 1, To Get A Cube

**Comment by TeamSpen210** [comment]
This is a duplicate of TeamSpen210/BEE2-items#1.
