### ISSUE TITLE
Lots Of Bugs With The Portal 1 Panels

### ISSUE THREAD

**Issue by TheReviewers** [BenVlodgi/BEE2.4#261]
You Cant Go Through Portals On IT, You Cant Connect Any Button To It Etc...

**Comment by LautaroL20** [comment]
You are in the wrong section, this is only related to the Bee2.4 Interface. To report bugs related to any item, should be posted here: 

https://github.com/TeamSpen210/BEE2-items/issues

Also, if im not wrong, this bug has been already reported.
