### ISSUE TITLE
[Question] How to install a custom addon, editoritems code, etc into Bee2.4?

### ISSUE THREAD

**Issue by LautaroL20** [BenVlodgi/BEE2.4#262]
I have a vmf file and its code installed into the retro bee2.2.5, but i would like to migrate it for the newer version 2.4. My question is, what are the steps to install an addon in Bee2.4? 

-----------------------------------------------------------------------------------

![addons](https://cloud.githubusercontent.com/assets/12244376/14057432/0205bff8-f2de-11e5-95b6-79450b1ab352.png)

**Comment by TeamSpen210** [comment]
It's not very simple - the way the files are arranged is very different. Especially for styles, since the compiler commands have changed a lot.

**Comment by TheReviewers** [comment]
Can You Link Me The Download?

**Comment by LautaroL20** [comment]
@TeamSpen210 - Thank you so much for the help. It was very useful.

**Comment by BenVlodgi** [comment]
I know we've talked about creating a tool to help in the creation of custom items. I don't think efforts on that ever moved forward.
Best thing to do to figure it out is to look at examples in @TeamSpen210's items 

Here([/packages/sendificator](https://github.com/TeamSpen210/BEE2-items/tree/pr19_/packages/sendificator)) for example is how Teamspen implemented the sendificator into the BEE2.4. This does a good job to show how you separate different style implementations.

the package file that you release is a zipped up folder of those contents.
It has to have the info.txt at the root which has the exposed information about your package
The resources folder is for new files that you need

*I was writing this response last week and just found the tab open.*

**Comment by LautaroL20** [comment]
Alright, thanks Been!
