### ISSUE TITLE
Suggestion: Underground BTS and Broken Observation Rooms.

### ISSUE THREAD

**Issue by Coolasp1e** [BenVlodgi/BEE2.4#263]
This'll probably be EXTREMELY difficult to do, but you know the areas in the underground where everything is pretty much broken, but you can still solve the test via outside the chambers? Example: Exiting out of one test chamber, but to get to the next, you have to do some portaling around because the catwalk is broken. This would be really cool as you feel like you're not trapped in a box. Although, it may be extremely difficult as: You have to pretty much get a LOT of props. Though, the props could be used via timer. And you have to create a way to get the skybox in so that it isn't just nodraw. One more thing, if it's possible, is to add broken observation rooms with the doors unlocked, which could lead to another puzzle. That would be added in overgrown. Just some suggestions.

**Comment by Konclan** [comment]
So what you're suggesting is a way to escape the test chamber via a pre-made bts escape area. This wouldn't work because:
1. The item to generate these would be massive
2. If a lot of BEE2.4 maps use this, it becomes easy and predicable to spot these. Making their point totally pointless

**Comment by Coolasp1e** [comment]
Not really. I'm not asking for a premade entrance/exit, but a style in which the entire test chamber has fallen apart. The only parts that are not broken are the test elements. The observation room idea would be an exit thing.

**Comment by TeamSpen210** [comment]
You can't really do different style transitions like you would need with these observation rooms here. Underground BTS is planned at some point, I don't want to work on that yet since I still have a huge backlog of bugs and things to port.
