### ISSUE TITLE
Bee mod not working

### ISSUE THREAD

**Issue by Friccmejerry** [BenVlodgi/BEE2.4#267]
I did everything right but when i run the EXE theres only a popup that goes away after a second. I'm using the version 18 packages because V19 didnt seem to have any

**Comment by TheReviewers** [comment]
re-install it, i had this problem too

**Comment by TeamSpen210** [comment]
Here are the [pr19 packages](https://github.com/TeamSpen210/BEE2-items/releases). That's probably the issue, post a copy of `BEE2.4/logs/bee2.log` so I can know what the actual error is if that doesn't fix it.
