### ISSUE TITLE
Item Idea-Bottomless Pits

### ISSUE THREAD

**Issue by Coolasp1e** [BenVlodgi/BEE2.4#269]
What's the reason for Catwalks WITHOUT bottomless pits?

Probably goo, but nothing else.

**Comment by TeamSpen210** [comment]
It's useful to allow players to move from one place to another, but only on particular paths, or to move vertically easily without portals or moving systems.

**Comment by Coolasp1e** [comment]
I'm stupid xD

What I meant was adding bottomless pits.

Basically, it could be like the cutout tile, only with bottomless pits.
You know, instead of goo for maps that want to add such bottomless pits.

**Comment by TeamSpen210** [comment]
Set the skybox to 'factory - 3D', and put a goo pit at the bottom of the map.

**Comment by Coolasp1e** [comment]
Ok. Thanks!
