### ISSUE TITLE
Override VPK editor wall textures for styles

### ISSUE THREAD

**Issue by ellingtonisland** [BenVlodgi/BEE2.4#27]
i see your getting a model chooser implemented, also i have some suggestions of things to implement into the final version and then get all items and styles converted and get it released.

- when the style changes, figure out a way to have it change the default graphics shown in the PTI editor such as for a overgrown style, show overgrown panels in the pti editor instead of the default clean ones (i'm talking about the PTI editor wall and floor panels etc shown in this image: http://www.maclife.com/files/imagecache/futureus_imagegallery_fullsize/gallery/pti2.jpg), and for a wheatley style have the default goo graphic be replaced with a bottomless pit graphic) do the same thing with PTI for the underground style, and wheatley.
- ~~if there is no way yet to create and use custom voice lines in your test chamber, implement it.~~
- ~~<b>(DO THIS)</b> allow the player to choose what entrance or exit elevator their test chamber will have (for more style customization ect, and style transitions etc)~~

**Comment by ncrecc** [comment]
1. That's what he's doing, man. Do you even check his screenshots of Portal 2?
2. That sounds like some pretty complex stuff. Not sure if it'll happen.
3. For the millionth time, no. You've asked this over and over again and tSpen has said "no" over and over again, so stop asking.

**Comment by ellingtonisland** [comment]
cleaning up
