### ISSUE TITLE
P1 4th exit observation room

### ISSUE THREAD

**Issue by corrupt21** [BenVlodgi/BEE2.4#270]
The 4th corridor in the P1 style has an observation room which is literally nothing. I think it should be more decorated instead of plain walls.
![20160403115744_1](https://cloud.githubusercontent.com/assets/17777059/14230273/7433e38c-f993-11e5-86d2-97152a81c461.jpg)

**Comment by TeamSpen210** [comment]
The size allocated for the exit corridor makes that all the room that exists. To fix it, I'd need worldportals or similar tricks.

**Comment by BenVlodgi** [comment]
You could expand it a little to the right and left if you really wanted to, there is probably 32units on either side for expansion

**Comment by TheReviewers** [comment]
@BenVlodgi See The Story I Wrote For You XD

**Comment by BenVlodgi** [comment]
@TheReviewers Where?

**Comment by Konclan** [comment]
BenVlodgi/BEE2.4-Items#467
