### ISSUE TITLE
Connection Relay [Logic]

### ISSUE THREAD

**Issue by jccreszMinecraft** [BenVlodgi/BEE2.4#272]
An item that can be hooked into by inputs and relay to other items to activate.

This is useful for when some items need to connect to more than 10 things. Delayer item can be integrated into this.

**Comment by TeamSpen210** [comment]
Use a Antline Magnet for this, or an AND gate. The number of connections is actually limited by the number of antline connection points, although I'll need to test to see if there's another higher limit as well. That can be solved by adding more locations to items where there's room for them.
