### ISSUE TITLE
Item Idea - Trapped Companion Cube

### ISSUE THREAD

**Issue by Konclan** [BenVlodgi/BEE2.4#274]
A companion cube that when grabbed fizzles and outputs a signal. I would use this for secret areas in my maps

**Comment by TeamSpen210** [comment]
What uses would this serve? It sounds like it has the same functionality as a pedestal button.

**Comment by Konclan** [comment]
Idk I though it would be a fun idea to mess around with secret areas with my maps. I guess it really serves no more purpose than that.
