### ISSUE TITLE
Questions about the next release

### ISSUE THREAD

**Issue by Konclan** [BenVlodgi/BEE2.4#276]
Sorry to be a bother but how much stuff do you have planned before the next update and how much longer do you estimate it will take. I can wait for quality but I would like something to hope for :)

**Comment by TeamSpen210** [comment]
Currently I'm working on adding in customisable vactube items, which work similarly to scaffolds or catwalks. I also want to go fix a lot of the bugs which have been piling up recently.

**Comment by Konclan** [comment]
I understand, just really love the mod and can't wait for the update. But as I said I can wait

**Comment by Konclan** [comment]
Also thank you very much for being the awesome person you are, your so active unlike some people and really listen to your community. I don't feel like you get told this enough but I really appreciate your dedication to this mod. <3
