### ISSUE TITLE
Incorrect  Elevator Video Name

### ISSUE THREAD

**Issue by corrupt21** [BenVlodgi/BEE2.4#278]
Both laser videos have a typo.
![untitled](https://cloud.githubusercontent.com/assets/17777059/14374903/d87ab2b2-fd9e-11e5-9a2d-15e8f3513337.png)

**Comment by TheReviewers** [comment]
@corrupt21 What Is A Typo?

**Comment by Konclan** [comment]
An error made when typing, usually caused by fast typing, not paying attention, or not knowing how to spell the word.
