### ISSUE TITLE
Allow for more voice line options for SP/MP

### ISSUE THREAD

**Issue by Konclan** [BenVlodgi/BEE2.4#280]
I know you can enable and disable certain voicelines, but can there be an option so that you can specify the voice line you want. Some of the singleplayer voicelines and multiplayer voice lines I would like in either.

**Comment by TeamSpen210** [comment]
This is more complex than it appears - Cave, GLaDOS and Wheatley all use slightly different systems to play their voicelines. I'd also need to build up lists of the captions so you can find all the lines you want. Which lines in particular do you want to use?

**Comment by Konclan** [comment]
Well for one of my multiplayer maps I wanted to use the singleplayer entry cave johnson (50s) line "Welcome to Aperture Science"

**Comment by Konclan** [comment]
I also noticed that the "I Own The Place" doesn't play
