### ISSUE TITLE
How to spawn on other side of BTS entrance?

### ISSUE THREAD

**Issue by corrupt21** [BenVlodgi/BEE2.4#284]
Went looking in the map file of the entrance, and I found out that you can spawn on the other side of the glass. But I cannot figure out how.
![capture](https://cloud.githubusercontent.com/assets/17777059/14517107/23398c80-024d-11e6-8c5a-469ced6ceb65.PNG)

**Comment by TeamSpen210** [comment]
I haven't made it switch, but you can swap it by unchecking "Office Spawn" and checking "Catwalk Spawn" on the Visgroups toolbar. Once I get around to it, about half of the entry corridors will choose office-mode, and the other half will choose catwalk-mode.
