### ISSUE TITLE
Add Current Bug List

### ISSUE THREAD

**Issue by Konclan** [BenVlodgi/BEE2.4#285]
Can we get a place to see a list of all current bugs, like a google spreadsheets
It would be really useful to see every Release's bug list is one place
Also if there is a bug you have not seen you can find it there and avoid it

**Comment by LautaroL20** [comment]
There is no need to make a parallel spreadsheet website, or things like that. If you want to only see all the reported bugs Just click the "Issues" flap, and then click the "Lavels" drop down bar, and youll see the bugs into a Spreadsheet and well shorted.

And it is the exactly same for the TeamSpen Items page.

**Comment by TheReviewers** [comment]
@LautaroL20 Labels*
