### ISSUE TITLE
Portal 1 exit door does not open when both player are next to it

### ISSUE THREAD

**Issue by CrashingScience** [BenVlodgi/BEE2.4#286]

**Comment by Konclan** [comment]
Can we get a screenshot?

**Comment by Konclan** [comment]
also it's a good idea to post anything related to items here https://github.com/TeamSpen210/BEE2-items

**Comment by CrashingScience** [comment]
![20160416094735_1](https://cloud.githubusercontent.com/assets/16468734/14580204/ff60e566-03bd-11e6-9573-c3cc44bff30b.jpg)

**Comment by TeamSpen210** [comment]
This issue was moved to TeamSpen210/BEE2-items#480
