### ISSUE TITLE
portal 1 stairs pistons clip through tile on activation

### ISSUE THREAD

**Issue by CrashingScience** [BenVlodgi/BEE2.4#288]
![20160415152442_1](https://cloud.githubusercontent.com/assets/16468734/14564510/be23cb94-031e-11e6-901f-eb40e4dd4375.jpg)

**Comment by Konclan** [comment]
I don't understand the issue here, can you explain what here is wrong?

**Comment by TheReviewers** [comment]
@Konclan Just activate stairs in portal 1 style, and you will see, that the pistons go through the stairs

**Comment by Konclan** [comment]
Oh wow I just finally saw the small things sticking out of the floor
