### ISSUE TITLE
Spawn without Portal Gun

### ISSUE THREAD

**Issue by Konclan** [BenVlodgi/BEE2.4#290]
Add a toggle to the entrance item or to the BEE2.4 properties to have the player spawn without a portal gun. Eliminating having to use a hidden dual portal gun pedestal.

**Comment by TheReviewers** [comment]
you can just hide two auto portals XD

**Comment by Konclan** [comment]
Well the purpose of the toggle is so you don't have to do that. It makes it much simpler and wont have objects get in the way.

**Comment by Konclan** [comment]
I also wonder if you can have a coop without portal guns... I think that would be possible

**Comment by TeamSpen210** [comment]
I could add toggles like this, but there's a few issues with it. I need to ensure the player can never fire a portal while the same colour autoportal is open. If that happens the two portals will interfere with each other. For coop, there's a different issue - portalgun pedestals aren't locked to a particular player, so one player can pick up two portalguns - causing the other player to be unable to pickup a gun. I could fix that by making the pedestal respawn the gun constantly, but it still won't actually match the player's stripe colour.

**Comment by Konclan** [comment]
It is possible to have autoportals with different ids than the regular portal gun, I've seen it in maps before.

**Comment by TeamSpen210** [comment]
Yes, but those won't then work with the player's gun.

**Comment by TheReviewers** [comment]
@TeamSpen210 Did You Edit Your Comment, It Was Different Some hours Ago
