### ISSUE TITLE
[Enhancement]Portal Stories : Mel soundtrack

### ISSUE THREAD

**Issue by SpyyZ158** [BenVlodgi/BEE2.4#292]
I would like to ask if there will be soundtrack from Portal Stories Mel in future.

**Comment by TheReviewers** [comment]
Me Too :3

**Comment by TheReviewers** [comment]
And The Portal Stories Mel : ASHPD

**Comment by TeamSpen210** [comment]
The main reason I haven't added it is file size - it'll end up being 100mb or more larger. I'll do it once I've figured out a way to do updates so people don't need to redownload everything each time.

**Comment by TheReviewers** [comment]
Maybe Only Some Of Them, 

: The Best The World Had To Offer
Firestorm
Etc...

**Comment by LautaroL20** [comment]
@TeamSpen210 - The soundtrack from Portal stories mel is terrible, i remember being playing the mod and turning off the music volume. I consider this soundtrack as terrible as you consider the "Stretched long Light Strip" is.

Personally, the soundtrack from Aperture Tag Initiative is far decent than Mel´s one. So i hope Aperture Tag will be included in too.

**Comment by Konclan** [comment]
The music from aperture tag and Mel were made by the same person...

**Comment by LautaroL20** [comment]
@Konclan - Beethoven´s symphony No.2, and Symphony No.9 "Ode to Joy" was made by the same composer, and that does not mean both symphonies are equally good.....

So... Probably the composer from Aperture Tag did not made a decent work on the soundtrack from Mel.

**Comment by jccreszMinecraft** [comment]
Harry Callaghan was behind both soundtracks.

On Wed, Apr 20, 2016 at 2:53 PM, Lautaro <notifications@github.com> wrote:

> @Konclan <https://github.com/Konclan> - Beethoven´s symphony No.2, and
> Symphony No.9 "Ode to Joy" was made by the same composer, and that does not
> mean both symphonies are equally good.....
>
> So... Probably the composer from Aperture Tag did not made a decent work
> on the soundtrack from Mel.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/BenVlodgi/BEE2.4/issues/292#issuecomment-212557334>
>



-- 
*-~=~-*
*Ice Network Entertainment Studios*
*-~=~-*

Chores in videogames are ridiculous!

**Comment by LautaroL20** [comment]
Doesnt matter if its the same composer, Mel´s soundtrack is far below than Aperture Tag´s one, so considering Stories Mel´s songs will gonna be included, it should be the same for the Aperture Tag songs. Otherwise, it would be pretty unfair.

**Comment by TeamSpen210** [comment]
Tag music definitions are included already. I'll add some logic to copy over the music files if you also have Aperture Tag installed, so you can use them in Portal 2.
