### ISSUE TITLE
Laser emitter on floor behind glass

### ISSUE THREAD

**Issue by Konclan** [BenVlodgi/BEE2.4#294]
In the clean style, when placing a laser emitter on the floor and in the center, it should be placed under a small pane of glass so that you can more easily place cubes on top of it. Such as in Portal 2 Co-op Course 1 Chamber 5.
http://theportalwiki.com/wiki/Portal_2_Co-op_Course_1_Chamber_5

**Comment by TeamSpen210** [comment]
Actually, the collision mesh for laser emitters doesn't include the protruding emitter portion, so cubes can be placed directly on it. This is much nicer visually though.

**Comment by TeamSpen210** [comment]
This issue was moved to TeamSpen210/BEE2-items#487
