### ISSUE TITLE
Ingame screenshots don't update

### ISSUE THREAD

**Issue by Konclan** [BenVlodgi/BEE2.4#295]
When taking a screenshot for the map thumbnail (F5), it won't update until you run the map again.

**Comment by TheReviewers** [comment]
@Konclan Strange.. it works for me

**Comment by TheReviewers** [comment]
even without running map again

**Comment by TheReviewers** [comment]
instant reply :D

**Comment by TeamSpen210** [comment]
Yes, I can't avoid that. The thumbnail is overriden through some code in the compiler, which looks at screenshots to figure out the correct one. You'll need to run it again to replace thumbnails. That should be fine anyway, since you have to compile again whenever you publish a map.

**Comment by Konclan** [comment]
That's the problem, it doesn't update when you're publishing the map

**Comment by LautaroL20** [comment]
To everyone who want to have a "Custom Thumbnail" on your PeTi map without using the Publishing Tool. I have found a way to do it without causing secundary bugs like not displaying the thumbnail on the Queue and things like that. I have done this on my latest publish (Co-op N°9), here is the result from the Thumbnail: http://steamcommunity.com/sharedfiles/filedetails/?id=670999063

And of course i will made a Steam Workshop Guide on how to do this properly, soon.
