### ISSUE TITLE
Things That They Could Add and Fix (For The New BEE2 Editor)

### ISSUE THREAD

**Issue by Juleder** [BenVlodgi/BEE2.4#298]
* [x] Overgrown Obs Rooms on ceilings: That's something I definitely need to do, it's currently inconsistent.
* [x] Fix the I'm Different music track (it's currently broken)

-------------------------------

So I love the new BEE2 editor its really good! However they should add new stuff that were in the old BEE2 editor like Ceiling Lights I know there is ceiling lights in the new BEE2 editor (Just put the Observation Room on the ceiling) but for overgrown style nothing has changed.
Maybe you can make the ceiling lights broken like some are sparking and not working but others are working you know or make the sunlight. Next Wheatley Monitors I really like those nothing else to say just like them. Now the only bug I have is when I put a song like "I'm Different" by its self it doesn't work but if I put another song like "I Saw a Deer Today" the song plays but "collides" with "I'm Different and that can be annoying. 
Also add more styles to the new BEE2 editor like Refurbished, Art therapy and others. By the way for overgrown just make the tiny observation rooms broken and for old aperture make the turret models from Aperture Tag and add the double grate panel. 
I know there is a lot of suggestions but is it possible to have a item where the panel animations where they turn red and add 15 Acres Of Broken Glass and have the laser catcher make a beat like in the campaign. 
There is also a glitch with the BTS style the skybox doesn't work and the entrance doors are not the BTS doors. There you go remember you don't have to do these things its just a suggestion.

**Comment by Juleder** [comment]
Oh by the way TeamSpen210 how do I use the catwalks in the new BEE2 editor.

**Comment by TeamSpen210** [comment]
Place two in the map aligned in a straight line, and then connect them together via antlines.

**Comment by Juleder** [comment]
Oh thanks TeamSpen210 so just saying will you do some of these suggestions like I said you do not have to do it I'm not forcing you but just wondering?.

**Comment by TeamSpen210** [comment]
* [ ] Overgrown Obs Rooms on ceilings: That's something I definitely need to do, it's currently inconsistent.
* [ ] Fix the I'm Different music track (it's currently broken)
All/most of the items from my original addons are returning, see TeamSpen210/BEE2-items#95. 
Making laser catchers play music is one thing I'll be doing in the future, as well as the other styles.

**Comment by Juleder** [comment]
Thanks man your the best oh one thing I forgot that is it possible to fix
the autosaves  because when you die and you spawn in the autosaves the
music doesn't play.

**Comment by Juleder** [comment]
Also actually for the ceiling lights can you make two versions for
overgrown like one that is the sunlight and one with the regular lights but
they are rusty and some are broken?
