### ISSUE TITLE
Prl 20: Compile Error

### ISSUE THREAD

**Issue by Konclan** [BenVlodgi/BEE2.4#303]
VBSP failed.

[I] vbsp: BEE2.4.0pr20 VBSP hook initiallised.
[I] cond.core: Imported all conditions modules!
[I] vbsp: Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp: New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp: Clearing inject/ directory..
[I] vbsp: PeTI map detected!
[I] vbsp: Loading settings...
[W] instanceLocs: None in vals: False
[I] vbsp: Settings Loaded!
[I] vbsp: Parsing Map...
[I] vbsp: Reading Map...
[I] vbsp: Loading complete!
[I] vbsp: Forcing elevator spawn!
[I] vbsp: Setting Coop Exit to 1
[I] vbsp: Game Mode: COOP
[I] vbsp: Is Preview: False
[I] cond.core: Checking Conditions...
[I] cond.catwalks: Starting catwalk generator...
[I] cond.scaffold: Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold: Finished Scaffold generation!
[I] vbsp: Elevator type: FORCE
[I] voiceLine: Adding Voice Lines!
[W] BEE2_config: Config "bee2\voice.cfg" not found! Using defaults...
[W] BEE2_config: Config "bee2\mid_voice.cfg" not found! Using defaults...
[I] voiceLine: Adding Base instance!
[I] voiceLine: Quote events: []
[I] voiceLine: Generating responses data..
[W] BEE2_config: Config "bee2\resp_voice.cfg" not found! Using defaults...
[I] voiceLine: Adding quote: "Line"
 | 	{
 | 	"ID" "GENERIC_1"
 | 	"choreo" "scenes/npc/glados/a2_triple_laser01.vcd"
 | 	}
 |_

[I] voiceLine: End-commands: 
[I] voiceLine: Adding quote: "Line_COOP"
 | 	{
 | 	"ID" "GENERIC_1"
 | 	"Choreo" "scenes/npc/glados/botcoop_competition01.vcd"
 | 	}
 |_

[I] voiceLine: End-commands: 
[W] cond.core: "stylevartrue" is not a valid condition flag!
[I] voiceLine: 1 Mid quotes
[I] voiceLine: Adding quote: "Line_COOP"
 | 	{
 | 	"ID" "TURRET_DEATH"
 | 	"File" "clean/mid_turret.vmf"
 | 	}
 |_

[I] voiceLine: Done!
[I] vbsp: Added Screenshot Logic
[I] cond.core: Map has attributes: ['buttonacceptscube', 'pedestalbutton', 'weightedbutton', 'floorbutton', 'buttonacceptsball']
[I] cond.core: instanceLocs cache: CacheInfo(hits=17260, misses=251, maxsize=256, currsize=251)
[I] cond.core: Style Vars: {'allowgoomist': True, 'doorcameras': True, 'multiversecave': False, 'fixfizzlerbump': False, 'bee_show_trigger': False, 'unlockdefault': True, 'nomidvoices': False}
[I] cond.core: Global instances: {'instances/BEE2/clean/global_ents.vmf'}
[I] vbsp: Adding Music...
[I] vbsp: Adding Global PTI Ents
[I] vbsp: Editing Other Entities...
[I] vbsp: Editing Brushes...
[I] vbsp: Make Bottomless Pit: False
[I] vbsp: Editing Overlays...
[I] vbsp: Editing Triggers...
[I] vbsp: Collapsing goo triggers...
[I] vbsp: Done!
[I] vbsp: Editing Brush Entities...
[I] vbsp: Removing static indicator toggles...
[I] vbsp: Done!
[I] vbsp: Editing WorldSpawn
[I] vbsp: Making Pack list...
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3852, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 3449, in make_packlist
  File "F:\Git\BEE2.4\src\property_parser.py", line 278, in parse
  File "F:\Git\BEE2.4\src\property_parser.py", line 150, in read_flag
property_parser.KeyValError: Extra text after line: "models/hmw/props/sendificator_dirtyish.mdl"
Error occured on line 5, with file "bee2/pack_list.cfg"

It's not the same as #301

**Comment by TheReviewers** [comment]
:(

**Comment by TeamSpen210** [comment]
This should be fixed now with the pr20.5 packages.
