### ISSUE TITLE
How Do You Fix The Build Error.

### ISSUE THREAD

**Issue by Juleder** [BenVlodgi/BEE2.4#306]
Title.

**Comment by Konclan** [comment]
Can you give a screenshot of the map?

**Comment by Juleder** [comment]
Well if I click build and play puzzle with nothing on the map it does the error.

**Comment by Konclan** [comment]
Well what do you have in the map?
Also do you know how to open your dev console?

**Comment by Juleder** [comment]
I know how to open a dev console and for the map part I'm just testing some items but its not building the map.

**Comment by Konclan** [comment]
Go to options / Keyboard & Mouse / Enable Developer Console
Then press the ~ Key (Key to the left of the 1)

**Comment by Juleder** [comment]
I said I know hot top open the dev console

**Comment by Juleder** [comment]
*how

**Comment by Konclan** [comment]
Oh woops, sorry

**Comment by Konclan** [comment]
Type clear into your console then try to build the puzzle

**Comment by Juleder** [comment]
Okay.

**Comment by Juleder** [comment]
Nope didn't work.

**Comment by Konclan** [comment]
It wasn't supposed to, now copy and paste your console so we can see it

**Comment by Juleder** [comment]
What do you mean copy and paste?

**Comment by Konclan** [comment]
Select everything in console, Ctrl + C then Ctrl + V into the comments

**Comment by Juleder** [comment]
(KEEP CALM) My Pet Maicu unpaused the game
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 37 (ms)

VBSP failed.

[I] vbsp: BEE2.4.0pr20 VBSP hook initiallised.
[I] cond.core: Imported all conditions modules!
[I] vbsp: Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp: New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp: Clearing inject/ directory..
[I] vbsp: PeTI map detected!
[I] vbsp: Loading settings...
[W] instanceLocs: None in vals: False
[W] cond.core: Invalid weight! ()
[I] vbsp: Settings Loaded!
[I] vbsp: Parsing Map...
[I] vbsp: Reading Map...
[I] vbsp: Loading complete!
[I] vbsp: Forcing elevator spawn!
[I] vbsp: Setting SP Entry to 5
[I] vbsp: Setting SP Exit to 3
[I] vbsp: Game Mode: SP
[I] vbsp: Is Preview: False
[I] cond.core: Checking Conditions...
[I] cond.catwalks: Starting catwalk generator...
[I] cond.scaffold: Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold: Finished Scaffold generation!
[I] cond.vactubes: Running Generator (BEE2_VACTUBES)...
[I] vbsp: Elevator type: NONE
[I] voiceLine: Adding Voice Lines!
[W] BEE2_config: Config "bee2\voice.cfg" not found! Using defaults...
[W] BEE2_config: Config "bee2\mid_voice.cfg" not found! Using defaults...
[I] voiceLine: Quote events: []
[I] voiceLine: No responses data..
[I] voiceLine: 0 Mid quotes
[I] voiceLine: Done!
[I] vbsp: Setting Portalgun:
[I] vbsp: Blue: Y, Orange: Y
[I] vbsp: Done!
[I] vbsp: Added Screenshot Logic
[I] cond.core: Map has attributes: ['spawn_dual']
[I] cond.core: instanceLocs cache: CacheInfo(hits=2054, misses=247, maxsize=256, currsize=247)
[I] cond.core: Style Vars: {'multiversecave': False, 'bee_show_trigger': False, 'allowgoomist': True, 'unlockdefault': False, 'nomidvoices': False, 'fixfizzlerbump': False}
[I] cond.core: Global instances: {'instances/BEE2/bts/global_ents.vmf', 'instances/BEE2/logic/goo_fade.vmf'}
[I] vbsp: Adding Music...
[I] vbsp: Adding Global PTI Ents
[I] vbsp: Editing Other Entities...
[I] vbsp: Editing Brushes...
[I] vbsp: Make Bottomless Pit: True
[I] vbsp: Creating Bottomless Pits...
[I] vbsp: Done!
[I] vbsp: Clumping: 108 clumps (+ 0 special)
[I] vbsp: Editing Overlays...
[I] vbsp: Editing Triggers...
[I] vbsp: Collapsing goo triggers...
[I] vbsp: Done!
[I] vbsp: Editing Brush Entities...
[I] vbsp: Removing static indicator toggles...
[I] vbsp: Done!
[I] vbsp: Editing WorldSpawn
[I] vbsp: Making Pack list...
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3852, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 3449, in make_packlist
  File "F:\Git\BEE2.4\src\property_parser.py", line 278, in parse
  File "F:\Git\BEE2.4\src\property_parser.py", line 150, in read_flag
property_parser.KeyValError: Extra text after line: "models/props/light_rail_endcap2.mdl"
Error occured on line 107, with file "bee2/pack_list.cfg"


(KEEP CALM) My Pet Maicu unpaused the game
[

**Comment by Konclan** [comment]
Thank you, that is more helpful :3

**Comment by Juleder** [comment]
So what do I do.

**Comment by Konclan** [comment]
Are you using unstationary scaffolds?

**Comment by jccreszMinecraft** [comment]
This isn't anyone's fault. the compiler was changed and Teamspen probably
left in a line of code in the wrong place.

On Mon, May 2, 2016 at 8:31 PM, Juleder <notifications@github.com> wrote:

> So what do I do.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/BenVlodgi/BEE2.4/issues/306#issuecomment-216404077>
>



-- 
*-~=~-*
*Ice Network Entertainment Studios*
*-~=~-*

Chores in videogames are ridiculous!

**Comment by TeamSpen210** [comment]
Get the newest version of the packages, the original upload had corrupt config files.

**Comment by Juleder** [comment]
I did unless if I put them in the wrong place.

**Comment by TeamSpen210** [comment]
Did you get the pr20.5 version?

**Comment by Juleder** [comment]
Can you link it to me?

**Comment by Juleder** [comment]
Um hello?

**Comment by Juleder** [comment]
Although I do think I did.

**Comment by TeamSpen210** [comment]
https://github.com/TeamSpen210/BEE2-items/releases/tag/pr20.1

**Comment by Juleder** [comment]
Well it still didn't work :(.

**Comment by BenVlodgi** [comment]
Remove the BEE2.4
Then get the latest files, then try again

**Comment by Juleder** [comment]
Thanks BenVlodgi that actually worked!

**Comment by TheReviewers** [comment]
@Juleder Are You Keep Calm My Pet Maicu?

**Comment by BenVlodgi** [comment]
@Juleder glad it did, I was just guessing that you had outdated files that weren't overwritten, this was the solution to that

**Comment by Enterpise** [comment]
So..... Like Konclan would sayd..... This issue was solved, shouldn't this be closed now?

**Comment by Juleder** [comment]
@TheReviewers yes I am keep calm my pet maicu
