### ISSUE TITLE
Track Platform - Button Delay?

### ISSUE THREAD

**Issue by GLiTcH2** [BenVlodgi/BEE2.4#309]
I have a normal button hooked up to two track platforms, Before installing bee2.4 the button would activate the track platforms instantly however now it seems to have a several second delay before the platforms begin to move! Can this be changed?

**Comment by LautaroL20** [comment]
Ive already report this same bug some time ago: https://github.com/TeamSpen210/BEE2-items/issues/461

Id recommend you to post any issue related to items on the respective section: https://github.com/TeamSpen210/BEE2-items

**Comment by Konclan** [comment]
@LautaroL20 His issue is not that the platforms won't move, its that they take longer than usual to move. So it's not the same bug.

**Comment by TheReviewers** [comment]
@Konclan It Moves, Lautaro Just Didnt Observe it for a long time... it does take longer
