### ISSUE TITLE
Pre-Release 20 breaks hammer.

### ISSUE THREAD

**Issue by corrupt21** [BenVlodgi/BEE2.4#311]
![untitled](https://cloud.githubusercontent.com/assets/17777059/15013537/8e44acd4-1243-11e6-8478-7e3b12e254b9.png)
Now I cannot make hammer maps :(

**Comment by Konclan** [comment]
Are you trying to export maps from PeTI?

**Comment by corrupt21** [comment]
No, I am making an underground map from scratch.
I found out it is a bug in the python code :(

**Comment by BenVlodgi** [comment]
The BEE2.4 does override the compilers.
Its good to report these, but you want to restore you compilers back to default, you can verify your game cache

**Comment by TeamSpen210** [comment]
Go into Hammer's settings, and on the 'Build Programs' tab there's a file picker for the locations of VBSP and VRAD. Change the filename to `vbsp_original` and `vrad_original`. That will run the original compilers directly. 

This is still a bug - the compilers should correctly function when run in Hammer, not modifying the maps. (They will auto-pack files if you add a `map_name.filelist.txt` file in the same folder as the VMF).
