### ISSUE TITLE
1961 Typo

### ISSUE THREAD

**Issue by TheReviewers** [BenVlodgi/BEE2.4#312]
The description says '' makes it a good choice for stange testing elements '' 

'stange' is the typo btw :3 
i dont know how to screenshot it.. just look at it
@TeamSpen210 Pls Fix

**Comment by SpyyZ158** [comment]
@TheReviewers You could use Gyazo to screenshot it then download picture and post to to issue ;). Just suggestion for you.

**Comment by Konclan** [comment]
If you're on windows, there is a tool called Snipping Tool which allows you to highlight a certain part of a screen and save it as an image

**Comment by TheReviewers** [comment]
you can all just see it -.- if you look in the description

**Comment by TeamSpen210** [comment]
It's fixed now, anyway.

**Comment by Konclan** [comment]
Well I was just mentioning for future problems lol

**Comment by BenVlodgi** [comment]
you don't even have to save images to upload them
I use the snipping tool, then hit [Ctrl] + [C], and just paste it into this little box, and it uploads it right up

**Comment by Luke18033** [comment]
@TeamSpen210 Do you mean, "fixed for the next release"?

**Comment by Konclan** [comment]
Yes, that's what the tag means
