### ISSUE TITLE
Completely Unrelated Hammer Question

### ISSUE THREAD

**Issue by Konclan** [BenVlodgi/BEE2.4#313]
I normally wouldn't post questions like this but I cannot find the answer anywhere. I also know you guys respond quickly and are probably more proficient with hammer.

My question is how do you stop the player from spawning with a portal gun, I am using just a info_player_start and its giving me a portal gun without me using the weapon_portalgun. Any suggestions?

**Comment by jccreszMinecraft** [comment]
Don't have a weapon_portalgun entity anywhere near the info_player_start.

On Thu, May 5, 2016 at 11:14 AM, Konclan <notifications@github.com> wrote:

> I normally wouldn't post questions like this but I cannot find the answer
> anywhere. I also know you guys respond quickly and are probably more
> proficient with hammer.
>
> My question is how do you stop the player from spawning with a portal gun,
> I am using just a info_player_start and its giving me a portal gun without
> me using the weapon_portalgun. Any suggestions?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/BenVlodgi/BEE2.4/issues/313>
>



-- 
*-~=~-*
*Ice Network Entertainment Studios*
*-~=~-*

Chores in videogames are ridiculous!

**Comment by Konclan** [comment]
I don't, that's the confusing part

**Comment by TeamSpen210** [comment]
Surround the spawn area in a `trigger_weaponstrip`. That will take the gun away before thevplayer noticies. `OnStartTouch` `Disable` the trigger, then spawn in a portalgun if desired. (Use `RunScriptCodè on something with an argument of `give_portalgun()` to give the player a single-portal-device.)

**Comment by Konclan** [comment]
That didn't work for some reason, the trigger is removed but I still spawn with the gun... Do I need to surround the outside of the spawn?

**Comment by Konclan** [comment]
yeah putting the trigger under the player instead of inside worked, thanks for your help

**Comment by TheReviewers** [comment]
hope im not late...

**Comment by BenVlodgi** [comment]
> Konclan said
> yeah putting the trigger under the player instead of inside worked, thanks for your help

Yeah, I'm pretty sure you have to enter the trigger once the game starts for the weapon strip to work. (can't spawn in it)

**Comment by TeamSpen210** [comment]
For the BEE2.4 triggers, they're set to Start Disabled, and are then enabled by a ´logic_auto´.
