### ISSUE TITLE
Missing Packages -- Pre-release 20

### ISSUE THREAD

**Issue by MrKrunk** [BenVlodgi/BEE2.4#314]
![bugreport prerelease 20 1](https://cloud.githubusercontent.com/assets/17092818/15059322/befe1160-12d6-11e6-8a3e-811c0a7ae6f7.png)
There are only source code downloads available.

**Comment by BenVlodgi** [comment]
you're looking at a tag that broken items in it (or something), so that tag isn't to be used
just look at the latest Releases part of the page

https://github.com/TeamSpen210/BEE2-items/releases
https://github.com/TeamSpen210/BEE2-items/releases/tag/pr20.1

**Comment by TeamSpen210** [comment]
Specifically, I broke a script I'm using to create the final package zip - it made all the packlist config files filled extra quote charscters which broke all compile attempts.
