### ISSUE TITLE
Music Not Playing

### ISSUE THREAD

**Issue by Konclan** [BenVlodgi/BEE2.4#321]
A lot of the normal portal 2 music such as control group and Comedy = T + T plays a sound error when the map is published and played.

**Comment by Xorven** [comment]
+1
I have the same problem with 3 maps with the overgrown style.
The musics are Rexaura Six, Self-Esteem Fund and Technical Difficulties (so it doesn't work even with an overgrown style music).
When I'm testing it in the editor of course the music works, but after publishing it, it's over.

By the way, even if it's not the question here, signages with Portal 1 style don't work for me : there is the square around the signage, but there is nothing inside.

**Comment by Xorven** [comment]
Apparently, everyone have the same problem.
The only map I published without this issue has the music "Robot Ghost Story" with Overgrown style.

Other music used with the issue : 
- Overgrown style : Rexaura Two, Rexaura Five, Future Starter, Android Hell
- Clean style : I saw a Deer Today
