### ISSUE TITLE
Clean Style Texture Issue

### ISSUE THREAD

**Issue by GLiTcH2** [BenVlodgi/BEE2.4#322]
Not sure if this has been posted before but I just spotted this faint texture bug
![20160507101904_1](https://cloud.githubusercontent.com/assets/19172857/15093466/0646d936-143e-11e6-9fe7-20785e0a9563.jpg)

**Comment by Konclan** [comment]
What's the error?

**Comment by GLiTcH2** [comment]
If you look very close there is a faint texture of something else in the white tiles between where I am aiming, I see a number 8 at the top corner of the tile and what looks like 0008-2A? It's very strange..

**Comment by CrashingScience** [comment]
This is intentional. They are brand new panels printed with cerial number
ect.

**Comment by GLiTcH2** [comment]
Oh, anyway to just have plain panels... Kind of annoying.

**Comment by TeamSpen210** [comment]
It is indeed intentional, part of that tile variant.

**Comment by Luke18033** [comment]
@GLiTcH2 If you want plain panels then use Original Clean style.

**Comment by Luke18033** [comment]
Maybe @TeamSpen210 could add an option to remove this texture.

**Comment by GLiTcH2** [comment]
It would be nice to have an option to remove it but it's not a big deal, I will use the original clean style once I don't have this annoying bug which is far worse to look at lol: https://github.com/TeamSpen210/BEE2-items/issues/512
