### ISSUE TITLE
[Bug] If the Portal 2 Folder was moved, and then Bee2.4 is launched, beemod will not load anymore

### ISSUE THREAD

**Issue by LautaroL20** [BenVlodgi/BEE2.4#325]
Once Bee2.4 was installed and got associated to the Portal 2 folder, if you move the P2 folder to another place, and then launch beemod, it will crash and will close automatically to not load anymore, it doesn´t matter if you move back the P2 folder to the original place. You will have to re-install beemod again.

This bug happens in the latest pre-relase and the previous ones too.

**Comment by TheDarkBomber** [comment]
That is because you corrupted the GAME chosen on BEE2.4. You need to select it again as a different game. That will work.

**Comment by LautaroL20** [comment]
@TheDarkBomber - That would be not possible due the Bee UI will not open anymore. The re-install of Bee2.4 is the only alternative for this bug.

**Comment by LautaroL20** [comment]
Okay, i have tested this again this time using the Prl21.5 and seems to be fixed.
