### ISSUE TITLE
New Object (Text on wall)

### ISSUE THREAD

**Issue by Venima** [BenVlodgi/BEE2.4#327]
In one of my maps, there is a stuck prevention button. I want to make it clear to the player that this is its purpose. Is it in any way possible to have an object which sticks to a wall, with writing on it? I understand the ingame editor won't be able to edit this text but it could be entered in the BEE program and turned into a texture during exporting maybe? Using the 'button type' menu, could have up to 3 different writings in a chamber. This is probably a lot of work, but it would be pretty cool IMO.

**Comment by TeamSpen210** [comment]
It would be a lot of work - I'd need to write code to typeset the text into an image, convert it into Valve's VTF format, then generate a correctly-sized brush. I'll probably implement this as TeamSpen210/BEE2-Items#531, a button or something which shows the text as an on-screen overlay.
