### ISSUE TITLE
"Keep windows inside screen" and "Show Log window" toggle each other.

### ISSUE THREAD

**Issue by Luke18033** [BenVlodgi/BEE2.4#328]
When I turn on "Keep windows inside screen" in the BEE2 options, the "Show Log window" option is turned on. I turned off the "Show log window" option but then "Keep windows inside screen" turned off again. Basically, when toggling one of the settings, the other will switch to the same state.
![broken_options](https://cloud.githubusercontent.com/assets/19228201/15262480/82e0dc52-1917-11e6-91d2-fc611deb62bb.gif)

**Comment by Luke18033** [comment]
@TeamSpen210 Where does the options file save? I want to edit the file directly so I can have only "Keep windows inside screen" on.

**Comment by TeamSpen210** [comment]
It saves to `config/config.cfg` in the BEE2 folder. It might not affect anything, the bug is with the storying of the values in memory - they were both storing the setting in the same location.
