### ISSUE TITLE
BEE2.4?

### ISSUE THREAD

**Issue by Konclan** [BenVlodgi/BEE2.4#329]
This seems like a weird question, but why is BEE2.4 called BEE2.4 and not BEE3?

**Comment by TeamSpen210** [comment]
It's the BEE2, version 4. The BEE2, version 2.5 was the older version, and version 3 was a version made by Ben thar was not released.

**Comment by Luke18033** [comment]
@Konclan If you want to ask questions, use [Gitter](https://gitter.im/BenVlodgi/BEE2.4).
