### ISSUE TITLE
How to install on Mac?

### ISSUE THREAD

**Issue by Luke18033** [BenVlodgi/BEE2.4#330]
I am trying to install BEE2 on a mac. I have downloaded the mac files, put in the packages and run the "BEE2" executable, but this comes up:
<img width="596" alt="screen shot 2016-05-13 at 3 59 49 pm" src="https://cloud.githubusercontent.com/assets/19228201/15264021/c87f7866-1923-11e6-974f-78ab443cdbcf.png">
What should I do?

**Comment by Luke18033** [comment]
@TeamSpen210 I know EXE files don't work on mac, so I'm assuming the "executable" is the "BEE2" file in the bin folder which has the terminal as the icon. The programs I download for Mac are usually on Steam, an installer or a DMG.

**Comment by dunkler-schatten** [comment]
You must install Pyton Framework version 3.4 only version 3.4 
Then you must Drag and Drop the executable BEE2 into your Mac Terminal Window.
My English ist very bad sorry.

**Comment by dunkler-schatten** [comment]
Scroll Down to Files https://www.python.org/downloads/release/python-344/
You can use version 3.4 or 3.4.4 its the same vor BEE2
Any Question? Ask me. good luck.

**Comment by Luke18033** [comment]
This actually isn't my Mac, so I'd have to ask the owner about it.

**Comment by Luke18033** [comment]
@dunkler-schatten That worked, thanks.

**Comment by Ratatree** [comment]
Hi I am trying to install BEE2.4 ver23 on my mac I have followed the steps and all I get is “BEE2” is damaged and can’t be opened. You should move it to the Trash. can anyone help me?

**Comment by EmeraldShield99** [comment]
Hey i cant find the beemod executable could someone help me i am also on mac

**Comment by Luke18033** [comment]
There is no longer a Mac version, and do you realize how old this issue is?
