### ISSUE TITLE
Non-Portal 2 music does not work for me in maps published through the PeTI editor

### ISSUE THREAD

**Issue by CUBICinfinity** [BenVlodgi/BEE2.4#331]
I know others have talked about issues with the music files. My case is that I cannot get any of the music files from the packages folder to play in my published Portal 2 maps. I get the "oh, fiddlesticks" error. All of my files in the packages folder are zipped, but I have also tried extracting them and that did not change anything. I did not try every sound file. The ones I have tried are P1:4000 Kevlin, Tag:Confrontation, and my own .wav file.

Edit: Oh, actually the Machiavellian Bach (which _is_ a P2 track and is in the Wheatley folder) one failed too, but I was using it in the 1970s theme. I don't know if that would change anything.

**Comment by Luke18033** [comment]
@TeamSpen210 must have forgotten to bundle the music with the map when piblishing. Now that (He? She? They?) has been mentioned, @TeamSpen210 should see this.

**Comment by Luke18033** [comment]
@TeamSpen210 must have forgotten to bundle the music with the map when publishing. Now that (He? She? They?) has been mentioned, @TeamSpen210 should see this.
