### ISSUE TITLE
Reflective cube dropper - Auto-Respawning system doesn't work.

### ISSUE THREAD

**Issue by Xorven** [BenVlodgi/BEE2.4#333]
When I enter the chamber, the first reflective cube is dropped. But when I destroy it, the dropper doesn't want to drop me another one.
Note : This issue happens only with the reflective cube, not for the other cubes.

**Comment by Luke18033** [comment]
Please post anything related to items in TeamSpen210/BEE2-items.

**Comment by libbybapa** [comment]
I have the same issue.  Reflective cube won't re-spawn.  I checked and the Standard cube will re-spawn.  The Reflective cube re-spawned fine with release 19, but not 20.

**Comment by LautaroL20** [comment]
Ive already reported this bug on the TeamSpen210/BEE2-items section, some time ago.

**Comment by BenVlodgi** [comment]
@LautaroL20 link to issue?

**Comment by libbybapa** [comment]
https://github.com/TeamSpen210/BEE2-items/issues/555  I reverted back to 19 for now because the map I was working on had re-spawning a reflective cube as part of the solution.

**Comment by LautaroL20** [comment]
@BenVlodgi https://github.com/TeamSpen210/BEE2-items/issues/529

**Comment by libbybapa** [comment]
Lautaro, that's not the same issue although perhaps related.
