### ISSUE TITLE
Old Aperture catwalk stair handrails not connecting

### ISSUE THREAD

**Issue by TheReviewers** [BenVlodgi/BEE2.4#334]
http://steamcommunity.com/sharedfiles/filedetails/?id=684973667

**Comment by Konclan** [comment]
This doesn't seem to be the correct screenshot

**Comment by TheReviewers** [comment]
@Konclan Whoops

**Comment by Luke18033** [comment]
So...where's the right one?

**Comment by Luke18033** [comment]
You should post things related to styles at TeamSpen210/BEE2-items.

**Comment by TheReviewers** [comment]
Steam is down for maintenance in my country, cant access store, screenshots, community or anything   :(

**Comment by Luke18033** [comment]
@TheReviewers I was able to look at your list of screenshots, is it the one of the tiny break in the railing?

**Comment by TheReviewers** [comment]
Yes

**Comment by Luke18033** [comment]
That just looks like a bug with the model.

**Comment by xDadiKx** [comment]
This is it then.
You can edit the description with the right screenshot, the link is right below my text.
http://steamcommunity.com/sharedfiles/filedetails/?id=684973667

**Comment by TeamSpen210** [comment]
The problem is that the stair models all have an inbuilt end piece, so they don't actually connect to other catwalk models. I'll switch it to a custom model.

**Comment by Luke18033** [comment]
@TeamSpen210 Shouldn't this be on BEE2-items?

**Comment by TeamSpen210** [comment]
This issue was moved to TeamSpen210/BEE2-items#573
