### ISSUE TITLE
Hammer - Compiler can't find some instances

### ISSUE THREAD

**Issue by Xorven** [BenVlodgi/BEE2.4#336]
When I tried to compile my map, I had this error first : 

> materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
Loading c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\the_ultimate_repulsion_gel.vmf
ConVarRef gpu_level doesn't point to an existing ConVar
Could not open instance file instances/BEE2/clean/items/barrier/segment.vmf

I found a segment.vmf in p1/items/barrier/ so I copied it and pasted it in /clean/items/barrier/.
But now I have this error : 

> materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
Loading c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\the_ultimate_repulsion_gel.vmf
ConVarRef gpu_level doesn't point to an existing ConVar
Could not open instance file instances/BEE2/clean/items/button/weighted_black.vmf

There is no "weighted_black.vmf" in my PC. What can I do ?

**Comment by TheReviewers** [comment]
@Xorven Good to see that you started using github again :D

**Comment by TeamSpen210** [comment]
If you're wanting to edit BEE2.4 maps in hammer, don't use `puzzlemaker_export`; it doesn't run the precompiler, so the maps will be wrong. (Those instances aren't supposed to exist, they're replaced by others.) Turn on 'start in elevator' on the Compiler pane, compile the map, then you can edit `maps/styled/preview.vmf`. There's also files you'll need to pack as well, listed in `maps/styled/preview.filelist.txt`.

**Comment by BenVlodgi** [comment]
Do you think there should be an item, or parameter set in the vmf to run the BEE2.4's custom compiler operations even if compiling from hammer?

**Comment by TeamSpen210** [comment]
There is, actually. You can add the parameters `-force_peti` or `-force_hammer` to make VBSP or VRAD run in that mode. Putting options in the VMF isn't something I'd like to do - parsing the map actually takes a substantial amount of time to do, and `vmfLib` doesn't support all of the VMF format (visgroups mainly).

**Comment by BenVlodgi** [comment]
could this be something you include in all pti maps, so when people run the export command, those maps can compile?

**Comment by TeamSpen210** [comment]
That's a command-line argument to VBSP and VRAD, not part of the map. The export command is all internal to Portal 2 - no compilers get invoked at all. I do want to keep the conversion from Hammer explicit though - running the compiler on non-PeTI maps or modified ones will probably break assumptions made in the code, or generate invalid maps.

**Comment by BenVlodgi** [comment]
You wouldn't have to parse the whole map. Instead, just search for some specific instance/property.
Though I suppose that would open a new can of worms.
Though, does this mean people can create new compiler settings and add `-force_peti` to the VBSP and VRAD calls?
