### ISSUE TITLE
Allow escaping " in Property files

### ISSUE THREAD

**Issue by Luke18033** [BenVlodgi/BEE2.4#338]
When attempting to backup/restore puzzles for Aperture Tag, I get this message:

![image](https://cloud.githubusercontent.com/assets/19228201/15590473/dba7624a-234c-11e6-9dcb-f94c99dc99d3.png)

[Here](https://steamcommunity.com/sharedfiles/filedetails/?id=649560048) is the chamber which I think is causing the problem.

I am still able to backup Portal 2 puzzles, this only happens with Aperture Tag.

**Comment by TeamSpen210** [comment]
The bug is specifically with the " characters in the file - I'll need to allow using  `\"` to escape them..

**Comment by Luke18033** [comment]
@TeamSpen210 Actually, it should have the Crash label because it crashes the BEE2.

**Comment by TeamSpen210** [comment]
True. There's kind of 2 issues here - 1 is the quote parsing failure, and the other is that the 'invalid' map file crashes the backup program.

**Comment by Luke18033** [comment]
Ah, so this is fixed now.
