### ISSUE TITLE
[Bug] When viewing the Tags menu, the items will move down but not the scrollbar.

### ISSUE THREAD

**Issue by Luke18033** [BenVlodgi/BEE2.4#342]
When the Tags menu is opened, all of the items shown below will move down to prevent being blocked by the Tags menu, but the scrollbar won't.

GIF:
![tag_menu_bee2](https://cloud.githubusercontent.com/assets/19228201/15655090/b821f6fa-264e-11e6-8100-c912fa6f8c0a.gif)

**Comment by TeamSpen210** [comment]
I could change that, but you wouldn't be able to use the scrollbar anyway - since you can't move the mouse off the tags pane.

**Comment by Luke18033** [comment]
But wait...did you see how screwy the items looked when I was scrolling?

**Comment by xDadiKx** [comment]
It doesn't really matter how screwy they are, for me that doesn't happen tho.

**Comment by TeamSpen210** [comment]
I don't think the item smearing in the canvas widget is something I can fix.

**Comment by Luke18033** [comment]
Are you sure?
