### ISSUE TITLE
[Stylevar] Fullbright Mode

### ISSUE THREAD

**Issue by Luke18033** [BenVlodgi/BEE2.4#346]
A stylevar which makes the map fullbright, this would remove the light entities from observation rooms, light strips, and any other light-emitting items. An invisible light, for non-fullbright maps, would also be useful, but that's for another issue.

**Comment by CrashingScience** [comment]
But fullbright looks awful. Everything just becomes white and glaring

**Comment by Luke18033** [comment]
Fullbright does look pretty bad, but it's really annoying having to put light strips everywhere, especially in P1, where light holes don't seem to emit much light.
@TeamSpen210 Another fix for this: Invisible Light Source.

**Comment by TeamSpen210** [comment]
Type `bindtoggle o mat_fullbright`, then the 'o' key will toggle fullbright mode. If I added such a stylevar, it would be disabled when publishing maps - fullbright isn't suitable for releases.

**Comment by TheReviewers** [comment]
@TeamSpen210 Why did you add enhancment?

**Comment by CrashingScience** [comment]
As for lighting problems, the large ceiling light could be useful

**Comment by Luke18033** [comment]
Or an invisible light...

**Comment by Luke18033** [comment]
Or an invisible light...

**Comment by Luke18033** [comment]
Woops, wrong button.

**Comment by Luke18033** [comment]
@BenVlodgi @TeamSpen210  What if it was just for preview mode and would be disabled when the map was published?

**Comment by TheReviewers** [comment]
@Luke18033 Then people wont see anything when its published

**Comment by BenVlodgi** [comment]
@Luke18033 then what would be the point?
you can toggle fullbright mode for your self any time you want.

**Comment by Luke18033** [comment]
While playing the old Portal Project Beta, I realized that the final map was fulbright and realized how ugly it looks.
