### ISSUE TITLE
Black ceiling in "Original Clean" style appears bright white, is portalable

### ISSUE THREAD

**Issue by AdmiralPancakes1** [BenVlodgi/BEE2.4#348]
Screenshots from editor and chamber
![20160611182513_1](https://cloud.githubusercontent.com/assets/19880843/15987919/fcec14a2-3001-11e6-8254-b3787a81300d.jpg)
![20160611182555_1](https://cloud.githubusercontent.com/assets/19880843/15987920/0072378c-3002-11e6-810c-9d67993c7165.jpg)

**Comment by LautaroL20** [comment]
This is a duplicate of https://github.com/TeamSpen210/BEE2-items/issues/512
