### ISSUE TITLE
AttributeError on rearranging palette (Mac OSX)

### ISSUE THREAD

**Issue by microlith57** [BenVlodgi/BEE2.4#349]
On my MacMini with BEE 2.4 open, when I attempt to rearrange my palette, the icons flicker and then a dialog appears detailing an AttributeError:

`AttributeError: AttributeError("'NoneType' object has no attribute 'clear'",)`

Can I fix this? I will be happy to respond to diagnostic questions.

Thanks,
Microlith57

**Comment by TeamSpen210** [comment]
Open `BEE2.4/logs/bee2.log`, and copy-paste the last lines of it here, or rename to a `txt` file and drag into the comment system.

**Comment by microlith57** [comment]
[BEE2.txt](https://github.com/BenVlodgi/BEE2.4/files/311259/BEE2.txt)

Here you are. I am familiar with Python myself so will attempt to dissect the error.

Thanks!

**Comment by microlith57** [comment]
It appears to be an error with __draw__() in tinter that occurs twice in two separate places.
