### ISSUE TITLE
"There was an error building the puzzle"

### ISSUE THREAD

**Issue by Emma-Walker** [BenVlodgi/BEE2.4#351]
After installing pr20 I get "There was an error building the puzzle" when I press F9 (rebuild puzzle) in the Puzzle Maker. 

Even with completely empty puzzles: File -> New Chamber -> F9 -> "There was an error building the puzzle"

**Comment by TeamSpen210** [comment]
Open the dev console and copy the error in there.

**Comment by Emma-Walker** [comment]
Please note that this Error still appears after I deinstalled BEE2 (File-->Remove Selected Game).

[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 37 (ms)

VBSP failed.

vbsp_styles: Starting style Changer VBSP hook.
vbsp_styles: Elevators (hold ctrl): False
vbsp_styles: commandline: " -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/""
vbsp_styles: filename: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
vbsp_styles: game: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/"
vbsp_styles: limit: 1750
vbsp_styles: Saved modified C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\styled\preview.vmf
vbsp_styles: Changed 0 materials.
vbsp_styles: -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\styled\preview.vmf"
vbsp_styles: Launching and waiting for "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" with commandline "-game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\styled\preview.vmf""
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in <module>
zipimport.ZipImportError: can't find module 'vbsp_original__main__'
vbsp_styles: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" finished.
vbsp_styles: Packing because RunBspZip is set to 1 in editoritems.txt
vbsp_styles: Making C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/\puzzles\76561198001362169\untitled.jpg writable

**Comment by Emma-Walker** [comment]
I tried with pr20 and pr18

**Comment by TeamSpen210** [comment]
Delete the vbsp and vrad files in `Portal 2/bin/`, then verify your cache and export again. They're very mixed up

**Comment by Emma-Walker** [comment]
OK, works now.

**Comment by Blacksilver42** [comment]
I have the same problem; the workaround worked. If you can't find the actual problem, perhaps add a button to automagically delete `vbsp.exe` and `vrad.exe`, verify game files, and re-export?

**Comment by Blacksilver42** [comment]
Welp, I added a *single trigger once* to an existing puzzle and now nothing works.

Here's the error in the console:

```
VBSP failed.

Valve Software - vbsp.exe (Aug 26 2015)
8 threads
materialPath: M:\SteamLibrary\steamapps\common\Portal 2\portal2\materials
Loading M:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps/preview.vmf
ConVarRef gpu_level doesn't point to an existing ConVar
Could not open instance file instances/BEE2/clean/items/barrier/segment.vmf

```

**Comment by GuyInGrey** [comment]
I have the same problem with trying to export my map, any fix?

**Comment by ThePootisBird** [comment]
i have same problem, AND I WILL NEVER USE BEEMOD AGAIN

**Comment by Luke18033** [comment]
Why not? I was trying to help you fix the error...

**Comment by ThePootisBird** [comment]
can u plz tell me how to fix error cuz i think i f*cked my self with it

**Comment by GuyInGrey** [comment]
I have a fix that worked for me:
I had a logic gate that was outside of the map, try that.

**Comment by Luke18033** [comment]
First we need to know what the dev console error was, post that on the issue you opened by doing what Endermage said.

**Comment by TeamSpen210** [comment]
You need to post the actual error, there's hundreds of ways it could happen.

**Comment by GuyInGrey** [comment]
Triggers or logic gates being outside of the map will cause this. That's what was causing the problem for me.

**Comment by Luke18033** [comment]
There are a lot of other things that could cause it as well, including the fact that some people just randomly get errors for no reason.

**Comment by Pucmeloud1380** [comment]
I have problem with BEE mod:
VBSP failed.

[I] vbsp.main(): BEE2.4.0pr31 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "D:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "D:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): Clearing inject/ directory..
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] vbsp_options.load(): Extra config options: {'bottomless_pit': '0', 'use_screenshot': '1', 'glass_scale': '0.15', 'voice_pack': 'BEE2_GLADOS_CLEAN'}
[W] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common': 'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})
[W] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common': 'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})
[I] cubes.parse_conf(): Parsed 0 cube types, 0 dropper types and 0 addons.
[W] cubes.parse_conf(): Valve Cube type "VALVE_CUBE_STANDARD" is missing!
[W] cubes.parse_conf(): Valve Cube type "VALVE_CUBE_COMPANION" is missing!
[W] cubes.parse_conf(): Valve Cube type "VALVE_CUBE_REFLECTION" is missing!
[W] cubes.parse_conf(): Valve Cube type "VALVE_CUBE_SPHERE" is missing!
[W] cubes.parse_conf(): Valve Cube type "VALVE_CUBE_FRANKEN" is missing!
[I] fizzler.read_configs(): Loaded 0 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Using random SP Exit (1)
[I] vbsp.mod_entryexit(): Using random SP Entry (7)
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (11 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] cond.core.check_all(): Checking Conditions...
[I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[I] connections.gen_item_outputs(): Generating item IO...
[I] connections.gen_item_outputs(): Item IO generated.
[I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[I] vbsp.set_elev_videos(): Elevator type: FORCE
[I] voiceLine.add_voice(): Adding Voice Lines!
[W] BEE2_config.load(): Config "bee2\voice.cfg" not found! Using defaults...
[W] BEE2_config.load(): Config "bee2\mid_voice.cfg" not found! Using defaults...
[I] voiceLine.add_voice(): Adding Base instance!
[I] voiceLine.add_voice(): Quote events: []
[I] voiceLine.add_voice(): No responses data..
[I] voiceLine.find_group_quotes(): "ENTRY": 1/15 quotes..
[I] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "GENERIC_1"
 | 	"choreo" "scenes/npc/glados/a2_triple_laser01.vcd"
 | 	}
 | 
 |___

[I] voiceLine.find_group_quotes(): "EXIT": 1/5 quotes..
[I] voiceLine.add_quote(): Adding quote: "Line_SP"
 | 	{
 | 	"ID" "GENERIC_2"
 | 	"Choreo" "scenes/npc/glados/dlc1_leaderboard01.vcd"
 | 	}
 | 
 |___

[I] voiceLine.find_group_quotes(): "MIDCHAMBER": 0/9 quotes..
[I] voiceLine.add_voice(): 0 Mid quotes
[I] voiceLine.add_voice(): Done!
[I] vbsp.set_player_portalgun(): Setting Portalgun:
[I] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[I] vbsp.set_player_portalgun(): Done!
[I] cond.core.check_all(): Map has attributes: ['spawn_dual']
[I] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=2878, misses=319, maxsize=256, currsize=256)
[I] cond.core.check_all(): Style Vars: {'blockplayergelbomb': True, 'doorcameras': False, 'restartonexit': False, 'multiversecave': False, 'fixfizzlerbump': False, 'nomidvoices': False, 'unlockdefault': False, 'allowgoomist': False, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True}
[I] cond.core.check_all(): Global instances: {'instances/BEE2/clean/global_ents.vmf'}
[I] vbsp.add_extra_ents(): Adding Music...
[I] vbsp.add_extra_ents(): Adding global ents...
[I] vbsp.add_extra_ents(): Adding Global PTI Ents
[I] vbsp.change_ents(): Editing Other Entities...
[I] vbsp.fixup_goo_sides(): Changing goo sides...
[I] vbsp.fixup_goo_sides(): Done!
[I] vbsp.change_brush(): Editing Brushes...
[I] vbsp.change_brush(): Make Bottomless Pit: False
[I] vbsp.change_brush(): Goo heights: 0 <- Counter()
[I] vbsp.change_overlays(): Editing Overlays...
[I] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[I] vbsp.collapse_goo_trig(): Done!
[I] vbsp.change_func_brush(): Editing Brush Entities...
[E] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3190, in main
  File "F:\Git\BEE2.4\src\barriers.py", line 153, in make_barriers
  File "F:\Git\BEE2.4\src\template_brush.py", line 574, in get_scaling_template
template_brush.InvalidTemplateName: Template not found: "bee2_glass_template"
Valid templates:
 * "__TILING_TEMPLATE__"
 * "BEE2_ANGLED_BLOCK_30"
 * "BEE2_ANGLED_BLOCK_45"
 * "BEE2_ANGLED_BLOCK_60"
 * "BEE2_ANGLED_BLOCK_CORNER_30"
 * "BEE2_ANGLED_BLOCK_CORNER_45"
 * "BEE2_ANGLED_BLOCK_CORNER_60"
 * "BEE2_BALL_BUTTON_BASE_BTS"
 * "BEE2_BALL_BUTTON_BASE_P1_WHITE"
 * "BEE2_BLOCK_128_32_32"
 * "BEE2_BLOCK_128_64_64"
 * "BEE2_BLOCK_64_64_64"
 * "BEE2_BLOCK_WINDOW_FULL"
 * "BEE2_BLOCK_WINDOW_LOW"
 * "BEE2_BLOCK_WINDOW_MID"
 * "BEE2_BTS_GRATING_TEMPLATE"
 * "BEE2_CONVEYOR_COVER_BOTTOM_CLEAN"
 * "BEE2_CONVEYOR_COVER_BOTTOM_OVER"
 * "BEE2_CONVEYOR_COVER_BOTTOM_PORTAL_1"
 * "BEE2_CONVEYOR_COVER_RETRO"
 * "BEE2_CONVEYOR_COVER_TOP_CLEAN"
 * "BEE2_CONVEYOR_COVER_TOP_OVER"
 * "BEE2_CONVEYOR_COVER_TOP_PORTAL_1"
 * "BEE2_CONVEYOR_RAIL_RETRO"
 * "BEE2_CONVEYOR_TUNNEL_TILE_CLEAN"
 * "BEE2_CUBE_BUTTON_BASE_BTS"
 * "BEE2_CUBE_DROPPER_CLEAN_CAP"
 * "BEE2_CUTOUT_TILE_FLOOR_PILLAR"
 * "BEE2_CUTOUT_TILE_FLOOR_SIDE_DETAIL"
 * "BEE2_CUTOUT_TILE_FLOOR_SIDE_WORLD"
 * "BEE2_DYNAMIC_PAN_ANGLED_P1"
 * "BEE2_EMBEDDED_VOXEL"
 * "BEE2_FLAT_HALF"
 * "BEE2_FLAT_QUARTER"
 * "BEE2_FLAT_THREE_QUARTER"
 * "BEE2_FLOOR_BUTTON_BASE_BTS"
 * "BEE2_FLOOR_BUTTON_BASE_CLEAN_BALL"
 * "BEE2_FLOOR_BUTTON_BASE_CLEAN_CUBE"
 * "BEE2_FLOOR_BUTTON_BASE_CLEAN_WEIGHTED"
 * "BEE2_FLOOR_BUTTON_BASE_P1_WHITE"
 * "BEE2_FUTBOL_SURF_BACK"
 * "BEE2_FUTBOL_SURF_BACK_50S"
 * "BEE2_FUTBOL_SURF_BACK_P1"
 * "BEE2_GLASS_DOOR_CLEAN"
 * "BEE2_GLASS_DOOR_RETRO"
 * "BEE2_HALF_PANEL_TOP_50S"
 * "BEE2_HALF_PANEL_TOP_80S"
 * "BEE2_HALF_PANEL_TOP_CLEAN"
 * "BEE2_HALF_PANEL_TOP_P1"
 * "BEE2_HMW_SENDTOR_BASE_SLAB"
 * "BEE2_HMW_SENDTOR_BASE_SLAB_OVER"
 * "BEE2_HMW_SENDTOR_TOP_SLAB_P1"
 * "BEE2_MONITOR_COVER_CLEAN"
 * "BEE2_MONITOR_COVER_P1"
 * "BEE2_NEUROTOXIN_TIMER_COVER_CLEAN"
 * "BEE2_NEUROTOXIN_TIMER_COVER_OVER_LEFT"
 * "BEE2_NEUROTOXIN_TIMER_COVER_OVER_RIGHT"
 * "BEE2_NEUROTOXIN_TIMER_COVER_P1"
 * "BEE2_NEUROTOXIN_VENT_50S"
 * "BEE2_NEUROTOXIN_VENT_CLEAN"
 * "BEE2_NEUROTOXIN_VENT_P1"
 * "BEE2_OVER_BALL_BUTTON_BASE"
 * "BEE2_OVER_CUBE_BUTTON_BASE"
 * "BEE2_OVER_FLOOR_BUTTON_BASE"
 * "BEE2_OVER_PED_BASE"
 * "BEE2_OVER_STAIRS_TOP_1"
 * "BEE2_OVER_STAIRS_TOP_2"
 * "BEE2_OVER_STAIRS_TOP_3"
 * "BEE2_OVER_STAIRS_TOP_4"
 * "BEE2_P1_DRAWBRIDGE_DOWN"
 * "BEE2_P1_DRAWBRIDGE_UP"
 * "BEE2_P1_GLASS_BEAM"
 * "BEE2_P1_GLASS_TEMPLATE"
 * "BEE2_P1_GRATING_TEMPLATE"
 * "BEE2_RETRO_MECH_PLATE_ANGLED"
 * "BEE2_RETRO_MECH_PLATE_STRAIGHT"
 * "BEE2_ROCKET_TURRET_CAP_CLEAN"
 * "BEE2_SIGNAGE_50S_ARROW"
 * "BEE2_SIGNAGE_50S_ARROW_REV"
 * "BEE2_SIGNAGE_50S_EXIT"
 * "BEE2_SIGNAGE_50S_EXIT_REV"
 * "BEE2_SIGNAGE_50S_EXIT_WALL"
 * "BEE2_SIGNAGE_50S_NUM"
 * "BEE2_SIGNAGE_50S_NUM_REV"
 * "BEE2_SIGNAGE_50S_NUM_WALL"
 * "BEE2_SIGNAGE_50S_SIGN"
 * "BEE2_SIGNAGE_50S_SIGN_REV"
 * "BEE2_SIGNAGE_50S_SIGN_WALL"
 * "BEE2_SIGNAGE_70S_ARROW"
 * "BEE2_SIGNAGE_70S_ARROW_REV"
 * "BEE2_SIGNAGE_70S_ARROW_WALL_REV"
 * "BEE2_SIGNAGE_70S_SIGN2_FLOOR"
 * "BEE2_SIGNAGE_70S_SIGN2_FLOOR_REV"
 * "BEE2_SIGNAGE_70S_SIGN_FLOOR"
 * "BEE2_SIGNAGE_70S_SIGN_REV"
 * "BEE2_SIGNAGE_70S_SIGN_WALL"
 * "BEE2_SIGNAGE_BTS_ARROW"
 * "BEE2_SIGNAGE_BTS_ARROW_REV"
 * "BEE2_SIGNAGE_BTS_LONG"
 * "BEE2_SIGNAGE_BTS_LONG_REV"
 * "BEE2_SIGNAGE_BTS_NUM"
 * "BEE2_SIGNAGE_BTS_NUM_REV"
 * "BEE2_SIGNAGE_BTS_RECT"
 * "BEE2_SIGNAGE_BTS_RECT_REV"
 * "BEE2_SIGNAGE_CLEAN_ARROW"
 * "BEE2_SIGNAGE_CLEAN_ARROW_REV"
 * "BEE2_SIGNAGE_CLEAN_ARROW_WALL_REV"
 * "BEE2_SIGNAGE_CLEAN_SIGN2_FLOOR"
 * "BEE2_SIGNAGE_CLEAN_SIGN2_FLOOR_REV"
 * "BEE2_SIGNAGE_CLEAN_SIGN_FLOOR"
 * "BEE2_SIGNAGE_CLEAN_SIGN_REV"
 * "BEE2_SIGNAGE_CLEAN_SIGN_WALL"
 * "BEE2_STAIRS_TOP"
 * "BEE2_STATIC_PAN_ANGLED"
 * "BEE2_STATIC_PAN_ANGLED_BLACK_50S"
 * "BEE2_STATIC_PAN_ANGLED_BLACK_70S"
 * "BEE2_STATIC_PAN_ANGLED_BLACK_80S"
 * "BEE2_STATIC_PAN_ANGLED_BTS"
 * "BEE2_STATIC_PAN_ANGLED_P1"
 * "BEE2_STATIC_PAN_ANGLED_WHITE_50S"
 * "BEE2_STATIC_PAN_ANGLED_WHITE_80S"
 * "BEE2_STATIC_PAN_FLAT"
 * "BEE2_STATIC_PAN_FLAT_P1"
 * "BEE2_STATIC_PAN_FLAT_RETRO"
 * "BEE2_STATIC_STAIRS_CLEAN_EXTENDED"
 * "BEE2_STATIC_STAIRS_CLEAN_RETRACTED"
 * "BEE2_STATIC_STAIRS_STATIC_BEAMS_OVER"
 * "BEE2_STATIC_STAIRS_STATIC_BEAMS_TEMP"
 * "BEE2_TBEAM_FRAME"
 * "BEE2_TRACK_PLAT_BOTTOM"
 * "BEE2_TRACK_PLAT_MIDDLE"
 * "BEE2_TRACK_PLAT_SINGLE"
 * "BEE2_TRACK_PLAT_TOP"
 * "BEE2_TURRET_DROPPER_50S_CAP"
 * "BEE2_TURRET_DROPPER_P1_CAP"
 * "BEE2_VACTUBE_CORNER_CLEAN_LARGE"
 * "BEE2_VACTUBE_CORNER_CLEAN_MEDIUM"
 * "BEE2_VACTUBE_CORNER_CLEAN_SMALL"
 * "BEE2_VACTUBE_CORNER_RETRO_MEDIUM"
 * "BEE2_WALL_HALF"
 * "BEE2_WALL_HALF_CENTER"
 * "BEE2_WALL_PLUS"
 * "BEE_DOOR_COWL_CLEAN"
 * "BEE_DRAW_BRIDGE_CLEAN"
 * "BEE_DRAW_BRIDGE_OVER"
 * "BEE_HEP_CATCHER_BASE_CLEAN"
 * "BEE_HEP_CATCHER_BASE_P1_EXTENDED"
 * "BEE_HEP_CATCHER_BASE_P1_FLAT"
 * "BEE_HEP_CATCHER_BASE_P1_PISTON"
 * "BEE_HEP_EMITTER_BASE_CLEAN"
 * "BEE_HEP_EMITTER_BASE_P1"
 * "BEE_HEP_EMITTER_BASE_P1_SIGN"
 * "BEE_PGUN_BASE"
 * "BEE_VENT_BASE_50S"
 * "BEE_VENT_BASE_CLEAN"
 * "LAUTARO_PROTRUDING_PED_BASE_80S"
 * "LAUTARO_PROTRUDING_PED_BASE_BTS_BLACK"
 * "LAUTARO_PROTRUDING_PED_BASE_BTS_BLACK_REV"
 * "LAUTARO_PROTRUDING_PED_BASE_BTS_WHITE"
 * "LAUTARO_PROTRUDING_PED_BASE_BTS_WHITE_REV"
 * "LAUTARO_PROTRUDING_PED_BASE_CLEAN"
 * "LAUTARO_PROTRUDING_PED_BASE_OVER"
 * "LAUTARO_PROTRUDING_PED_BASE_P1"
 * "LAUTARO_PROTRUDING_PED_BASE_RETRO"
 * "REX_CUBE_DEFLECTOR_TEMP_CLEAN"
 * "REX_CUBE_DEFLECTOR_TEMP_P1"
 * "REX_CUBE_DEFLECTOR_TEMP_RETRO_METAL"
 * "REX_CUBE_DEFLECTOR_TEMP_RETRO_WOOD"
 * "REX_PELLET_FIELD_TEMP"
 * "REX_PELLET_FIELD_TEMP_RETRO"
 * "TSPEN_BTN_PED_CLEAN_BASE"
 * "TSPEN_BTN_PED_P1_BASE"
 * "TSPEN_CHAMBERLOCK_CLEAN"
 * "TSPEN_CHAMBERLOCK_P1"
 * "TSPEN_LARGE_FAITH_RETRO_BORDER"
 * "TSPEN_LARGE_FAITH_RETRO_MECH_BACK"
 * "TSPEN_LARGE_FAITH_TRIG"
 * "TSPEN_LARGE_FAITH_TRIG_SQUARE"
 * "WOM_CONDUCTOR_50S_BLACK"
 * "WOM_CONDUCTOR_50S_WHITE"
 * "WOM_CONDUCTOR_CLEAN"
 * "WOM_CONDUCTOR_P1"
