### ISSUE TITLE
Pre - Release 21 Not Starting?

### ISSUE THREAD

**Issue by GLiTcH2** [BenVlodgi/BEE2.4#353]
So not sure what's going on, I saw Pre - Release 21 came out and I downloaded it and the items packages, set it up exactly in the same spot as Pre - Release 20 which was working fine but anytime I try to run BEE2.exe it shows up in the task manager as if starting and then closes. No errors or any UI pop up on the screen it just seems like the process terminates within seconds. Any advice?

Edit - Redownloaded Pre - Release 20 and it's working flawlessly, So I am guessing there is a problem with 21?

**Comment by TeamSpen210** [comment]
Open `BEE2.4/logs/BEE2.log`, and copy it here.

**Comment by GLiTcH2** [comment]
The log is completely blank....
