### ISSUE TITLE
[Bug] Windows SmartScreen and antivirus think Pr21 is malware

### ISSUE THREAD

**Issue by Luke18033** [BenVlodgi/BEE2.4#355]
When running Pr20 or earlier, it runs with no problems, but for some reason when I run Pr21 Windows SmartScreen "protects" my computer by not allowing me to run the app, my antivirus also tries to scan BEE2 when I tell SmartScreen to launch the program anyway.

After the scan, BEE2 will not launch, even if I try to re-open it. Probably related to #354

**Comment by TeamSpen210** [comment]
I'm not sure why that would happen, I can't really do anything about it.
