### ISSUE TITLE
PR 21.5 not for 32-bit?

### ISSUE THREAD

**Issue by QuantiX999** [BenVlodgi/BEE2.4#359]
It says: "Cannot launch this app on your computer". Is it for 32-bit systems?

**Comment by xDadiKx** [comment]
I got a 64bit computer, so it should be working.
Where did you place your BEEMod File?

**Comment by QuantiX999** [comment]
In my Portal 2 folder (Steam version).

**Comment by xDadiKx** [comment]
Copy and Paste the text from the BEE2.log files located

**Comment by QuantiX999** [comment]
I deleted BEE, please wait :/

**Comment by QuantiX999** [comment]
Um, sorry, but where can I find .log file? :P

**Comment by xDadiKx** [comment]
In the logs folder?

**Comment by QuantiX999** [comment]
But there is no logs folder in BEE2 folder!

**Comment by xDadiKx** [comment]
Did you run bee2?

**Comment by QuantiX999** [comment]
I CANNOT run it. I'm on Win10. 32-it. It says: "Cannot run this app on your PC", if I'm translating correctly.

**Comment by xDadiKx** [comment]
Did other **pre-releases** work for you?

**Comment by QuantiX999** [comment]
PR 20 worked. 21 and 21.5 don't.

**Comment by xDadiKx** [comment]
Strange, I ran out of ideas, maybe TeamSpen or Ben can help you.

**Comment by QuantiX999** [comment]
This "Can't run this app" message usually appears when your system is not 32 or 64-bit, depending on the app. I think it's only for 64-bit systems.

**Comment by GLiTcH2** [comment]
I can confirm that PR21.5 is 64-bit only.

**Comment by QuantiX999** [comment]
Wanna fix it, TeamSpen?

**Comment by Enterpise** [comment]
@QuantiX999 Ehmmm...... We are in 2016 dude, idk how you were able to open the web browser on that system, if your Computer is really 32Bit, just grab it and throw it into the garbage. You can get a fine 64Bit PC for a cheap price these days.

**Comment by GLiTcH2** [comment]
@Enterpise Doesn't matter that @QuantiX999 doesn't have a 64-Bit system, The point was BEE was working for 32-Bit systems before and now is not which as we see from the label is a bug.

**Comment by BenVlodgi** [comment]
#391 
> TeamSpen210: I'm switching back to 32-bit
