### ISSUE TITLE
The filters get cut off

### ISSUE THREAD

**Issue by BenVlodgi** [BenVlodgi/BEE2.4#36]
Problem: The filters get cut off
Possible solution: let the menu extend as far as it needs to to the right, even off the interface

**Comment by TeamSpen210** [comment]
I'm planning on replacing that with something that actually scales, like a textbox which lets you type in filter tags.

**Comment by BenVlodgi** [comment]
textbox would be a good idea, if the filters list got long. I think right now it looks good, and easy to use. A scaling area, or expanded area would be good... I think also right now one of the problems is a filter that doesn't look like it got split right and is two filters
