### ISSUE TITLE
[Bug] 1970s Suggested Music Doesn't Change

### ISSUE THREAD

**Issue by Hyperosious** [BenVlodgi/BEE2.4#360]
When clicking "Use Suggested" with 1970's Old Aperture the music doesn't change. 
Here's an example: 
![6528ace4ddc23df357d68565a9863015](https://cloud.githubusercontent.com/assets/6967523/16359541/3f299a7c-3b30-11e6-9408-79d2e9d60e03.gif)
Not sure if this is intended or not though.

I have noticed that there is now a part 2 of the reunion (that has been added) so the default should be part 1. This can then be changed by the user to part 2 if they wish.

**Comment by TeamSpen210** [comment]
The part 1/2 change is the problem. It is set to suggest that, but I changed the music item name when making the two parts, breaking it.
