### ISSUE TITLE
Cube Deflector file doesn't exist in Overgrown Style

### ISSUE THREAD

**Issue by SW50000** [BenVlodgi/BEE2.4#362]
When I compile with a cube deflector, it gets a error.

**Comment by TeamSpen210** [comment]
What exactly is the error? Open the Developer console to see it.

**Comment by SW50000** [comment]
I closed it on accident but here it is: http://images.akamai.steamusercontent.com/ugc/258211138017070418/E92973341D1DE511CF57E39A503B04E724B27C39/ (It Happened in overgrown style)

**Comment by SW50000** [comment]
Thanks for that rename

**Comment by TeamSpen210** [comment]
Should be fixed.
