### ISSUE TITLE
Bee 2.2.5

### ISSUE THREAD

**Issue by Shooba** [BenVlodgi/BEE2.4#366]
I already have BEEMOD2, But I can't upgrade to 2.2.5...When I use the auto-installer it installs, but nothing happens...

**Comment by Luke18033** [comment]
@Shooba BEE2.2.5 is outdated now, this is BEE2.4. You can still use BEE2.2.5, but it won't be updated anymore.

**Comment by Luke18033** [comment]
@TeamSpen210 Shouldn't this be closed?
