### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by gamerscruffy** [BenVlodgi/BEE2.4#374]
Hello! I put this into the Issues tab because I didn't know where else I could post a question.

The last time I used BEE2 like a year ago, there were alot of different items. Ex. Animal King, Torch, TNT.

I'm just wondering if they have been removed for some reason or so. Thank you.

**Comment by Luke18033** [comment]
@gamerscruffy You were using BEE2.2.5 Alpha. Although it had a lot more items, @BenVlodgi and @TeamSpen210 decided to make a new BEE2.4 for some reason. All of the items will be added eventually, see TeamSpen210/BEE2-items#95.

**Comment by gamerscruffy** [comment]
Alright thnks.

**Comment by Luke18033** [comment]
@gamerscruffy You can close this issue now using the Close Issue button below.
