### ISSUE TITLE
Rendering bug?

### ISSUE THREAD

**Issue by gamerscruffy** [BenVlodgi/BEE2.4#376]
Hey! I decided to make a Puzzle where you have to go into separate sections of the map, or you could say, time. And you cannot see them unless you go through the portals. But when you look into the portal,  all the models are invisible but not the brushes. And they reappear when you go through the portal. So this may be a bug? Maybe an unfixable bug?

**Comment by Luke18033** [comment]
This seems like a Valve-bug.

**Comment by TeamSpen210** [comment]
What do you mean by portals? Worldportal doors? It sounds like the rendering issue caused by having more than 4 portals visible onscreen at once. Check the console.
