### ISSUE TITLE
[Suggestion] Add BEE2 icon to README.md

### ISSUE THREAD

**Issue by Luke18033** [BenVlodgi/BEE2.4#377]
This would make the main page look a bit nicer.
![bee2](https://raw.githubusercontent.com/BenVlodgi/BEE2.4/master/bee2.ico)

**Comment by Shooba** [comment]
I like it :P

**Comment by Luke18033** [comment]
![bee2](https://raw.githubusercontent.com/BenVlodgi/BEE2.4/master/bee2.ico)

**Comment by Luke18033** [comment]
I really should have forked the project and submitted a pull request, but I already reported the issue.
