### ISSUE TITLE
Whenever I make a 1950 map, it plays "oh fiddlesticks"

### ISSUE THREAD

**Issue by Shooba** [BenVlodgi/BEE2.4#378]
I make a map it says that when you get in, like 10 seconds later it plays the cave johnson line, people complain about this in the comments of the map so...

**Comment by SW50000** [comment]
That is a music error, I think.

**Comment by DeGenerato** [comment]
Use the p2map_publish.exe in Portal2/bin folder instead of publishing in-game. Don't forget to download the fix for it.
