### ISSUE TITLE
Connecting a trigger once to a door doesn't allow anything else to activate the door.

### ISSUE THREAD

**Issue by Flairieve** [BenVlodgi/BEE2.4#381]
If you connect a trigger once to a door, nothing else will be able to activate it but only the trigger once.
For example you hook a button to make it open and then a trigger once at the end of the door to close it, the button won't open it and the trigger once can only open it. Also with this bug for some odd reason the x and check mark indicator appears on the floor and/or on the floor behind the door, it will never appear on the wall. I'm using the overgrown theme.

**Comment by TeamSpen210** [comment]
When two items are connected, botj hsve to be activated. Try running the trigger through a NOT, then connecting that to the door.

It's better to use the Chamberlock item in this case. I can't fix the indicator locations, use a Antline Magnet to fix it.
