### ISSUE TITLE
[Suggestion] Make a special "Separated package" containing the songs from Aperture Tag for people who can´t afford the game purchase

### ISSUE THREAD

**Issue by LautaroL20** [BenVlodgi/BEE2.4#382]
Me and many other people who can not affor the purchase from AT, or that just does not likes it because it is pretty much different from what the original Portal 2 is, consider the chance of having a "Separated Package" on the download page from Bee2.4, so we can use it to making maps with these songs with beemod.

It is terrible for people who does not like AT having to buying it just because you can´t having these songs for Beemod.

**Comment by xDadiKx** [comment]
True, it's annoying that you have to buy the game (and you don't like it) just to get access to AT music.

**Comment by BenVlodgi** [comment]
It is $4.99.... Hardly a steep price.

> people who does not like AT having to buying it

How do you know that you won't like it if you haven't bought and played it??

**Comment by LautaroL20** [comment]
> How do you know that you won't like it if you haven't bought and played it??

It is pretty much different from what the original P2 Puzzle concepts are. You have a stupid Paint Gun instead of a true Portal Gun, you can not create "Portals" on AT, and therefore it detracts all the laser puzzles and many other stuff that you might have created. 

On the other hand...... The CO-OP Feature is completely unpolished / Bugged. You have to arrange some files before, to being able to build CO-OP Maps with AT.

And if you are wondering how i know all this, simple, i have a Steam friend who have AT, and he usually made Livestreams, so i had the oportunity to see how bad is AT.

**Comment by BenVlodgi** [comment]
> stupid Paint Gun
It is a different puzzle experience, just like playing any other game. Or even Portal chambers that have no portal gun. Even if having a paint gun detracts from the laser puzzles, it adds to other types of puzzles.

If you want content from a paid game, you need to pay for it. No freebies.

If you know of bugs in the Tag PTI Co-op, report them on the [issues page](https://github.com/BenVlodgi/Tag-PTI/issues), otherwise they'll never get fixed.

**Comment by LautaroL20** [comment]
@BenVlodgi @TeamSpen210 - Well, this is my lucky day, i think i will get it now:
![aperture tag](https://cloud.githubusercontent.com/assets/12244376/19226815/d59403fe-8e86-11e6-89a0-90739bc73986.png)
