### ISSUE TITLE
Big Observation Room (4x1 or 1x4 whatever it was)

### ISSUE THREAD

**Issue by bloxxingblocks** [BenVlodgi/BEE2.4#383]
Where did that one go? It was in BEE2, I think, where did it go...!?

**Comment by LautaroL20** [comment]
This should be posted into the Items page section: https://github.com/TeamSpen210/BEE2-items/issues

**Comment by TeamSpen210** [comment]
This will be done via TeamSpen210/BEE2-items#659.
