### ISSUE TITLE
Big music issue (Dr Kleiner error) and more

### ISSUE THREAD

**Issue by DeGenerato** [BenVlodgi/BEE2.4#386]
BEE 2.4 have a major issue that affects musics. I already know what musics are getting error in any style. Tests get so boring with the same music or when get the error and all chamber becomes silent.

The musics that are getting error are the musics that have the following characteristics, you probably know what is this:
http://i.imgur.com/mojJcAS.png

If the music have these three extra playback sounds, you will get a Dr. Kleiner ("Oh fiddlesticks, what now?" from half life 2) error, but only when PUBLISHING, not reconstructing the chamber.

The console error: 
http://i.imgur.com/plMrUnG.png
(Note the wheatley error, some lines from wheatley isn't playing when exit the testchamber.)

Well, you have to choice only that type of music:
http://i.imgur.com/eKw7tdv.png

I'm getting back to the BEE 2.2.5. I love both, both have unique options, for example, the fast rendering without pressing CTRL button when render, but BEE 2.2.5 are glitching with me while rendering and some skybox and ilumination are glitching for me on deadly goo. I want so bad these things fixed in Bee 2.4, and please, put the addons of the 2.2.5 on the 2.4, I love the celling light on bee 2.2.5, give so much detail.

**Comment by TeamSpen210** [comment]
The bug here might be earlier, where it lists a problem with the manifest file. The Wheatley error is actually from the music. For ceiling lights I need to re-add those, but you can partially get them by puttiing an obs room on the ceiling.

**Comment by DeGenerato** [comment]
Thanks, I didn't know about the obs on ceiling. I tried to put a music on the map in hammer, but it's hard, I get some errors, and I have to transform most of the brushes in func_detail, because PeTI maps are very bad optimized, and rendering VIS could take hours to render if I don't transform most of the brushes into func_detail. And the lines from cave/BTS/glados/wheatley dissapear when I edit in hammer and compile it, I really don't know why this happens. So, a simple tool is BEE2.4, I got back to BEE2.4, definitly it's way better than 2.2.5, but this music problem is very annoying. Almost all of my maps I put 9999999 (2) music, Doug Rattman, PeTI music 6 and Love as Construct music. Do you know a temporary solution for the musics? Thank you again.

**Comment by DeGenerato** [comment]
I discovered the FIX for the problem of Dr Kleiner!!! Just use the p2_publish tool instead of publishing in-game.
