### ISSUE TITLE
[Bug] Gel dropper doesn't compile

### ISSUE THREAD

**Issue by Kenkenkon** [BenVlodgi/BEE2.4#388]
Independent the type of gel, chamber style, position, or any other variable, when I build the level with a gel dropper, it doesn't compiles.

**Comment by DeGenerato** [comment]
Sometimes happens to me too. It's not always. Today I got an error on pedestal base button, I had to remove all buttons to compile.

**Comment by DeGenerato** [comment]
I'm getting the gel dropper error again, a simple map default room isn't compiling because of the gel dropper, is getting a error on VBSP when compile. Already exported again the files and I'm getting the same error.

http://i.imgur.com/emRY7EL.png

**Comment by TeamSpen210** [comment]
Ah, it's the voice that's the problem. I have fixed that bug for PR22.
