### ISSUE TITLE
Make Selector Windows Non-Modal

### ISSUE THREAD

**Issue by LautaroL20** [BenVlodgi/BEE2.4#389]
![Suggestion](https://cloud.githubusercontent.com/assets/12244376/18234318/f4fd075c-72d6-11e6-98c8-760c1fb742ca.png)

**Comment by TeamSpen210** [comment]
Okay. I might leave the 'style' window modal though, it changes a fair amount of other things like available items - allowing changing the style with other things open could cause bugs.
