### ISSUE TITLE
Glass / Glass Frame items / misc

### ISSUE THREAD

**Issue by jccreszMinecraft** [BenVlodgi/BEE2.4#393]
1. Half-glass item (64x128)
2. Glass frame models as used in custom maps, like the 192x128, 256x256, 128x128, etc
3. Half-block centered fizzler [||)=(||] [||)==(||]
- preferably a item that requires another hooked to it via antline and it is generated. if the item is spaced several blocks apart up to a maximum of 5 blocks, it will continue to add 32x32x128 pilliars to support the fizzler. Basically an off-center fizzler.
- a special logic item could be created to control inputs.

**Comment by TheDarkBomber** [comment]
Do issues about items [here](https://github.com/TeamSpen210/BEE2-items/issues).
This issue section is about is the BEE2 Application.

**Comment by Luke18033** [comment]
This should be ~~closed~~ moved.

**Comment by TeamSpen210** [comment]
This issue was moved to TeamSpen210/BEE2-items#798
