### ISSUE TITLE
how can i get the code for and compile bee2.4 before next pre release

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BenVlodgi/BEE2.4#395]
@TeamSpen210 - if you haven't done it yet, how can i get the code for and compile bee2.4 before next pre-release so i can get more beta than beta...

**Comment by TheDarkBomber** [comment]
Go to code, select Clone or Download, click Download ZIP

**Comment by xDadiKx** [comment]
Where do you find the code tho?

**Comment by TheDarkBomber** [comment]
I mean the code tab on Github (next to issues)
