### ISSUE TITLE
BEE 2.4 Suggestions

### ISSUE THREAD

**Issue by christophermc0324** [BenVlodgi/BEE2.4#396]
Not everyone has Aperture Tag, so it would be cool to add the paint gun (Which I think has been around longer than the game) and a gravity gun could be used in creative tests. It has been made into an addon before, but it isn't compatible with BEE2.4. I'm sure if you asked the creator (http://www.moddb.com/games/portal-2/addons/rb-tamradelites-bee2-addon-modextended-editor), thet/he would allow it.  Also, could you create a trigger_teleport and teleport_destination? That would be very useful in test chambers, like if you had to find a cube and you then have to get all the way back, you could either walk in the area with the trigger teleport or you could push a button to activate it.

**Comment by Luke18033** [comment]
@TeamSpen210 Why did you close this?

**Comment by TeamSpen210** [comment]
Reconstructing is planned. The other suggestions won't be added (I'm not going to redistribute the paint gun model, and the teleport doesn't make too much sense).
