### ISSUE TITLE
[Prl22 Bug] Export maps causing "divide by zero" error

### ISSUE THREAD

**Issue by cartman1337** [BenVlodgi/BEE2.4#399]
This is a bug of Bee2.exe, not linked to any game item or style. When you go to the Backup/Restore Puzzles option from the File menu, and choose either "Save Backup" or ".. As", when you hit Save on whatever file name and location you choose, the program crashes with an error saying:

BEE2 Error:
ZeroDivisionError: ZeroDivisionError('division by zero',)

In other words, backup isn't working, because no file is created.

**Comment by Jadeygaming** [comment]
That Kinda Weird How It Talks About Dividing By Zero...

**Comment by TeamSpen210** [comment]
It's because of the loading screen - that tries to display 'x/0' maps, and crashes trying to calculate the percentage. I've fixed that issue in the loading screen, and the backup now displays an error when no maps are selected. 

Did you choose any maps to backup?
