### ISSUE TITLE
[Bug PR 22] Logic gates bugged from old map

### ISSUE THREAD

**Issue by Venima** [BenVlodgi/BEE2.4#400]
I tried upgrading to the latest version of beemod (pr22), to see if it fixes some texture bugs with the antlines & signs, and I find the logic gates are no longer functional; even when remaking them. I reverted back to pr16 and they worked again.

**Comment by TeamSpen210** [comment]
What sort of bugs?

**Comment by Venima** [comment]
The antline bugs were from the old pr16, sorry for not making that clearer.

The logic gates don't seem to ever output true, even when all the conditions are met.

**Comment by TeamSpen210** [comment]
The issue is specifically that multiple logic gates might/might not send signals to each other. It depends on what order they are processed in.
