### ISSUE TITLE
Issue with custom music

### ISSUE THREAD

**Issue by Byzarru** [BenVlodgi/BEE2.4#401]
I'm trying to add a custom music track by the instructions in #24. I'm using prerelease 22.  I created an info.txt with this data:
```
"ID"        "POPCORN_MIDI"
"Name"      "Popcorn Midi"

"Music"
    {
    "ID"            "POPCORN_HOT_BUTTER"
    "Name"          "Popcorn"
    "Group"         "Custom"
    "ShortName"     "Popcorn"
    "Icon"          "BEE2/music/music_icon.png"
    "Authors"       "Gershon Kingsley"
    "Description"   "Test"
    "SoundScript"   "sound/popcorn.wav"

    "Pack"          "sound/popcorn.wav"
    }
```
I have the directory as follows:
```
popcorn.zip
+resources
-+BEE2
--+music
---+music_icon.png
-+sound
--+popcorn.wav
+info.txt
```
When I put the package into the packages folder and run BEE2.4, it will get to extracting 204/301 images before suddenly closing. If I remove the package, BEE will extract 298/298 images and run as normal. The log apparently loads the music, but the last lines are:
```
[DEBUG] packageLoader.load_packages(): Loading BrushTemplate "BEE2_SIGNAGE_50S_EXIT"!
[DEBUG] packageLoader.load_packages(): Loading Style "BEE2_OVERGROWN"!
[DEBUG] packageLoader.load_packages(): Loading Style "BEE2_1960s"!
[DEBUG] packageLoader.load_packages(): Loading Style "BEE2_CLEAN_ORIGINAL"!
[DEBUG] packageLoader.load_packages(): Loading Style "BEE2_1950s"!
[DEBUG] packageLoader.load_packages(): Loading Style "BEE2_1970s"!
[DEBUG] packageLoader.load_packages(): Loading Style "BEE2_BTS"!
[DEBUG] packageLoader.load_packages(): Loading Style "BEE2_PORTAL_1"!
[DEBUG] packageLoader.load_packages(): Loading Style "BEE2_CLEAN"!
[DEBUG] packageLoader.load_packages(): Loading Style "BEE2_1980s"!
[INFO] BEE2_config.save(): Saving changes in config "../config\config.cfg"!
```

What am I doing wrong?

**Comment by TeamSpen210** [comment]
Try removing the image file, to see if that's the cause.

**Comment by Byzarru** [comment]
Didn't work. I removed both the image and the reference to it in info.txt.

```
[DEBUG] packageLoader.load_packages(): Loading StyleVar "P1_WPORTAL_STRIPS"!
[DEBUG] packageLoader.load_packages(): Loading StyleVar "P1_PORTED_PGUN"!
[DEBUG] packageLoader.load_packages(): Loading StyleVPK "VPK_BEE2_OVERGROWN"!
[DEBUG] packageLoader.load_packages(): Loading StyleVPK "VPK_BEE2_1980S"!
[DEBUG] packageLoader.load_packages(): Loading StyleVPK "VPK_BEE2_PORTAL_1"!
[DEBUG] packageLoader.load_packages(): Loading StyleVPK "VPK_BEE2_1950S"!
[DEBUG] packageLoader.load_packages(): Loading StyleVPK "VPK_BEE2_BTS"!
[DEBUG] packageLoader.load_packages(): Loading StyleVPK "VPK_BEE2_1970S"!
[INFO] BEE2_config.save(): Saving changes in config "../config\config.cfg"!
```

The log still notes that my package has been extracted and my music has been loaded.

**Comment by TeamSpen210** [comment]
Attach a copy here and I'll have a look.

**Comment by Byzarru** [comment]
[popcorn.zip](https://github.com/BenVlodgi/BEE2.4/files/483642/popcorn.zip)

Here it is as it was when I first posted.

**Comment by Byzarru** [comment]
Additional note, if I want to include a remix track (same tempo and notes and length) for gels and funnels, will all of the tracks line up? Is there a special function I'd need to add? I briefly looked at the Portal 1 music info file and saw that the extra tracks were essentially little snippets as opposed to full-length tracks, and there's nothing I could find about the Portal 2 tracks.

**Comment by TeamSpen210** [comment]
Portal 2 uses a much more [complex sound system](https://developer.valvesoftware.com/wiki/Soundscript#Operator_stacks) than in Portal 1, to allow this behviour. The BEE2 compiler auto-generates this though, so it only needs the WAV files. The extra sounds start offset so the notes will line up. Gel sounds are overlaid with the normal music, Funnel sounds fade in and replace the normal music temporarily. Providing multiple means one is randomly chosen each time.

**Comment by TeamSpen210** [comment]
Ok, I figured out the issue - it's to do with the exact way/program you used to generate the zip file. Leave it unzipped for now (just in a folder with the same name), or use the `compile_packages` script in the BEE2-items repro.

**Comment by Byzarru** [comment]
TYVM
