### ISSUE TITLE
File Exists Error

### ISSUE THREAD

**Issue by QuantiX999** [BenVlodgi/BEE2.4#404]
When I click on the "Export" button, it says something like "FileExistError17: Unable to create a file because it already exists". To get past this error, I have to delete all "bee2" folders in Portal 2 directory in Steam.

**Comment by QuantiX999** [comment]
No one?

**Comment by TeamSpen210** [comment]
Attach the contents of `bee 2/logs/BEE2.log`.

**Comment by QuantiX999** [comment]
This was at the end of the log:

[ERROR] tk_tools.tk_error(): TKinter callback exception occurred:
 | Traceback (most recent call last):
 |   File "F:\Git\BEE2.4\src\UI.py", line 802, in export_editoritems
 |   File "F:\Git\BEE2.4\src\gameMan.py", line 537, in export
 |   File "F:\Git\BEE2.4\src\gameMan.py", line 323, in refresh_cache
 |   File "C:\Python34\lib\shutil.py", line 303, in copytree
 |   File "c:\python\32-bit\3.4\lib\os.py", line 237, in makedirs
 | FileExistsError: [WinError 183] Unable to create a file because it already exists: 'c:\\program files\\steam\\steamapps\\common\\portal 2\\bee2\\sound'
 |_

**Comment by QuantiX999** [comment]
Hey?

**Comment by TeamSpen210** [comment]
Try deleting the /bee2/ folder there.

**Comment by QuantiX999** [comment]
I am doing that to avoid this error.
