### ISSUE TITLE
(Long Term) add tools to bee2 to assist in custom portal 2 mod creation.

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BenVlodgi/BEE2.4#405]
i just thought of this, in the long run add some tools built into to bee2 to assist in custom portal 2 mod creation. here is a list of what needs to be completed for this in the long run...

- [ ] make bee2 have a option to generate the beginning of a custom mod (title screen, menu's, back image etc.)
- [ ] make bee2 dump a compiled map as a vmf and also generate all the folders and directories and resources and necessary for the custom resources and parts used in a single map in a custom portal 2 mod (the folders would be carefully merged with instructions on how to do so in bee for the mod for more than one map)
- [ ] option for bee2 to select custom maps in order and generate the file the mod uses for the map order.

**Comment by TeamSpen210** [comment]
This has nothing to do with the BEE2. I'm not adding a 'make a mod for you' button, that would inevitably give terrible results.

**Comment by Luke18033** [comment]
This would probably be better as a separate tool.
