### ISSUE TITLE
Vactubes

### ISSUE THREAD

**Issue by Jadeygaming** [BenVlodgi/BEE2.4#408]
Vactubes Are Not Working
![20161008163111_1](https://cloud.githubusercontent.com/assets/22718537/19216533/be4f5a58-8d74-11e6-89a7-be71d0b71d61.jpg)

**Comment by Jadeygaming** [comment]
No People Replying?

**Comment by TeamSpen210** [comment]
It looks like you might have the vactubes pointing the wrong way. Make sure the rotation handles are pointing in the same directions.

**Comment by Jadeygaming** [comment]
How About If You Want To Make A Turn?

**Comment by TeamSpen210** [comment]
Make sure there's some space between them, and place them at the beginning and end.

**Comment by Luke18033** [comment]
I had this same problem when I first used vactubes.

**Comment by Jadeygaming** [comment]
![20161013192636_1](https://cloud.githubusercontent.com/assets/22718537/19373736/50747fd0-917b-11e6-926d-ee08fe28eab0.jpg)
This Happened Now

**Comment by h4uja2** [comment]
Vactubes work fine to me, make sure you rotated and connected them right
[Editor screenshot](http://i.imgur.com/lQnsizA.jpg)
[In-game screenshot](http://i.imgur.com/3T34UrP.jpg)

**Comment by Luke18033** [comment]
Somebody is going to need to make a Vactubes Tutorial video, so this question stops getting asked so much.

**Comment by Jadeygaming** [comment]
Yeah That Would Be Nice :)

**Comment by Konclan** [comment]
Well it may be easier if the vactubes had a model with an arrow pointing which way they are going

**Comment by Jadeygaming** [comment]
Wasn't Using Them Right :)

**Comment by TeamSpen210** [comment]
Also fixed, since I added an editor model for them.
