### ISSUE TITLE
BEE2 Hammer Export Help (Solved)

### ISSUE THREAD

**Issue by Alfe5** [BenVlodgi/BEE2.4#409]
I keep getting this error in hammer

-------------------------------------------------------------------------------
Running command: cd "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin"
-------------------------------------------------------------------------------

-------------------------------------------------------------------------------
Running command: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp.exe" -game "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2" "C:\Program Files (x86)\Steam\SteamApps\common\Portal 2\sdk_content\maps\template.vmf"
-------------------------------------------------------------------------------

[I] vbsp: BEE2.4.0pr21 VBSP hook initiallised.
[I] cond.core: Imported all conditions modules!
[I] vbsp: Map path is "C:\Program Files (x86)\Steam\SteamApps\common\Portal 2\sdk_content\maps\template.vmf"
[I] vbsp: New path: "C:\Program Files (x86)\Steam\SteamApps\common\Portal 2\sdk_content\maps\styled\template.vmf"
[I] vbsp: Clearing inject/ directory..
[W] vbsp: Hammer map detected! skipping conversion..
[I] vbsp: Calling original VBSP...
[I] vbsp: Arguments: "C:\Program Files (x86)\Steam\SteamApps\common\Portal 2\bin\vbsp_original.exe" -game "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2" "C:\Program Files (x86)\Steam\SteamApps\common\Portal 2\sdk_content\maps\template.vmf"
[E] <Valve>: Valve Software - vbsp.exe (Aug 26 2015)
 | 8 threads
 | materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading C:\Program Files (x86)\Steam\SteamApps\common\Portal 2\sdk_content\maps\template.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | Could not open instance file instances/BEE2/logic/blocks/wall_half_center_black.vmf
wall_half_center_black.vmf
 |
 |_

[E] vbsp: VBSP failed! (1)
Finished. Press a key to close.

I have no idea where to dump the packed files to and I can't find a guide. Its not just for blocks/wall_half_center_black.vmf This error happens to all BEE2 vmf custom items. If someone could help me it would really help!

**Comment by TeamSpen210** [comment]
You need to open `styled/preview.vmf`, that's the map modified by the compiler. As you can see, many instances are just flags and don't exist in a folder anywhere.

**Comment by Alfe5** [comment]
TeamSpen210, where can I find that?

**Comment by Alfe5** [comment]
found it! thank you

**Comment by Alfe5** [comment]
https://github.com/BenVlodgi/BEE2.4/issues/410
