### ISSUE TITLE
BEE2 Hammer Export Help Part 2

### ISSUE THREAD

**Issue by Alfe5** [BenVlodgi/BEE2.4#410]
So, I decided to work on another map in hammer than the one I was using and deleted the preview.vmf from hammer thinking a new one would appear. I exported my new map over and the preview.vmf is really deleted. Did I screw up big time??? I would really like an in depth guild on how exactly BEE2 to Hammer exporting works.

**Comment by TeamSpen210** [comment]
You need to compile ingame to generate it.

**Comment by Alfe5** [comment]
I did...
Should I try getting the beta version of BEE2 to see if that fixes it?

**Comment by Alfe5** [comment]
Okay, I went ahead and re validated my Portal 2 game cache and now I get the preview. Thanks

**Comment by Alfe5** [comment]
However I am getting this error. -------------------------------------------------------------------------------
Running command: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vvis.exe" -game "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2" "C:\Program Files (x86)\Steam\SteamApps\common\Portal 2\sdk_content\maps\styled\preview"
-------------------------------------------------------------------------------

Valve Software - vvis.exe (Aug 26 2015)
8 threads
reading c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\styled\preview.bsp
reading c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\styled\preview.prt
LoadPortals: couldn't read c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\styled\preview.prt

Finished. Press a key to close.

**Comment by Alfe5** [comment]
Okay, I had to re-validate my game cache and now when I compile it it works. Thank you. (Man Hammer is hard to learn.)
