### ISSUE TITLE
Aperture Tag Will Not With BEE Anymore.

### ISSUE THREAD

**Issue by Jadeygaming** [BenVlodgi/BEE2.4#412]
(when exporting ) It Said In A Error Message "FileNotFoundError: FileNotFoundError(2, 'Not Such File Or Directory')" Am I Doing Something Wrong? (Sorry Can't Get Screenshot Because When I Took The Portal 2 Screenshots I Used The Steam Screenshot Tool) Also I Do Have It Installed. UPDATE : Reinstalling Did Not Work

**Comment by Jadeygaming** [comment]
Hello This Issue Need TO Be Fixed!

**Comment by TeamSpen210** [comment]
Post the contents of `bee2/logs/bee2.log` here.

**Comment by Jadeygaming** [comment]
Here : http://pastebin.com/kd6he9VD

**Comment by Jadeygaming** [comment]
#420 Closed
