### ISSUE TITLE
"Oh, Fiddlesticks" Music Error

### ISSUE THREAD

**Issue by QuantiX999** [BenVlodgi/BEE2.4#413]
Whatever music I choose, it plays normally at the preview, but when uploaded, it says "Oh, fiddlesticks" and silence...

**Comment by Jadeygaming** [comment]
TeamSpen Hasn't Been Replying To Issues Latly

**Comment by TeamSpen210** [comment]
This has been fixed for the next release.

**Comment by Jadeygaming** [comment]
Did He Really Skip My Issue?

**Comment by LautaroL20** [comment]
This is a duplicate of: https://github.com/TeamSpen210/BEE2-items/issues/679
