### ISSUE TITLE
Delayer Not Working?

### ISSUE THREAD

**Issue by OnlyFails** [BenVlodgi/BEE2.4#417]
Hey I am having troubles with the delayer object.

What is suppose to happen is I have two connected to each other, the first one waits 4 seconds and then holds power for 3 seconds. But the first delayer never fires any output to the next delayer. It works the first time I try it but then it breaks for no reason and no matter how many times I delete these from the level and replace them in the world they won't trigger any outputs ever again.

The weird thing though is that I have a bunch of delayers on the opposite side of the map doing the exact same thing because they are clones of the same mechanic I am making so it must just be the cubes I am working inside of that affect these delayers?

Any information anyone has on this please let me know! Thank you>

EDIT: I made a video to demonstrate what happens for me:
🔗 https://youtu.be/5um0vHxPb6I
Awesome mod except for this one part! Thank you so much for making this! 😃

**Comment by Luke18033** [comment]
This should be moved to [BEE2-items](https://github.com/TeamSpen210/BEE2-items).

**Comment by TeamSpen210** [comment]
This is caused by a bug, dependent on the exact order the compiler operates on the items.
