### ISSUE TITLE
Crusher panel.

### ISSUE THREAD

**Issue by Modsojoy** [BenVlodgi/BEE2.4#419]
Why cant i configure it? I cant select length and in the editor it shows up as an error, It works and plays fine though.

**Comment by MrKrunk** [comment]
Crusher panels aren't meant to be tweaked in general. Unless I'm wrong, because I haven't tested out the mod in a while. The error model however is an actual bug.

**Comment by TeamSpen210** [comment]
The model doesn't really have a length, it only ever extends the same distance.

**Comment by Jadeygaming** [comment]
Hey TeamSpen210 I Added The Log To The Aperture Tag Isn't Working Page.
