### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by SPAHI4** [BenVlodgi/BEE2.4#422]
First time when I'm trying to build chamber game chashes after loading. 
When I'm launch game after this there is a text "changes was autosaved" in editor and then build is successfull . But after any changes game crashes again.
Windows 10.
If any logs exists I can attach them

**Comment by Jadeygaming** [comment]
The Logs Are In Bee2/logs/BEE2 post them here so that TeamSpen has them here and ready.

**Comment by TeamSpen210** [comment]
In this case they aren't too useful, since the configs export correctly. Logs for the compiler are in `Portal 2/bin/bee2/vbsp.log`.

**Comment by SPAHI4** [comment]
[vbsp.log.txt](https://github.com/BenVlodgi/BEE2.4/files/582557/vbsp.log.txt)

**Comment by SPAHI4** [comment]
There is no crash on new created chamber
