### ISSUE TITLE
Backups Doesn't Restore

### ISSUE THREAD

**Issue by QuantiX999** [BenVlodgi/BEE2.4#424]
When I try to restore a backup, it shows this:
[ERROR] tk_tools.tk_error(): TKinter callback exception occurred:
 | Traceback (most recent call last):
 |   File "F:\Git\BEE2.4\src\backup.py", line 665, in ui_restore_all
 |   File "F:\Git\BEE2.4\src\backup.py", line 492, in restore_maps
 |   File "c:\python\32-bit\3.4\lib\ntpath.py", line 108, in join
 |   File "c:\python\32-bit\3.4\lib\ntpath.py", line 159, in splitdrive
 | TypeError: object of type 'NoneType' has no len()
 |_

**Comment by TeamSpen210** [comment]
Select a game in the list before restoring to it, that should resolve the issue.
