### ISSUE TITLE
A disparity of the announcers lines are just ''Oh Fiddlesticks, what now?'' 

### ISSUE THREAD

**Issue by Hoovy** [BenVlodgi/BEE2.4#426]
I haven't tried them all yet, but a few I can name are ''Smooth Jazz'' and ''Lethal Military Androids''.  Also, the mid lines as well as the exit lines never show up at all.  idk if I'm doing something wrong or if it's a problem.  So, never mind that.  Because as I found out, it wasn't the voicelines, it was the MUSIC!  But even that doesn't matter now.  Every time it's about to finish exporting, I get an error message.  ''Permission error: Permission Error(13, 'Access is denied')''      EDIT:  I found out that the problem came from how my steam was frozen........  My own fault......  Whatever, it's working now.  Notice how much has been done without ANY replies?  It's almost like this place is dead and that I'm writing to myself.

**Comment by TeamSpen210** [comment]
The couple of bugs here should be fixed.
