### ISSUE TITLE
BEE 2.5.5 I know this is from an old version but no one is gonna check the old one. - Items are missing in BEE2 2.2.5

### ISSUE THREAD

**Issue by Jadeygaming** [BenVlodgi/BEE2.4#428]
<img width="750" alt="capture" src="https://cloud.githubusercontent.com/assets/22718537/20552936/799ca2ac-b115-11e6-9c56-8ab6ca6a0458.PNG">
Probably gonna be taken down immediately.

**Comment by Jadeygaming** [comment]
Doing this because I wanted to use the old BEE2 but ran into this.

**Comment by TeamSpen210** [comment]
I really don't know why this bug happens, I think it might be due to the install location.

**Comment by Jadeygaming** [comment]
i install it on a D:/ Drive in my Portal 2 Folder.

**Comment by Jadeygaming** [comment]
I figured it out.

**Comment by Luke18033** [comment]
If you have any problems with BEE2.2, open an issue [here](github.com/BenVlodgi/BEE2.2). But it's probably not going to get fixed...
