### ISSUE TITLE
Bug: Game gives test chamber build error with new version of bee2

### ISSUE THREAD

**Issue by ellingtonisland** [BenVlodgi/BEE2.4#43]
Bug: Game gives test chamber build error when using clean style in new version of bee2

**Comment by TeamSpen210** [comment]
What's the actual compile error? Copy it out of the developer console (with developer 2 enabled).

**Comment by ellingtonisland** [comment]
here is what the dev console gave on building test chamber in PTI

i had the new bee2 extracted to the desktop and ran it from there, does it have to be in a certain folder, the PTI showed a bunch of purple error textures in it for items!

==== calling mapspawn.nut
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198025151093\autosave.p2c
Parent cvar in client.dll not allowed (r_shadowlod)
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
Redownloading all lightmaps
[PORTAL2 PUZZLEMAKER]  Saved puzzle: puzzles\76561198025151093\1433085382.p2c
Ellington Isle unpaused the game
Ellington Isle unpaused the game
Ellington Isle unpaused the game
Ellington Isle unpaused the game
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198025151093\autosave.p2c
Ellington Isle unpaused the game
Ellington Isle unpaused the game
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,6)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 99 (ms)

VBSP failed.

vbsp_styles: Starting style Changer VBSP hook.
vbsp_styles: Elevators (hold ctrl): False
vbsp_styles: commandline: " -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/""
vbsp_styles: filename: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
vbsp_styles: game: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/"
vbsp_styles: limit: 1750
vbsp_styles: Saved modified C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\styled\preview.vmf
vbsp_styles: Changed 0 materials.
vbsp_styles: -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\styled\preview.vmf"
vbsp_styles: Launching and waiting for "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" with commandline "-game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\styled\preview.vmf""
Valve Software - vbsp.exe (Aug 26 2014)
4 threads
materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
Loading C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\styled\preview.vmf
ConVarRef gpu_level doesn't point to an existing ConVar
Could not open instance file instances/BEE2/bts/elevator_sp/entrance_corridor_2.vmf

vbsp_styles: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" finished.
vbsp_styles: Packing because RunBspZip is set to 1 in editoritems.txt
vbsp_styles: Making C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/\puzzles\76561198025151093\untitled.jpg writable
