### ISSUE TITLE
Missing texture for large Ariel Faith plate on wall 

### ISSUE THREAD

**Issue by Jadeygaming** [BenVlodgi/BEE2.4#434]
In Game
![20161127114402_1](https://cloud.githubusercontent.com/assets/22718537/20651316/ec936144-b497-11e6-93fc-c0ed1bf871f9.jpg)

In Editor
![20161127114409_1](https://cloud.githubusercontent.com/assets/22718537/20651321/f81ae42e-b497-11e6-8949-316022507abd.jpg)

**Comment by Luke18033** [comment]
This should go on BEE2-items.

**Comment by LautaroL20** [comment]
This issue has been moved to the items section.

https://github.com/TeamSpen210/BEE2-items/issues/1080
