### ISSUE TITLE
Add GLaDOS and Wheatley!

### ISSUE THREAD

**Issue by TANER05** [BenVlodgi/BEE2.4#443]
Hey! Can you add GLaDOS? Like, you can set it to angry: This will make GLaDOS attack you. Then calm: This will make GLaDOS ignore you. And friendly: GLaDOS will talk to you (you can set the talking time. Like if you set the time for 5 seconds, GLaDOS will talk for five seconds then don't) And make theese for Wheatley too! Please add them.

**Comment by TheDarkBomber** [comment]
You mean voice lines? We already have voice lines.

**Comment by TeamSpen210** [comment]
No. It doesn't make sense for GLaDOS to be in a random test chamber.
