### ISSUE TITLE
add panel

### ISSUE THREAD

**Issue by ILIA-NENASHEV** [BenVlodgi/BEE2.4#447]
![2011-04-14_00004](https://cloud.githubusercontent.com/assets/24510029/21082023/91d27bda-bfe3-11e6-8531-fd865fac3ea0.jpg)
![hqdefault](https://cloud.githubusercontent.com/assets/24510029/21082022/91d1f9f8-bfe3-11e6-827a-dfa3df0ea916.jpg)
![maxresdefault](https://cloud.githubusercontent.com/assets/24510029/21082024/91d2b820-bfe3-11e6-9bc2-fee444683b89.jpg)
![portal___panels_by_first9-d5bsd9a](https://cloud.githubusercontent.com/assets/24510029/21082021/91d1c050-bfe3-11e6-931e-afa6b19cd47a.jpg)
![portal_2___creepy_panels_by_half_dude-d3h7veu](https://cloud.githubusercontent.com/assets/24510029/21082020/91d159d0-bfe3-11e6-8348-31a2f320ad0a.jpg)

**Comment by LautaroL20** [comment]
To suggest things related to items, this is the page: https://github.com/TeamSpen210/BEE2-items/issues

**Comment by Luke18033** [comment]
This should be closed.
