### ISSUE TITLE
Item/Theme Correlation Issues

### ISSUE THREAD

**Issue by jccreszMinecraft** [BenVlodgi/BEE2.4#45]
When building a test chamber with BEEMod (Any Version) you may choose a few items and add them to the map and then go back to BEEMod. Now you want to add more items and change the theme. items available in one theme will disappear from the paletter another theme in both BEEMOD and en route the PTi palette. While this makes sense in some places, like not having a sendificator in the 1950's, it bugs me sometimes when i have to make testchambers in specific themes for the kind of puzzle i want.

**Comment by TeamSpen210** [comment]
This is actually one of the things I changed for the BEE2.4. Every item will be available in some style no matter what styled versions are specified. It'll prefer using the the appropriate version, or one from the "parent" style (1970 uses 1950s items if they haven't changed). If the BEE2 has to it'll use an "incorrect" version.

**Comment by jccreszMinecraft** [comment]
Cool. Thanks ;)
Great to see this heading places ^.^
