### ISSUE TITLE
srctools module is missing from repo?

### ISSUE THREAD

**Issue by gordoodle** [BenVlodgi/BEE2.4#453]
I cloned the repo and can't compile because srctools appears to be missing:

gmercer@Raptor MINGW64 ~/bee2_git/BEE2.4/src (master)
$ ls -ltR | grep src

I can see commits where you have moved things into srctools, but it just looks like deletes.

is the srctools module missing from the repo, or am I missing something dumb? Thanks!

**Comment by TeamSpen210** [comment]
It's at [TeamSpen210/srctools](https://github.com/TeamSpen210/srctools/).
