### ISSUE TITLE
[Behind The Scenes] Entry Door Glitch

### ISSUE THREAD

**Issue by Jazz63540** [BenVlodgi/BEE2.4#454]
Whenever I build a chamber in the behind the scenes style, the view through the entry door is very glitchy. I have already attempted 'verify integrity of game cache':

![20161218234826_1](https://cloud.githubusercontent.com/assets/22215605/21297736/fe55bd00-c57c-11e6-90e0-9594e67c52f5.jpg)
![20161218234831_1](https://cloud.githubusercontent.com/assets/22215605/21297737/fe5ab83c-c57c-11e6-8301-4bd3cd9de83a.jpg)

**Comment by Byzarru** [comment]
This should go on https://github.com/TeamSpen210/BEE2-items/issues.
The BTS style is in development, so a lot of the entries and exits have leaks.

**Comment by Jazz63540** [comment]
I've posted it there now. Thanks.
