### ISSUE TITLE
Attached windows stick to main screen

### ISSUE THREAD

**Issue by BenVlodgi** [BenVlodgi/BEE2.4#51]
When dragging the main BEEMOD window to a second screen the attached windows stay on the main screen

**Comment by TeamSpen210** [comment]
This would be the 'fault' of `utils.adjust_inside_window()`. Tkinter only provides methods to get the screen size of the primary display. The reason I have that function is to stop the windows being pushed entirely off-screen when moving the main window. I'll add an option to disable that, along with something to reset window positions.

**Comment by BenVlodgi** [comment]
I don't know if this works on windows as-well, but this may be helpful.
http://stackoverflow.com/a/3129567/1812944
