### ISSUE TITLE
publish error

### ISSUE THREAD

**Issue by ellingtonisland** [BenVlodgi/BEE2.4#56]
i get this error when i try to publish a map with clean style and glados and everything in latest release of bee2.4

Redownloading all lightmaps
[PORTAL2 PUZZLEMAKER]  Saved puzzle: puzzles\76561198025151093\1435511518.p2c
[PORTAL2 PUZZLEMAKER]  Saved puzzle: puzzles\76561198025151093\1435511518.p2c
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/1435511518.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (10,7,6)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 83 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VBSP): 6389 (ms)

VVIS failed.

Valve Software - vvis.exe (Jun  4 2014)
4 threads
reading c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\1435511518.bsp
reading c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\1435511518.prt
LoadPortals: couldn't read c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\1435511518.prt

**Comment by BenVlodgi** [comment]
Is this only happening when you try to publish? Does this happen on a normal compile?

VVIS failing usually makes me think there is a leak, but it says it cant read the prt file, which I think is strange.

**Comment by ellingtonisland** [comment]
only happens on a real publish to the steam workshop, works fine on normal compile.

**Comment by jccreszMinecraft** [comment]
This happens a lot with BEEMOD, no matter what version. Mainly it happens
if some special items from BEE are close to the edge of the map, where
stuff may stick out into the void.

On Sun, Jun 28, 2015 at 5:33 PM, ellingtonisland <notifications@github.com>
wrote:

> only happens on a real publish to the steam workshop, works fine on normal
> compile.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BenVlodgi/BEE2.4/issues/56#issuecomment-116343409>.
>



-- 
[image: Ice Network 2014]

**Comment by ellingtonisland** [comment]
this is being caused by leaks
