### ISSUE TITLE
Over ride VPK editor wall textures for styles

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BenVlodgi/BEE2.4#61]
it would be cool to Override the vpk editor wall textures for styles so you could have custom editor textures with custom doors underground in a underground style.

implement something in bee2 that can restore default vpk editor textures to prevent it from breaking portal 2.

**Comment by BenVlodgi** [comment]
Oh is this for the in-game editor?
Yah, TeamSpen has been working on this feature for like a year :D
did it release with PR-18 0762be17d061aafa21b44c30b90f7ce6d45028c5, because that would be sweet

**Comment by TeamSpen210** [comment]
I eventually decided to hardcode the copying into dlc3 (I've been trying to think of ways to handle Valve releasing a game update, but that's probably a bit premature at this point.)  I've also overriden some other things like the Aperture logos seen in the editor, as well as switching out some UI elements (making the pedestal button timer use the nixie tube textures, for example.)

**Comment by BenVlodgi** [comment]
Can you do dlc99 perhaps? 
If you do change it, you'd have to write a little cleanup procedure for dlc3 but only if its BEE2 stuff in there, I know some other mods have used the dlc3 hack before.

**Comment by TeamSpen210** [comment]
The preceding dlc folders need to exist as well for Portal 2 to load it. For other mods, they don't really need it - a proper sourcemod can set gameinfo to have any priority they want - the `aperturetag/` or `portalstories/` folder is higher priority than any of the `portal2/` folders. I'm actually copying it to `portal2/` in the case of Aperture tag - the priorities are set such that that folder is higher than the `portal2_dlc2/` folder we're trying to override.

**Comment by BenVlodgi** [comment]
I see, perhaps then this should just be a configuration for each game, what folder to export the resources to, so that way if portal 2 does ever come out with a new version, anyone can still use it by updating that config.
or be quick on the draw for a new release.
I wonder if it makes a difference whether or not the user has the sixense expansion.
