### ISSUE TITLE
Portal Deflection Cube issues

### ISSUE THREAD

**Issue by jccreszMinecraft** [BenVlodgi/BEE2.4#62]
Recently I've been working with "p0rtalmaster" on a map in hammer, you may know the name. Anyhow we are building a map in hammer using a exported PTi puzzle that used deflection cubes. Unfortunately on every test compile they just sit there and look fancy (their normal look) but you could shoot them all day and they wouldn't do a thing if compiled with Hammer. To me it seems like a VScript issue. Also notable: They don't work with any form of dropper, and 2. Let's say you're on one side of a fizzler, and the cube is on the other. You can shoot at the cube thru the fizzler and it will activate. number 2 happens with PTi, and in hammer if they decide to work right in the test compile.

**Comment by TeamSpen210** [comment]
Number 2, and the fact that they also work through anything else (including solid wall) is the reason why I don't think I'll be reimplementing them. You need the p2editor_clean/global_ents instance from my addons collection, it has a copy of the various entities that make the cube work. You'll also need to pack the script.

**Comment by xDadiKx** [comment]
TeamSpen210 can I ask you a question? Since the release of BEE 4.0pr?? How do you install addons to the new BEE program?

**Comment by TeamSpen210** [comment]
I've completely redesigned the way things are added, so any previous stuff won't work. (That's why a lot of things are missing, I still need to port them). To add things, you just put the zip file in the 'packages' subfolder in the BEE2 folder and it'll install everything automatically.

**Comment by xDadiKx** [comment]
I put one of your mods in the package. And I opened up BEE4.0pr5 doesn't seem to work.

**Comment by BenVlodgi** [comment]
@xDadiKx you should actually create a new issue with the Question label to ask these.
 
The answer is that the Teamspen210 Addon pack for the BEE2 is for the BEE2.2.5 and is not supported in the BEE2.4.0 (this version)
