### ISSUE TITLE
Bee2.4pr5 bugs

### ISSUE THREAD

**Issue by harritron2k2** [BenVlodgi/BEE2.4#63]
I am a big fan of your mod and I found some bugs yesterday.
* [x] Placing a gel splat causes a combiler error (can't find instance)
* [x] Overgrown style and BTS can't find style instances and gives combile error
* [ ] Wheatley voice doesn't work
* [ ] BSOD elevator video doesn't work, just black screen

That's really it for bugs. All P2 items and all BEE items seem to work so far, and the catwalks are amazing! Great Job!

**Comment by TeamSpen210** [comment]
For number 3, I don't really consider walking on piston arms a valid part of a puzzle. Depending on the style, the exact shape of the piston will probably change considerably. I might actually add clips to forcefully prevent you from walking on pistons.

Custom elevator videos aren't actually implemented currently, the option does nothing.

PDVs will match the surface type they are attached to, which is usually the ceiling.

**Comment by harritron2k2** [comment]
Thanks for the correction. I removed those
