### ISSUE TITLE
Questions and Suggestions- Open to Everyone

### ISSUE THREAD

**Issue by harritron2k2** [BenVlodgi/BEE2.4#64]
I'm just wondering about the Wheatley style. How long do you think it will be until it's in the mod? What pre-release/release do you think you are going to release it in?

Also about goo. Can you make it so that you can select a alternative version of it so that it can be a bottomless pit?

Last thing. May I see a photo of the BTS bottomless pit because BTS doesn't combile and I really wanted to see the upgraded pit.

Not trying to be pesky, take your time with this. It must have been a lot of work to get it all working. Really nice job. You deserve a reward.

**Comment by ellingtonisland** [comment]
wheatley, years from now!

there will be a alternative goo which will also work with goo walls and ceilings that will make bottomless pits

**Comment by TeamSpen210** [comment]
Bottomless pits are controlled by the selected skybox, not the style. You'll be able to use pits in any style, although it'd be good if they match. Goo will be converted to a pit if it occupies one of the bottom 3 levels of the map, to prevent visual oddities. (If the user was able to put a room below the pit, you'd see it floating in the pit from above.)
This is what 'Factory' BTS looks like right now:
![620_2015-06-21_00001](https://cloud.githubusercontent.com/assets/8453732/8443463/3de8de48-1fca-11e5-8021-aba4472050cb.png)
Wheatley or Clean BTS will look different.
My current priority is to get everything working that was in the BEE2, before working on new items or styles

**Comment by harritron2k2** [comment]
Looks nice. The BEE2 Addons need to be in the mod as well. Suggested Skyboxes:
- Wheatley, with other testchambers in the background
- 50s/60s/70s/80s, with rock showing at the sides, with possible goo at the bottom

**Comment by TeamSpen210** [comment]
I'll be adding my addons items at some point. These are all the skyboxes I'm thinking of implementing:
2D (No bottomless pit)
* Overgrown Sunlight
* Darkness
* Orange Glow
3D:
* Reactor Fires: The glows seen in the last few levels of the campaign from the imminent destruction of the reactor.
* Clean BTS: Various chambers in the distance, pillars, catwalks, vactubes
* Wheatley BTS: Like clean but also with destroyed chambers as well
* Factory BTS: Cramped pits with various machinery, turret storage
* Portal 1 BTS: Mostly a gradual fade into the orange glow seen behind test walls
* Art Therapy BTS: A water-filled 1980s era reservoir the chambers are built in
* Test Shaft: Bare cave walls extending down into blackness
* Test Sphere: An enrichment sphere filled with goo. This just makes the chamber seem less enclosed.

**Comment by ellingtonisland** [comment]
will we also be able to open up the walls and ceiling to make a wheatley test chamber look professional?

**Comment by harritron2k2** [comment]
If you want to make a test look "professional", you should use hammer for the little details.
Use PETI first then in the console do the command puzzlemaker_export yourmapname

**Comment by xsantosis** [comment]
There is some problems that make people dont use hammer, some of them, for example, when you export the map to hammer editor it breaks the trigger lights of the large observation rooms and also of the small ones making the puzzle looks very dark, and there is ZERO tutorials on internet explaining how to fix this.

**Comment by TeamSpen210** [comment]
When using the BEE2 you shouldn't export to the editor like that. That command doesn't run the custom compiler, so it won't do all of the modifications. In the BEE2 app set 'spawn at' in the Compile Options window to 'elevator', and then preview the map normally. Then you can edit sdk_content/maps/preview.vmf, and save it under another name.

**Comment by harritron2k2** [comment]
I have some more suggestions:
- Maybe make a skybox that shows blue sky behind overgrown plants, to show that the test is a bit below the surface (I've seen some tests have this in overgrown maps)
- Make catwalks crushable, like in Wheatley BTS
- Make a 50s/60s/70s/80s BTS style, showing pump stations as items

**Comment by BenVlodgi** [comment]
@xsantosis @harritron2k2 If you want to make your test look professional... don't make it in the PTI. Use the PTI for making puzzles, then use hammer to (from scratch) make the map. The best maps are made from scratch so that they don't have to be held back by the PTI layout and design limitations.
