### ISSUE TITLE
Portal 2 crashes after building map

### ISSUE THREAD

**Issue by harritron2k2** [BenVlodgi/BEE2.4#66]
When I build my puzzle, it takes about 5 minutes to build, then it starts loading, and then P2 crashes with a window saying something like Warning: no free edicts. It worked fine before, but now it's crashing due to an item probably. I only added a new item, along with some ones I already had in my puzzle. The new item was goo, which is really glitchy. But I added a catwalk that's supposed to go over a big ledge over the goo with no walls to the sides. I don't know what's causing it, but if I figure out what item it is, I'll post it here.

EDIT: Its the goo. It glitches

**Comment by TeamSpen210** [comment]
I'm automatically adding certain particle systems to give a nice effect. I should probably add a way to turn it off, since it could exceed the entity limit like this.

**Comment by harritron2k2** [comment]
Never mind then, if it's a max entity error, I get it now
