### ISSUE TITLE
suggestion: implement something that can change photo's shown on loading screen when map loads in portal 2

### ISSUE THREAD

**Issue by ellingtonisland** [BenVlodgi/BEE2.4#67]
implement something that can change the photo's displayed when the map loads in portal 2

idea is a directory where custom photo's are placed and when the map compiles and is published those photo's are shown on the loading screen as the map loads. got the idea from the photo of that giant fan in the clean style on the loading screen of a level in portal stories mel.

**Comment by TeamSpen210** [comment]
I can't change the loading screen in a PeTI map.
