### ISSUE TITLE
Bottomless pits in next pre-release?

### ISSUE THREAD

**Issue by harritron2k2** [BenVlodgi/BEE2.4#68]
Are you going to be adding more skyboxes like reactor fires and Wheatley BTS in the next release, and make a alternative version of goo to toggle the bottomless pits?

**Comment by TeamSpen210** [comment]
Probably not the next release, but yes. I can't make any kind of alternative goo item, bottomless pits are part of the regular goo. They only change with the lowest 3 blocks, so you can have both pits and goo in the same map.
