### ISSUE TITLE
Game fails to compile 

### ISSUE THREAD

**Issue by ncrecc** [BenVlodgi/BEE2.4#73]
I know this has been asked before, but it seems that nobody but ellingtonisland and Teamspen210 (obviously) can successfully compile a test chamber. I remember the answer to this had something to do with modifying the config folder, but what exactly is it?

**Comment by harritron2k2** [comment]
I've had it combile correctly. In the new release, I've heard you need to go into your BEE2 directory folder and create a config folder. If it still doesn't combile, open the developer console and look at the error. It should say something like: Couldn't open instance file /Bee2/packages/hazards/goo.vmf. It will tell you what item is not working, then you just need to delete it out of your test, and report it to Teamspen210.

**Comment by ncrecc** [comment]
I already made the config folder, and I get an error even if I make a completely empty test.

**Comment by harritron2k2** [comment]
Are you using BTS or overgrown styles? Because I can't run my maps on those styles because it can't find style instances. Teamspen210 is going to fix this, I already mentioned to him about it.

**Comment by ncrecc** [comment]
I was using BTS style. I guess that's the problem, thanks!

**Comment by ncrecc** [comment]
...Never mind. It still fails, even on Clean.

**Comment by TeamSpen210** [comment]
Open the developer console and paste the message that appears there when you compile.

**Comment by ncrecc** [comment]
VBSP failed.

Config "../config\config.cfg" not found! Using defaults...
Adding metacondition ("remove_blank_inst") with priority 1000!
Adding metacondition ("fix_catapult_targets") with priority 0!
Adding metacondition ("add_voice") with priority 100!
Adding metacondition ("fix_fizz_models") with priority -200!
Adding metacondition ("static_pan") with priority -100!
Adding metacondition ("anti_fizz_bump") with priority 200!
BEE2 VBSP hook initiallised.
Map path is "C:/Program Files (x86)/Steam/SteamApps/common/Portal 2/sdk_content\maps/preview.vmf"
PeTI map detected!
Loading settings...
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 1828, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 387, in load_settings
  File "F:\Git\BEE2.4\src\BEE2_config.py", line 15, in __init__
  File "F:\Git\BEE2.4\src\BEE2_config.py", line 23, in load
OSError: [Errno 22] Invalid argument: 'C:\\Users\nathan\\Downloads\\BEE2pr6.5\\config/compile.cfg'

**Comment by TeamSpen210** [comment]
Make an empty config/ folder in the `C:\Users\nathan\Downloads\BEE2pr6.5\` directory, and then everything should work.

**Comment by ncrecc** [comment]
I already have a config folder, and compile.cfg is already in there. Should I clear out the folder?

**Comment by TeamSpen210** [comment]
Deleting compile.cfg might help, this error is slightly weird though.

**Comment by ncrecc** [comment]
I'm just getting the same error...
