### ISSUE TITLE
Make angled panels change angle via imput

### ISSUE THREAD

**Issue by harritron2k2** [BenVlodgi/BEE2.4#74]
I thought about making the panels change the angle if powered by a button, trigger, etc. You could connect it with ant lines and then a menu pops up when you connect it listing all the angles, like the tractor beam menu that gives a choice of polarity or active.

**Comment by TeamSpen210** [comment]
I can't really do this. The panels don't have the animations for this, plus I'm not able to add extra menus and things like that.

**Comment by BenVlodgi** [comment]
I believe the angle can be set in the editor... but only for its active state... the inactive state will be set then to flush with the wall.
So in short it isn't possible for different inputs to change the angle to different things
