### ISSUE TITLE
Bee2.4pr6.5 Bugs

### ISSUE THREAD

**Issue by LautaroL20** [BenVlodgi/BEE2.4#80]
Hello, today i downloaded the Pre-release 6.5, i extracted it in a new folder, i maked a "config" folder into it, then i launched BEE2.exe, and i found 2 bugs: 

The first bug is related to the "Exporting..." process, wich makes less than half the progress, and then it becomes stagnant forever:

![6205b4ff25fc18eeaf9c705d0ba1eb46](https://cloud.githubusercontent.com/assets/12244376/8562807/3e4edfb6-250d-11e5-9b03-1a4072a62085.png)

And the second bug is related to the pallete items, when you drag an item to the pallete in some cases, this is what happens:

![9cb72a0dc97459e32df1cc01915e1725](https://cloud.githubusercontent.com/assets/12244376/8562815/5bd299b0-250d-11e5-9de8-3eb165a4ca8a.gif)

**Comment by harritron2k2** [comment]
Did you replace the old bee2 folder of did you merge it with the new one? What I did was merge it with 7-zip and just replaced all the files. It had a config folder with all of the config files inside of it.
