### ISSUE TITLE
Bugs and Invisible Stuff

### ISSUE THREAD

**Issue by L0ILKAS** [BenVlodgi/BEE2.4#83]
Hello, recently when trying to install beemod2.4 I came across a few problems:

1. How do I install, where do I put the folders in the zip?
2. No models showing up, but I think that's something to do with issue no.1
3. The same as before, but instead of models its water, and even Chell herself

**Comment by xDadiKx** [comment]
1. You can put it anywhere. But BEE2.4 needs to detect the materials and instances and stuff like that.
2. It's buggy. That's why it is called Pre-Release
3. It's buggy again. Pre-release :)
