### ISSUE TITLE
Remove "bottomlesspit" style option

### ISSUE THREAD

**Issue by TeamSpen210** [BenVlodgi/BEE2.4#90]
Bottomless pits should always be enabled if a "bottomlesspit" block is present in `vbsp_config`. This way a pit can be applied to any stye.

**Comment by ellingtonisland** [comment]
ahh good, you should make pits work across all styles. even overgrown, and portal 1.

**Comment by jccreszMinecraft** [comment]
Portal 1 has more of a realistic approach according to BenVlodgi.
bottomless pits never occurred there anyways.

On Sun, Jul 26, 2015 at 3:45 PM, ellingtonisland <notifications@github.com>
wrote:

> ahh good, you should make pits work across all styles. even overgrown, and
> portal 1.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BenVlodgi/BEE2.4/issues/90#issuecomment-125032523>.
>



-- 
[image: Ice Network 2014]

**Comment by BenVlodgi** [comment]
@jccreszMinecraft what did I say?... I don't recall

**Comment by jccreszMinecraft** [comment]
@BenVlodgi I was asking you how you thought i should do a overgrown/wheatley mix of a map theme and you said that bottomless pits weren't realistic and that portal 1 had a better more realistic approach.

**Comment by BenVlodgi** [comment]
@jccreszMinecraft I see. Yeah, traditionally bottomless bits are a bts feature only. its a normal toxic pit that has had its structure weakened and dissolved by the toxic waste until it broke through and opened up to the BTS below.
supposedly you could have bottomless pits in all styles, but they'd be a bit different from the one we're used to in the BTS

**Comment by TeamSpen210** [comment]
My interpretation is more that the floors are missing, or ripped out by Wheatley. You'll be able to *have* bottomless pits in all styles, it won't necessarily make sense though. There are other flavors of pits I'll be wanting to implement - the voids below the more enclosed factory BTS areas (like the Turret Factory levels), Art Therapy 1980s reservoirs (filled with goo, but with detail around the map), P1 orange glows, and perhaps an Enrichment Sphere if the geometry works out.

**Comment by OnlyFails** [comment]
Is there a link to a tutorial on how to add bottomless pits? I did it once and don't know how I did it.
I can't seem to get the goo pit to become bottomless in any style. (I haven't tried the overgrown one yet because the build process fails when it's selected)

**Comment by FtWApertureScience** [comment]
I would also like a link for a tutorial on how to add Bottomless Pits.

**Comment by Nikita74RU** [comment]
To add a bottomless pit you need to choose 3D/2D Factory/BTS Skybox

**Comment by DatPerkYT** [comment]
How do you add them? ive tried everything they still dont work!!

**Comment by Luke18033** [comment]
This is an old issue from 2017...Bottomless pits have been removed for now, they're going to be reworked.
