### ISSUE TITLE
Pre-Release Bug List. (This one will be used only)

### ISSUE THREAD

**Issue by xDadiKx** [BenVlodgi/BEE2.4#95]
Pr8 Bugs
====
- Can't play test, without even putting anything in the editor(Clean Style and other)

Pr9 Bugs
=======
- Some items are blue errors, once in-game editor. So, placing an item is just a blue error model.

**Comment by TeamSpen210** [comment]
Can you give me the contents of the developer console?

**Comment by xDadiKx** [comment]
I'm just going to quickly verify my cache on portal 2

**Comment by xDadiKx** [comment]
[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file materials/models/props_map_editor/door_frame.vmt
patch, (*insert*), 
KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file materials/models/props_map_editor/crusher_back.vmt
patch, (*insert*), 
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_autoportal_blue.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_autoportal_blue.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_autoportal_frame.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_autoportal_frame.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_catwalk.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_catwalk.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_null.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_null.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_portalgun1.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_portalgun1.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_portalgun2.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_portalgun2.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_portalgun3.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_portalgun3.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_hmw_sendificator.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_hmw_sendificator.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_ant_mag.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_ant_mag.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_ant_router.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_ant_router.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_checkpoint.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_checkpoint.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_checkpoint_sep.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_checkpoint_sep.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_a.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_a.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_b.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_b.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_chamberlock.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_chamberlock.3ds
KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file materials/models/props_map_editor/floor_panels.vmt
patch, (*insert*), 
[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------

==== calling mapspawn.nut
[PORTAL2 PUZZLEMAKER]  Saved puzzle: E:/Games/Valve/Steam/steamapps/common/Portal 2/portal2/puzzles\76561197989930042\autosave.p2c
Parent cvar in client.dll not allowed (r_shadowlod)
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
Redownloading all lightmaps
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF E:/Games/Valve/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 53 (ms)

VBSP failed.

Config "../config\config.cfg" not found! Using defaults...
Adding metacondition ("remove_blank_inst") with priority 1000!
Adding metacondition ("fix_catapult_targets") with priority 0!
Adding metacondition ("add_voice") with priority 100!
Adding metacondition ("fix_fizz_models") with priority -200!
Adding metacondition ("static_pan") with priority -100!
Adding metacondition ("anti_fizz_bump") with priority 200!
BEE2 VBSP hook initiallised.
Map path is "E:/Games/Valve/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
PeTI map detected!
Loading settings...
Settings Loaded!
Parsing Map...
Parsing complete!
Forcing elevator spawn!
['instances/bee2/clean/elevator_sp/door_exit_1.vmf', 'instances/bee2/clean/elevator_sp/door_exit_2.vmf', 'instances/bee2/clean/elevator_sp/door_exit_3.vmf', 'instances/bee2/clean/elevator_sp/door_exit_4.vmf']
File: instances/bee2/clean/elevator_sp/door_exit_3.vmf
Setting exit to 1
File: instances/bee2/clean/point_light.vmf
File: instances/bee2/clean/elevator_sp/door_frame_black.vmf
File: instances/bee2/clean/point_light.vmf
File: instances/bee2/clean/elevator_sp/elevator_entrance.vmf
File: instances/bee2/clean/elevator_sp/elevator_exit.vmf
File: instances/bee2/clean/elevator_sp/door_frame_black.vmf
File: instances/bee2/arrival_departure_transition_ents.vmf
File: instances/bee2/clean/items/observation_room_256.vmf
File: instances/bee2/clean/point_light.vmf
File: instances/bee2/clean/point_light.vmf
File: instances/bee2/clean/elevator_sp/door_entrance_3.vmf
Setting entry to 1
Game Mode: SP
Is Preview: False
Checking Conditions...
Exiting empty condition!
adding overlay instances/BEE2/clean/door_cam.vmf
adding overlay instances/BEE2/clean/door_cam.vmf
adding overlay instances/BEE2/clean/elevator_sp/exit_door.vmf
Starting catwalk generator...
Exiting empty condition!
Adding Singleplayer voice lines!
Adding Voice!
No Data!
Map has attributes:  []
Style Vars: {'fixfizzlerbump': False, 'multiversecave': True, 'nomidvoices': False, 'unlockdefault': False, 'bee_show_trigger': False, 'doorcameras': True, 'allowgoomist': True, 'fixportalbump': False}
Global instances:  {'instances/BEE2/clean/global_ents.vmf'}
Adding Music...
Adding Global PTI Ents
Editing Other Entities...
Editing Brushes...
Editing Overlays...
Editing Triggers...
Collapsing goo triggers...
Done!
Editing Brush Entities...
Removing static indicator toggles...
Done!
Editing WorldSpawn
Saving New Map...
Complete!
Calling original VBSP...
"E:\Games\Valve\Steam\steamapps\common\Portal 2\bin\vbsp_original" -game "E:/Games/Valve/Steam/steamapps/common/Portal 2/portal2/" "E:/Games/Valve/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
VBSP failed! (1)

**Comment by TeamSpen210** [comment]
Try turning on developer mode ('developer 2; clear') and see if you get any further logs. (Put three backticks (\`\`\`) on a line before and after the log to format it nicely.)

**Comment by xDadiKx** [comment]
```[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF E:/Games/Valve/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 33 (ms)

VBSP failed.

Config "../config\config.cfg" not found! Using defaults...
Adding metacondition ("remove_blank_inst") with priority 1000!
Adding metacondition ("fix_catapult_targets") with priority 0!
Adding metacondition ("add_voice") with priority 100!
Adding metacondition ("fix_fizz_models") with priority -200!
Adding metacondition ("static_pan") with priority -100!
Adding metacondition ("anti_fizz_bump") with priority 200!
BEE2 VBSP hook initiallised.
Map path is "E:/Games/Valve/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
PeTI map detected!
Loading settings...
Settings Loaded!
Parsing Map...
Parsing complete!
Forcing elevator spawn!
['instances/bee2/clean/elevator_sp/door_exit_1.vmf', 'instances/bee2/clean/elevator_sp/door_exit_2.vmf', 'instances/bee2/clean/elevator_sp/door_exit_3.vmf', 'instances/bee2/clean/elevator_sp/door_exit_4.vmf']
File: instances/bee2/clean/elevator_sp/door_exit_3.vmf
Setting exit to 1
File: instances/bee2/clean/point_light.vmf
File: instances/bee2/clean/elevator_sp/door_frame_black.vmf
File: instances/bee2/clean/point_light.vmf
File: instances/bee2/clean/elevator_sp/elevator_entrance.vmf
File: instances/bee2/clean/elevator_sp/elevator_exit.vmf
File: instances/bee2/clean/elevator_sp/door_frame_black.vmf
File: instances/bee2/arrival_departure_transition_ents.vmf
File: instances/bee2/clean/items/observation_room_256.vmf
File: instances/bee2/clean/point_light.vmf
File: instances/bee2/clean/point_light.vmf
File: instances/bee2/clean/elevator_sp/door_entrance_3.vmf
Setting entry to 1
Game Mode: SP
Is Preview: False
Checking Conditions...
Exiting empty condition!
adding overlay instances/BEE2/clean/door_cam.vmf
adding overlay instances/BEE2/clean/door_cam.vmf
adding overlay instances/BEE2/clean/elevator_sp/exit_door.vmf
Starting catwalk generator...
Exiting empty condition!
Adding Singleplayer voice lines!
Adding Voice!
No Data!
Map has attributes:  []
Style Vars: {'fixportalbump': False, 'nomidvoices': False, 'bee_show_trigger': False, 'allowgoomist': True, 'unlockdefault': False, 'multiversecave': True, 'fixfizzlerbump': False, 'doorcameras': True}
Global instances:  {'instances/BEE2/clean/global_ents.vmf'}
Adding Music...
Adding Global PTI Ents
Editing Other Entities...
Editing Brushes...
Editing Overlays...
Editing Triggers...
Collapsing goo triggers...
Done!
Editing Brush Entities...
Removing static indicator toggles...
Done!
Editing WorldSpawn
Saving New Map...
Complete!
Calling original VBSP...
"E:\Games\Valve\Steam\steamapps\common\Portal 2\bin\vbsp_original" -game "E:/Games/Valve/Steam/steamapps/common/Portal 2/portal2/" "E:/Games/Valve/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
VBSP failed! (1)```

**Comment by TeamSpen210** [comment]
Still nothing useful there... Delete `E:/Games/Valve/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.log`, recompile, and then paste the contents of that log file.

**Comment by xDadiKx** [comment]
So once I delete the preview.log? Then I play the map again?

**Comment by TeamSpen210** [comment]
Yes, otherwise you'll also get the log for every compile you've ever done.

**Comment by xDadiKx** [comment]
There's lots of text inside the log. So I played the map, and an lot of text came up, should I copy it "all"

**Comment by TeamSpen210** [comment]
Look through it backwards, and see if talks about any errors. If if doesn't just copy it all.

**Comment by xDadiKx** [comment]
Alright

**Comment by xDadiKx** [comment]
Nothing intersting at all? Some things are 0% in this part, is that bad?
Object names       Objects/Maxobjs  Memory / Maxmem  Fullness 
------------       ---------------  ---------------  -------- 
models                 541/1024        25968/49152    (52.8%) 
brushes               2953/8192        35436/98304    (36.0%) 
brushsides           22793/65536      182344/524288   (34.8%) 
planes                9816/65536      196320/1310720  (15.0%) 
vertexes             10417/65536      125004/786432   (15.9%) 
nodes                 4817/65536      154144/2097152  ( 7.4%) 
texinfos               885/12288       63720/884736   ( 7.2%) 
texdata                 55/2048         1760/65536    ( 2.7%) 
dispinfos                0/0               0/0        ( 0.0%) 
disp_verts               0/0               0/0        ( 0.0%) 
disp_tris                0/0               0/0        ( 0.0%) 
disp_multiblend          0/0               0/0        ( 0.0%) 
disp_lmsamples           0/0               0/0        ( 0.0%) 
faces                 3607/65536      201992/3670016  ( 5.5%) 
hdr faces             3607/65536      201992/3670016  ( 5.5%) 
origfaces             3079/65536      172424/3670016  ( 4.7%) 
facebrushes           1336/0            2672/0        ( 0.0%) 
facebrushlists        3607/0           14428/0        ( 0.0%) 
leaves                5359/65536      171488/2097152  ( 8.2%) 
leaffaces             4054/65536        8108/131072   ( 6.2%) 
leafbrushes           5381/65536       10762/131072   ( 8.2%) 
areas                   13/256           104/2048     ( 5.1%) 
surfedges            28445/512000     113780/2048000  ( 5.6%) 
edges                17175/256000      68700/1024000  ( 6.7%) 
LDR worldlights          0/8192            0/819200   ( 0.0%) 
HDR worldlights        259/8192        25900/819200   ( 3.2%) 
leafwaterdata            1/32768          12/393216   ( 0.0%) 
waterstrips            296/32768        2960/327680   ( 0.9%) 
waterverts               0/65536           0/786432   ( 0.0%) 
waterindices          5580/65536       11160/131072   ( 8.5%) 
cubemapsamples           2/1024           32/16384    ( 0.2%) 
overlays                28/512          9856/180224   ( 5.5%) 
LDR lightdata         [variable]           0/0        ( 0.0%) 
HDR lightdata         [variable]     2164460/0        ( 0.0%) 
visdata               [variable]       27671/16777216 ( 0.2%) 
entdata               [variable]      414939/393216   (105.5%) VERY FULL!
LDR ambient table     5359/65536       21436/262144   ( 8.2%) 
HDR ambient table     5359/65536       21436/262144   ( 8.2%) 
LDR leaf ambient      5359/65536      150052/1835008  ( 8.2%) 
HDR leaf ambient      7958/65536      222824/1835008  (12.1%) 
occluders                0/0               0/0        ( 0.0%) 
occluder polygons        0/0               0/0        ( 0.0%) 
occluder vert ind        0/0               0/0        ( 0.0%) 
detail props          [variable]           1/12       ( 8.3%) 
static props          [variable]           1/31458    ( 0.0%) 
pakfile               [variable]     1035742/0        ( 0.0%) 
physics               [variable]     1140433/4194304  (27.2%) 
physics terrain       [variable]           2/1048576  ( 0.0%)

**Comment by TeamSpen210** [comment]
That's actually fine, it's telling you how many of each type of thing is in the map, compared to the maximum. Is this an empty map? It's actually got a lot of models, brushes and other things.

**Comment by xDadiKx** [comment]
It is an empty map. Just with the Entrance door and exit door, and the light room

**Comment by xDadiKx** [comment]
Found something, some things are outside the map.
Static prop models/props_ingame/window_frame_system_60.mdl outside the map (260.00, 260.00, 380.00)
Static prop models/props_ingame/window_frame_system_corner_4.mdl outside the map (258.00, 258.00, 382.00)
Static prop models/props_ingame/window_frame_system_64.mdl outside the map (320.00, 260.00, 260.00)
Static prop models/props_ingame/window_frame_system_corner_4.mdl outside the map (258.00, 258.00, 258.00)
Static prop models/props_ingame/window_frame_system_60.mdl outside the map (320.00, 260.00, 260.00)
Static prop models/props_ingame/window_frame_system_60.mdl outside the map (260.00, 260.00, 320.00)
Static prop models/props_ingame/window_frame_system_60.mdl outside the map (260.00, 260.00, 320.00)
Static prop models/props_ingame/window_frame_system_64.mdl outside the map (448.00, 260.00, 380.00)
Static prop models/props_ingame/window_frame_system_64.mdl outside the map (448.00, 260.00, 260.00)
Static prop models/props_ingame/window_frame_system_64.mdl outside the map (576.00, 260.00, 380.00)
Static prop models/props_ingame/window_frame_system_64.mdl outside the map (576.00, 260.00, 260.00)
Static prop models/props_ingame/window_frame_system_64.mdl outside the map (704.00, 260.00, 380.00)
Static prop models/props_ingame/window_frame_system_corner_4.mdl outside the map (766.00, 258.00, 382.00)
Static prop models/props_ingame/window_frame_system_60.mdl outside the map (704.00, 260.00, 380.00)
Static prop models/props_ingame/window_frame_system_60.mdl outside the map (764.00, 260.00, 320.00)
Static prop models/props_ingame/window_frame_system_corner_4.mdl outside the map (766.00, 258.00, 258.00)
Static prop models/props_ingame/window_frame_system_60.mdl outside the map (764.00, 260.00, 320.00)
Static prop models/props_ingame/window_frame_system_60.mdl outside the map (704.00, 260.00, 260.00)
Static prop models/props_ingame/window_frame_system_64.mdl outside the map (260.00, 260.00, 576.00)
Static prop models/props_ingame/window_frame_system_64.mdl outside the map (260.00, 260.00, 704.00)
Static prop models/props_ingame/window_frame_system_corner_4.mdl outside the map (258.00, 258.00, 766.00)
Static prop models/props_ingame/window_frame_system_60.mdl outside the map (260.00, 260.00, 704.00)
Static prop models/props_ingame/window_frame_system_60.mdl outside the map (320.00, 260.00, 764.00)
Static prop models/props_ingame/window_frame_system_64.mdl outside the map (448.00, 260.00, 516.00)
Static prop models/props_ingame/window_frame_system_64.mdl outside the map (448.00, 260.00, 764.00)
Static prop models/props_ingame/window_frame_system_64.mdl outside the map (576.00, 260.00, 516.00)
Static prop models/props_ingame/window_frame_system_64.mdl outside the map (576.00, 260.00, 764.00)
Static prop models/props_ingame/window_frame_system_64.mdl outside the map (764.00, 260.00, 576.00)
Static prop models/props_ingame/window_frame_system_64.mdl outside the map (704.00, 260.00, 764.00)
Static prop models/props_ingame/window_frame_system_corner_4.mdl outside the map (766.00, 258.00, 766.00)
Static prop models/props_ingame/window_frame_system_60.mdl outside the map (704.00, 260.00, 764.00)
Static prop models/props_ingame/window_frame_system_60.mdl outside the map (764.00, 260.00, 704.00)
Static prop models/props_ingame/window_frame_system_60.mdl outside the map (380.00, 260.00, 388.00)
Static prop models/props_ingame/window_frame_system_corner_4.mdl outside the map (382.00, 258.00, 386.00)
Static prop models/props_ingame/window_frame_system_corner_4.mdl outside the map (258.00, 258.00, 386.00)
Static prop models/props_ingame/window_frame_system_60.mdl outside the map (320.00, 260.00, 388.00)
Static prop models/props_ingame/window_frame_system_60.mdl outside the map (260.00, 260.00, 448.00)
Static prop models/props_ingame/window_frame_system_64.mdl outside the map (380.00, 260.00, 448.00)
Static prop models/props_ingame/window_frame_system_60.mdl outside the map (380.00, 260.00, 448.00)
Static prop models/props_ingame/window_frame_system_60.mdl outside the map (764.00, 260.00, 388.00)
Static prop models/props_ingame/window_frame_system_corner_4.mdl outside the map (766.00, 258.00, 386.00)
Static prop models/props_ingame/window_frame_system_60.mdl outside the map (704.00, 260.00, 388.00)
Static prop models/props_ingame/window_frame_system_60.mdl outside the map (644.00, 260.00, 448.00)
Static prop models/props_ingame/window_frame_system_64.mdl outside the map (764.00, 260.00, 448.00)
Static prop models/props_ingame/window_frame_system_60.mdl outside the map (764.00, 260.00, 448.00)
Static prop models/props_ingame/window_frame_system_64.mdl outside the map (260.00, 4.00, 320.00)
Static prop models/props_ingame/window_frame_system_corner_4.mdl outside the map (258.00, 2.00, 258.00)
Static prop models/props_ingame/window_frame_system_60.mdl outside the map (260.00, 4.00, 320.00)
Static prop models/props_ingame/window_frame_system_60.mdl outside the map (260.00, 64.00, 260.00)
Static prop models/props_ingame/window_frame_system_64.mdl outside the map (260.00, 4.00, 448.00)
Static prop models/props_ingame/window_frame_system_64.mdl outside the map (260.00, 4.00, 576.00)
Static prop models/props_ingame/window_frame_system_64.mdl outside the map (260.00, 64.00, 764.00)
Static prop models/props_ingame/window_frame_system_corner_4.mdl outside the map (258.00, 2.00, 766.00)
Static prop models/props_ingame/window_frame_system_60.mdl outside the map (260.00, 64.00, 764.00)
Static prop models/props_ingame/window_frame_system_60.mdl outside the map (260.00, 4.00, 704.00)
Static prop models/props_ingame/window_frame_system_60.mdl outside the map (260.00, 252.00, 260.00)
Static prop models/props_ingame/window_frame_system_corner_4.mdl outside the map (258.00, 254.00, 258.00)
Static prop models/props_ingame/window_frame_system_64.mdl outside the map (260.00, 192.00, 260.00)
Static prop models/props_ingame/window_frame_system_60.mdl outside the map (260.00, 192.00, 260.00)
Static prop models/props_ingame/window_frame_system_64.mdl outside the map (260.00, 252.00, 448.00)
Static prop models/props_ingame/window_frame_system_64.mdl outside the map (260.00, 252.00, 576.00)
Static prop models/props_ingame/window_frame_system_64.mdl outside the map (260.00, 252.00, 704.00)
Static prop models/props_ingame/window_frame_system_corner_4.mdl outside the map (258.00, 254.00, 766.00)
Static prop models/props_ingame/window_frame_system_60.mdl outside the map (260.00, 252.00, 704.00)
Static prop models/props_ingame/window_frame_system_60.mdl outside the map (260.00, 192.00, 764.00)
Static prop models/props_ingame/window_frame_system_64.mdl outside the map (764.00, 64.00, 260.00)
Static prop models/props_ingame/window_frame_system_corner_4.mdl outside the map (766.00, 2.00, 258.00)
Static prop models/props_ingame/window_frame_system_60.mdl outside the map (764.00, 64.00, 260.00)
Static prop models/props_ingame/window_frame_system_60.mdl outside the map (764.00, 4.00, 320.00)
Static prop models/props_ingame/window_frame_system_64.mdl outside the map (764.00, 4.00, 448.00)
Static prop models/props_ingame/window_frame_system_64.mdl outside the map (764.00, 4.00, 576.00)
Static prop models/props_ingame/window_frame_system_64.mdl outside the map (764.00, 4.00, 704.00)
Static prop models/props_ingame/window_frame_system_corner_4.mdl outside the map (766.00, 2.00, 766.00)
Static prop models/props_ingame/window_frame_system_60.mdl outside the map (764.00, 4.00, 704.00)
Static prop models/props_ingame/window_frame_system_60.mdl outside the map (764.00, 64.00, 764.00)
Static prop models/props_ingame/window_frame_system_64.mdl outside the map (764.00, 252.00, 320.00)
Static prop models/props_ingame/window_frame_system_corner_4.mdl outside the map (766.00, 254.00, 258.00)
Static prop models/props_ingame/window_frame_system_60.mdl outside the map (764.00, 252.00, 320.00)
Static prop models/props_ingame/window_frame_system_60.mdl outside the map (764.00, 192.00, 260.00)
Static prop models/props_ingame/window_frame_system_64.mdl outside the map (764.00, 252.00, 448.00)
Static prop models/props_ingame/window_frame_system_64.mdl outside the map (764.00, 252.00, 576.00)
Static prop models/props_ingame/window_frame_system_60.mdl outside the map (764.00, 252.00, 764.00)
Static prop models/props_ingame/window_frame_system_corner_4.mdl outside the map (766.00, 254.00, 766.00)
Static prop models/props_ingame/window_frame_system_64.mdl outside the map (764.00, 192.00, 764.00)
Static prop models/props_ingame/window_frame_system_60.mdl outside the map (764.00, 192.00, 764.00)

**Comment by TeamSpen210** [comment]
That'd be the issue likely. Do you have any glass/grating items in the map, epsecially butted up against a corner?

**Comment by xDadiKx** [comment]
Nope, just a empty map, it could be it spawns randomly, or the light room, or how it's called.

**Comment by xDadiKx** [comment]
Here is more

FindPortalSide: Couldn't find a good match for which brush to assign to a portal near (2048.0 3584.0 120.0)
Leaf 0 contents: 
Leaf 1 contents: CONTENTS_SOLID 
viscontents (node 0 contents ^ node 1 contents): CONTENTS_SOLID 
This means that none of the brushes in leaf 0 or 1 that touches the portal has CONTENTS_SOLID 
Check for a huge brush enclosing the coordinates above that has contents CONTENTS_SOLID 
Candidate brush IDs: 


FindPortalSide: Couldn't find a good match for which brush to assign to a portal near (1536.0 4096.0 120.0)
Leaf 0 contents: 
Leaf 1 contents: CONTENTS_SOLID 
viscontents (node 0 contents ^ node 1 contents): CONTENTS_SOLID 
This means that none of the brushes in leaf 0 or 1 that touches the portal has CONTENTS_SOLID 
Check for a huge brush enclosing the coordinates above that has contents CONTENTS_SOLID 
Candidate brush IDs: 


FindPortalSide: Couldn't find a good match for which brush to assign to a portal near (512.0 4096.0 120.0)
Leaf 0 contents: 
Leaf 1 contents: CONTENTS_SOLID 
viscontents (node 0 contents ^ node 1 contents): CONTENTS_SOLID 
This means that none of the brushes in leaf 0 or 1 that touches the portal has CONTENTS_SOLID 
Check for a huge brush enclosing the coordinates above that has contents CONTENTS_SOLID 
Candidate brush IDs: 


FindPortalSide: Couldn't find a good match for which brush to assign to a portal near (2048.0 2560.0 120.0)
Leaf 0 contents: 
Leaf 1 contents: CONTENTS_SOLID 
viscontents (node 0 contents ^ node 1 contents): CONTENTS_SOLID 
This means that none of the brushes in leaf 0 or 1 that touches the portal has CONTENTS_SOLID 
Check for a huge brush enclosing the coordinates above that has contents CONTENTS_SOLID 
Candidate brush IDs: 


FindPortalSide: Couldn't find a good match for which brush to assign to a portal near (512.0 2048.0 120.0)
Leaf 0 contents: CONTENTS_SOLID 
Leaf 1 contents: 
viscontents (node 0 contents ^ node 1 contents): CONTENTS_SOLID 
This means that none of the brushes in leaf 0 or 1 that touches the portal has CONTENTS_SOLID 
Check for a huge brush enclosing the coordinates above that has contents CONTENTS_SOLID 
Candidate brush IDs:

**Comment by xDadiKx** [comment]
Leaks and everything, those must be errors. Probably some leaks in the maps

**Comment by xDadiKx** [comment]
So are those confirmed to be errors?

**Comment by TeamSpen210** [comment]
Those would be errors, I'll check them in Hammer tommorrow. Try using PR7 for now.

**Comment by xDadiKx** [comment]
PR7 does the same, but I can wait. I have patience anyway.

**Comment by ellingtonisland** [comment]
obvious bugs i found

- voice lines do not play, glados clean voice doesn't play, clicking gearbox next to voice selection still doesn't work
- bottomless pit still doesn't generate in BTS
- placing autoportal in map still gives dual portal gun. 
- dragging a compressed smoke field into the map crashes game

**Comment by xDadiKx** [comment]
I will add that.

**Comment by xDadiKx** [comment]
I am using this issue only for bugs.
