### ISSUE TITLE
2.4.0pr8 BUG

### ISSUE THREAD

**Issue by k0rny13** [BenVlodgi/BEE2.4#97]
Hello !

I'm really enjoying your mod, but I have a strange bug and I cannot figure it out !

The first time I have installed the last version, according to the fact I never installed a pre-released before, because I was still using BEEMOD2 alpha 2.5, it works fine. I checked the new options in the new windows etc...

I exported once a config, it worked fine, except some bugs dragging death fields into the PETI, crashing the game.

Since then, I cannot export any configs at all. I am always stuck in the last step "Copy Resources 986/2007".

I really wanna use your mod to keep mapping, how can I do to fix that ? I'm also really interested in the "death fizzle", an item I was really waiting for, and I wonder If there is not a way to implement it in the older BEEMOD version ?

Thank you for everything, and I hope you will help me out with that problem :)

**Comment by xDadiKx** [comment]
That's why it's still Pre-Release. There are too much bugs, and also so much items to add.

**Comment by TeamSpen210** [comment]
What do you mean by stuck? It never finishes, or crashes? You could try deleting these folders in your Portal 2 directory: `Portal2/bee2`, and `Portal 2/sdk_content/maps/instances/bee2`. 

I can't really port the death fizzler to earlier versions, it's one item that heavily uses custom compiler code to function.

**Comment by k0rny13** [comment]
By Stuck I mean it never finishes.
I gonna try to delete the folders.

Just to know, will you implement all of the items we used to know in the older beemod ? Like your timer for neurotoxin, angled blocks etc ?

**Comment by TeamSpen210** [comment]
I wil be re-implementing all my items, though I'll probably change how some of them work.
